-- database_upgrade_current_pass.sql
-- Fresh staging file reset on 2026-05-10 after archiving the previous pass.
-- Archived copy: /archive/sql/database_upgrade_current_pass_2026-05-10_before_reset.sql
--
-- Use this file only for the next deployable D1 migration batch.
-- Keep each statement idempotent where possible: CREATE TABLE IF NOT EXISTS,
-- CREATE INDEX IF NOT EXISTS, or guarded ALTER patterns documented beside the change.
--
-- Current state: no pending SQL migration in this fresh pass file.
