-- Release 467 Build 234 — Workflow Help, Empty States & Recovery Guidance
-- Owner-authorized additive Packaging reference data: five editable 2 × 2 inch Soap Cupcake label templates.
-- No existing Packaging project, Product, Inventory, order, Finance, provider or publication data is changed.

INSERT OR IGNORE INTO packaging_templates
(template_key,template_name,package_type,description,page_width_mm,page_height_mm,front_width_mm,front_height_mm,rear_width_mm,rear_height_mm,layout_json,theme_json,is_system,is_active,created_by_user_id,created_at,updated_at)
VALUES
('soap-cupcake-sweet-orange-2in-v1','Soap Cupcake — Sweet Orange — 2 × 2 in','soap_cupcake_label','Owner-supplied Sweet Orange cupcake-soap label direction. Editable square front label; exact 50.8 × 50.8 mm physical size.',50.8,50.8,50.8,50.8,0,0,'{"shape":"square","design_profile":"cupcake_soap_square","safe_margin_mm":2.0,"bleed_mm":1.5,"cupcake_reference_id":"sweet-orange","default_label_title":"Cupcake Soap","default_purpose":"uplifting hand & body soap"}','{"theme_colour":"#FFF5E8","border_colour":"#7A210D","accent_gold":"#E99418","secondary_colour":"#F06A2E","rose_colour":"#F28A2D"}',1,1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('soap-cupcake-charcoal-2in-v1','Soap Cupcake — Charcoal — 2 × 2 in','soap_cupcake_label','Owner-supplied Charcoal cupcake-soap label direction. Editable square front label; exact 50.8 × 50.8 mm physical size.',50.8,50.8,50.8,50.8,0,0,'{"shape":"square","design_profile":"cupcake_soap_square","safe_margin_mm":2.0,"bleed_mm":1.5,"cupcake_reference_id":"charcoal","default_label_title":"Cupcake Soap","default_purpose":"deep-cleansing hand & body soap"}','{"theme_colour":"#F4F1EC","border_colour":"#171717","accent_gold":"#8B8B8B","secondary_colour":"#2C2C2C","rose_colour":"#555555"}',1,1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('soap-cupcake-oatmeal-goat-milk-2in-v1','Soap Cupcake — Oatmeal & Goat Milk — 2 × 2 in','soap_cupcake_label','Owner-supplied Oatmeal & Goat Milk cupcake-soap label direction. Editable square front label; exact 50.8 × 50.8 mm physical size.',50.8,50.8,50.8,50.8,0,0,'{"shape":"square","design_profile":"cupcake_soap_square","safe_margin_mm":2.0,"bleed_mm":1.5,"cupcake_reference_id":"oatmeal-goat-milk","default_label_title":"Cupcake Soap","default_purpose":"gentle hand & body soap"}','{"theme_colour":"#FFF7E8","border_colour":"#5B2C0F","accent_gold":"#C99B55","secondary_colour":"#B77B3D","rose_colour":"#D3B47B"}',1,1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('soap-cupcake-sea-breeze-2in-v1','Soap Cupcake — Sea Breeze — 2 × 2 in','soap_cupcake_label','Owner-supplied Sea Breeze cupcake-soap label direction. Editable square front label; exact 50.8 × 50.8 mm physical size.',50.8,50.8,50.8,50.8,0,0,'{"shape":"square","design_profile":"cupcake_soap_square","safe_margin_mm":2.0,"bleed_mm":1.5,"cupcake_reference_id":"sea-breeze","default_label_title":"Cupcake Soap","default_purpose":"refreshing hand & body soap"}','{"theme_colour":"#F1FCFA","border_colour":"#063E5A","accent_gold":"#B69A55","secondary_colour":"#1499A2","rose_colour":"#59C9C4"}',1,1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('soap-cupcake-lavender-dream-2in-v1','Soap Cupcake — Lavender Dream — 2 × 2 in','soap_cupcake_label','Owner-supplied Lavender Dream cupcake-soap label direction. Editable square front label; exact 50.8 × 50.8 mm physical size.',50.8,50.8,50.8,50.8,0,0,'{"shape":"square","design_profile":"cupcake_soap_square","safe_margin_mm":2.0,"bleed_mm":1.5,"cupcake_reference_id":"lavender-dream","default_label_title":"Cupcake Soap","default_purpose":"calming hand & body soap"}','{"theme_colour":"#FFF7F5","border_colour":"#45205F","accent_gold":"#C99B55","secondary_colour":"#8452A6","rose_colour":"#A985CF"}',1,1,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
