#!/usr/bin/env python3
"""Bake data/site/local-business-schema.json from an exported D1 LocalBusiness row file.
Input defaults to data/site/local-business-d1-export.json so it can be generated by an admin export later.
"""
from __future__ import annotations
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
source = ROOT / 'data/site/local-business-d1-export.json'
target = ROOT / 'data/site/local-business-schema.json'
if source.exists():
    raw = json.loads(source.read_text(encoding='utf-8'))
else:
    raw = json.loads(target.read_text(encoding='utf-8')) if target.exists() else {}
row = raw[0] if isinstance(raw, list) and raw else raw if isinstance(raw, dict) else {}
def parse(value, fallback):
    if isinstance(value, (list, dict)): return value
    try: return json.loads(value or '')
    except Exception: return fallback
schema = {
    '@context': 'https://schema.org',
    '@type': row.get('@type') or row.get('schema_type') or 'LocalBusiness',
    'name': row.get('name') or row.get('business_name') or 'Devil n Dove',
    'url': row.get('url') or row.get('canonical_url') or 'https://devilndove.com/',
    'telephone': row.get('telephone') or '',
    'email': row.get('email') or '',
    'areaServed': parse(row.get('areaServed') or row.get('area_served_json'), ['Ontario']),
    'sameAs': parse(row.get('sameAs') or row.get('same_as_json'), []),
}
target.write_text(json.dumps(schema, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')
print(f'Baked {target.relative_to(ROOT)} from {source.relative_to(ROOT) if source.exists() else "existing schema fallback"}.')
