import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const helper=read('functions/api/_lib/caipMediaIntake.js');
const direct=read('functions/api/admin/caip-media-upload-direct.js');
const client=read('public/js/admin-caip-media-intake.js');
const html=read('admin/creative-assets/index.html');
const repair=read('database_build266_live_payment_refund_compatibility.sql');
assert(/CAIP_MEDIA_INTAKE_BUILD = 'Build 26[6-9]'/.test(helper));
assert(helper.includes("upload_status<>'aborted'"));
assert(helper.includes('reused_existing: true'));
assert(helper.includes('collapseRecoveryFiles'));
assert(helper.includes('registration_pending'));
assert(helper.includes('Binary stored; CAIP registration pending'));
assert(direct.includes('const existing=await bucket.head(row.object_key)'));
assert(direct.includes('already_present:true'));
assert(client.includes("if(serverFile.upload_status==='uploaded'){ return; }"));
assert(client.includes('registration_pending'));
assert(helper.includes('retryUploadedFileRegistration'));
assert(client.includes('Retry CAIP registration'));
assert(read('functions/api/admin/caip-media-intake.js').includes("action==='retry_registration'"));
assert(/admin-caip-media-intake\.js\?v=26[6-9]/.test(html));
assert(repair.includes('ALTER TABLE payment_refunds ADD COLUMN refund_id INTEGER'));
assert(repair.includes('SET refund_id = payment_refund_id'));
assert(repair.includes('CREATE UNIQUE INDEX IF NOT EXISTS uq_payment_refunds_refund_id'));
assert(repair.includes('CREATE TRIGGER trg_payment_refunds_sync_refund_id_after_insert'));
assert(repair.includes('customer_documents_build266_backup'));
console.log('Build 266 CAIP dedupe/idempotence and live refund compatibility checks: PASS');
