import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=(p)=>fs.readFileSync(new URL(`../${p}`, import.meta.url),'utf8');
const api=read('functions/api/admin/creative-process.js');
const ui=read('public/js/admin-creative-process.js');
const css=read('css/styles.css');
const dashboard=read('admin/index.html');
const migration=read('database_build274_creative_process_lifecycle_corrections.sql');
const full=read('database_full_schema.sql');
const store=read('database_store_schema.sql');
const manifest=read('functions/api/_lib/fullSchemaRequirements.js');
assert.match(api,/const BUILD = '274'/);
assert.match(api,/action==='void_event'/);
assert.match(api,/action==='correct_inventory_use'/);
assert.match(api,/reverseInventoryPost/);
assert.match(api,/COALESCE\(entry_status,'active'\)='active'/);
assert.match(ui,/Concept → work → evidence → content → completion/);
assert.match(ui,/Planned material → actual review → inventory posting/);
assert.match(ui,/I confirm this material has actually been used/);
assert.match(ui,/Remove \/ undo entire entry/);
assert.match(ui,/Correct actual usage/);
assert.match(css,/Build 274/);
assert.match(dashboard,/Website Media &amp; Content Studio/);
assert.match(dashboard,/Creative Project Workflow/);
assert.match(dashboard,/Release &amp; Go-Live Center/);
assert.match(dashboard,/Advanced release tools/);
assert.match(migration,/ADD COLUMN entry_status/);
assert.match(full,/entry_status TEXT NOT NULL DEFAULT 'active'/);
assert.match(store,/entry_status TEXT NOT NULL DEFAULT 'active'/);
assert.match(manifest,/"schema_build":27[4-9]|"schema_build":[3-9][0-9]{2,}/);
assert.match(manifest,/"void_reason"/);
console.log('Build 274 Creative Process lifecycle / correction / dashboard consolidation checks: PASS');
