import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=(p)=>fs.readFileSync(p,'utf8');
const client=read('public/js/admin-creative-assets.js');
const html=read('admin/creative-assets/index.html');
const css=read('css/styles.css');
const guide=read('docs/creative-asset-intelligence-platform/18_Operator_Workflow_Guide.md');
assert(client.includes('function projectOptions()'));
assert(client.includes('id="caipProjectSelect"'));
assert(client.includes('Open any CAIP project here, including standalone/social projects'));
assert(client.includes('Create / refresh from Content Studio'));
assert(!client.includes('derivatives.slice(0, 6)'));
assert(client.includes('class="caip-ops-scroll"'));
assert(client.includes('Planned items are shown first. Scroll to review every plan.'));
assert(client.includes('What you have actually done'));
assert(client.includes('You do not need a derivative plan for every uploaded file.'));
assert(css.includes('.caip-ops-scroll{'));
assert(css.includes('max-height:420px'));
assert(html.includes('Build 271 • Master Creative Automation • Stage 3'));
assert(/admin-creative-assets\.js\?v=27[12]/.test(html));
assert(guide.toLowerCase().includes('safe probe'));
assert(guide.includes('Approve plan'));
assert(guide.includes('Standalone project selector rule'));
console.log('Build 271 CAIP operator clarity checks: PASS');
