import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=(p)=>fs.readFileSync(new URL(`../${p}`, import.meta.url),'utf8');
const cpJs=read('public/js/admin-creative-process.js');
const cpApi=read('functions/api/admin/creative-process.js');
const csJs=read('public/js/admin-content-studio.js');
const csApi=read('functions/api/admin/content-studio.js');
const helper=read('functions/api/_lib/contentAutomationStudio.js');
const css=read('css/styles.css');
const index=read('MARKDOWN_INDEX.md');
assert.match(cpJs,/directInventorySearch/);
assert.match(cpJs,/data-inventory-search/);
assert.match(cpJs,/What this blueprint is/);
assert.match(cpJs,/CAIP source assets/);
assert.match(cpApi,/output_media_context/);
assert.match(cpApi,/caip_approved_evidence/);
assert.doesNotMatch(cpApi,/Select at least one reviewed timeline entry first/);
assert.match(csApi,/create_from_creative_project/);
assert.match(csApi,/creative_project_id.*creative_work_project_id/);
assert.match(csJs,/Creative Process projects/);
assert.match(csJs,/does <strong>not<\/strong> create another Creative Project/);
assert.match(helper,/attachContentProjectToExistingCreativeWorkCaip/);
assert.match(helper,/raw_private_source/);
assert.match(helper,/Project Journal/);
assert.match(helper,/if \(!standalone\).*google-business-profile-photos/s);
assert.match(css,/Build 273/);
assert.match(css,/creative-output-context-grid/);
assert.match(index,/Only two mutable current authorities/);
console.log('Build 273 CAIP / Creative Process / Content Studio workflow consolidation checks: PASS');
