#!/usr/bin/env python3
"""Build 428 local-only remaining parity safety regression."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LIVE = (ROOT / 'scripts' / 'build428_live_remaining_parity_evidence.py').read_text(encoding='utf-8')
MEM = (ROOT / 'scripts' / 'build428_membership_nonexecuting_preview.py').read_text(encoding='utf-8')
ADD = (ROOT / 'scripts' / 'build428_production_additive_execution.py').read_text(encoding='utf-8')
DOC = (ROOT / 'database_membership_tier_policy_runtime_parity.sql').read_text(encoding='utf-8')

checks = 0
failures: list[str] = []


def check(condition: bool, label: str) -> None:
    global checks
    checks += 1
    if not condition:
        failures.append(label)


check("PRODUCT_POSTCHECK = ROOT / 'build427_production_product_number_postcheck.local.json'" in LIVE, 'remaining evidence requires Build 427 Product-number postcheck artifact')
check("payload.get('pass') is not True" in LIVE, 'remaining evidence refuses non-green Product-number prerequisite')
check("PROD_NAME = 'devilndove-prod'" in LIVE and "PROD_ID = '0dc8fa3e-319c-45f7-a515-34c8acd89fcf'" in LIVE, 'remaining evidence hard-pins Production')
check("DEV_NAME = 'devilndove-dev'" in LIVE and "DEV_ID = 'dbc1615b-dcbe-4951-973b-b47c99c73bfa'" in LIVE, 'remaining evidence hard-pins Development evidence target')
check("stream.reconfigure(encoding='utf-8', errors='replace')" in LIVE, 'remaining evidence is Windows UTF-8 safe')
check('D1 mutation capability: NONE' in LIVE and 'R2/provider mutation capability: NONE' in LIVE, 'remaining evidence declares read-only capability')
check(all(name in LIVE for name in ['lookup_email', 'code_suffix', 'ip_hash', 'user_agent', 'result_status']), 'Gift Card five-column evidence scope retained')
check('gift_card_lookup_lockouts' in LIVE and 'idx_gift_card_lookup_lockouts_status' in LIVE, 'Gift Card lockout evidence retained')
check('metadata_json' in LIVE and 'idx_notification_outbox_product' in LIVE, 'Notification metadata/index evidence retained')
check('idx_product_image_annotations_product_image_build197' in LIVE, 'Build 197 annotation index evidence retained')
check("FRACTIONAL_TABLES = [" in LIVE and all(t in LIVE for t in ['site_item_inventory','site_inventory_movements','creative_project_inventory_posts','creative_project_inventory_reversals','product_material_return_audit']), 'five fractional families retained')
check('orphan_queries' in LIVE and 'supplier_purchase_order_items' in LIVE, 'Product/FK orphan refresh retained')
check("'search_query_terms_rows': search_rows" in LIVE and "'__sql_test_rows': sql_test_rows" in LIVE and "'caip_media_upload_files_rows': caip_rows" in LIVE, 'preserve/exclude evidence retained')
check("'gift_card_authorized': False" in LIVE and "'notification_authorized': False" in LIVE and "'annotation_authorized': False" in LIVE and "'rebuild_authorized': False" in LIVE, 'remaining authorization flags all default false')
check("'production_mutation_executed': False" in LIVE and "'production_promotion_open': False" in LIVE, 'remaining live evidence cannot claim mutation/promotion')
check(all(column in DOC for column in ['policy_id','tier_code','title','short_description','benefits_json','badge_color','sort_order','is_visible','created_at','updated_at']), 'Build 395 canonical Membership authority has all ten columns')
check('ZERO EXECUTABLE STATEMENTS' in MEM and 'Production mutation authorization: NOT RECEIVED' in MEM, 'Membership preview remains inert and unauthorized')
check(all(token in ADD for token in ['AUTHORIZE-BUILD428-PROD-GIFT-CARD','AUTHORIZE-BUILD428-PROD-NOTIFICATION','AUTHORIZE-BUILD428-PROD-ANNOTATION-INDEX']), 'Build 428 additive stages remain separately token-gated')
check("'d1', 'export', PROD_NAME" in ADD and 'backup_sha256' in ADD and 'MAX_BACKUP_AGE_SECONDS = 1800' in ADD, 'every additive stage has a fresh full Production backup boundary')
check('row_count_preserved' in ADD and "after['row_count'] == before['row_count']" in ADD and 'Membership' not in ADD, 'additive controller proves row preservation and excludes rebuild families')

if failures:
    print(f'BUILD 428 REMAINING PARITY SAFETY REGRESSION: FAIL ({len(failures)}/{checks} failed)')
    for failure in failures:
        print(' -', failure)
    raise SystemExit(1)

print(f'BUILD 428 REMAINING PARITY SAFETY REGRESSION: PASS ({checks}/{checks})')
print('Product-number prerequisite source boundary: PASS')
print('Per-family Production backup boundary: PASS')
print('Remaining additive authorization inferred: NO')
print('Membership executable SQL generated by regression: NONE')
print('Cloudflare access: NONE')
print('Production mutation executed: NO')
print('PRODUCTION PROMOTION: CLOSED')
