import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(path.dirname(new URL(import.meta.url).pathname),'..');
const read=(p)=>fs.readFileSync(path.join(root,p),'utf8');
const helper=read('functions/api/_lib/caipMediaIntake.js');
const endpoint=read('functions/api/admin/caip-media-intake.js');
const client=read('public/js/admin-caip-media-intake.js');
const process=read('public/js/admin-creative-process.js');
assert(/CAIP_MEDIA_INTAKE_BUILD = 'Build 26[5-9]'/.test(helper));
assert(!helper.includes('creative_project_key,content_project_id,product_id'));
assert(helper.includes('Private R2 multipart initialization failed for'));
assert(helper.includes('DIRECT_UPLOAD_MAX_BYTES = 90 * 1024 * 1024'));
assert(helper.includes('completeDirectUploadFile'));
assert(read('functions/api/admin/caip-media-upload-direct.js').includes('bucket.put'));
assert(client.includes('/api/admin/caip-media-upload-direct'));
for(const ext of ['mpeg','avi','mkv','mts','m2ts','tiff'])assert(helper.includes(ext));
assert(endpoint.includes('CAIP_R2_MULTIPART_INIT_FAILED'));
assert(endpoint.includes("private_bucket_available:privateBucketAvailable(context.env)"));
assert(endpoint.includes("integer(new URL(context.request.url).searchParams.get('creative_project_id'))"));
assert(client.includes('error_code'));
assert(client.includes('need attention'));
assert(process.includes('prepareCaipWorkspaceTop'));
assert(!process.includes('creative-assets/?creative_project_id=${p.creative_work_project_id}'));
assert(/admin-caip-media-intake\.js\?v=26[5-9]/.test(read('admin/creative-assets/index.html')));
console.log('Build 265 CAIP upload diagnostics and productless-project routing checks: PASS');
