import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=(p)=>fs.readFileSync(p,'utf8');
const client=read('public/js/admin-caip-media-intake.js');
const helper=read('functions/api/_lib/caipMediaIntake.js');
const html=read('admin/creative-assets/index.html');
assert(/CAIP_MEDIA_INTAKE_BUILD = 'Build 27[0-9]'/.test(helper));
assert(/admin-caip-media-intake\.js\?v=27[0-9]/.test(html));
assert(client.includes('function integrityFailure(file)'));
assert(client.includes('Source replacement required'));
assert(client.includes('Preserved historical upload attempt — no transfer is running.'));
assert(client.includes("const integrityFailures=files.filter((file)=>integrityFailure(file)); const normalFiles=files.filter((file)=>!integrityFailure(file));"));
assert(client.includes("integrityIssue?'Needs Re-upload'"));
assert(client.includes('Re-upload source safely'));
console.log('Build 270 CAIP integrity-failure presentation checks: PASS');
