#!/usr/bin/env python3
"""Guard the active System Gate against stale release-specific provenance labels."""
from pathlib import Path
import subprocess
import sys
ROOT=Path(__file__).resolve().parents[1];WORKFLOW=ROOT/'.github/workflows/system-gate.yml';FAIL=[]
def req(ok,msg):
    if not ok: FAIL.append(msg)
text=WORKFLOW.read_text(encoding='utf-8')
for token in ("'current-development-authority.json'","'release467-*.json'",'python scripts/current_system_gate_provenance_gate.py','python scripts/current_regression_evidence.py','/tmp/current-development-url','/tmp/current-development-d1-authority.json','/tmp/current-development-deploy-proof','/tmp/current-regression-evidence.json','name: current-development-deploy-proof','name: current-regression-evidence','Current Development Preview ${GITHUB_SHA}'):req(token in text,f'missing current System Gate provenance token: {token}')
for stale in ('Release 465 Build 3 safety statement','Release 465 Build 3 canonical Development Preview','release465-build3-development-deploy-proof','release465-build3-regression-evidence','/tmp/release465-dev-url','/tmp/release465-build3-d1-authority.json','/tmp/release465-build3-development-deploy-proof.json'):req(stale not in text,f'stale active System Gate provenance remains: {stale}')
for historical in ('scripts/release464_update2_gate.py','scripts/release464_update3_gate.py','scripts/release465_build1_gate.py','scripts/release465_build2_gate.py','scripts/release465_build3_gate.py','scripts/release465_performance_budget_gate.py'):req(historical in text,f'historical regression prerequisite missing: {historical}')
def run_current_contract(path,label):
    result=subprocess.run([sys.executable,str(ROOT/path)],cwd=ROOT,text=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=False)
    out=(result.stdout or '').strip();err=(result.stderr or '').strip()
    if out: print(out)
    if err: print(err,file=sys.stderr)
    if result.returncode!=0:
        detail=(err or out or f'{label} gate failed').strip()[-2000:]
        annotation=detail.replace('\r',' ').replace('\n',' | ')
        print(f'::error title=System provenance child failed::{label} failed with exit code {result.returncode}: {annotation}')
        FAIL.append(f"{label} current reliability contract failed: {detail}")

catalog_media_source=(ROOT/'admin/catalog-media/index.html').read_text(encoding='utf-8',errors='replace')
product_editor_source=(ROOT/'admin/product-editor/index.html').read_text(encoding='utf-8',errors='replace')
products_source=(ROOT/'admin/products/index.html').read_text(encoding='utf-8',errors='replace')
product_page_source=(ROOT/'shop/product/index.html').read_text(encoding='utf-8',errors='replace')
build163_current=(('product-media-v163' in catalog_media_source) or ('product-media-v164' in catalog_media_source)) and 'product-editor-v163' in product_editor_source
build164_current='product-media-v164' in catalog_media_source and ('product-editor-v163' in product_editor_source or 'product-editor-v165' in product_editor_source)
build165_current='product-browser-v165' in products_source and 'product-editor-v165' in product_editor_source and 'product-media-v164' in catalog_media_source
build166_current='product-browser-v166' in products_source and any(token in product_page_source for token in ('/public/js/product-detail-v166.js?v=166','/public/js/product-detail-v166.js?v=179','/public/js/product-detail-v166.js?v=180')) and (ROOT/'scripts/release467_build166_gate.py').is_file()

# Explicit calls and their historical formatting are intentional because retained gates inspect this source literally.
run_current_contract('scripts/release467_build62_gate.py', 'Release 467 Build 62')
run_current_contract('scripts/release467_build63_gate.py', 'Release 467 Build 63')
run_current_contract('scripts/release467_build64_gate.py', 'Release 467 Build 64')
run_current_contract('scripts/release467_build65_gate.py', 'Release 467 Build 65')
run_current_contract('scripts/release467_build66_gate.py', 'Release 467 Build 66')
run_current_contract('scripts/release467_build67_gate.py', 'Release 467 Build 67')
run_current_contract('scripts/release467_build68_gate.py', 'Release 467 Build 68')
run_current_contract('scripts/release467_build69_gate.py', 'Release 467 Build 69')
run_current_contract('scripts/release467_build70_gate.py', 'Release 467 Build 70')
run_current_contract('scripts/release467_build71_gate.py', 'Release 467 Build 71')
run_current_contract('scripts/release467_build72_gate.py', 'Release 467 Build 72')
if build163_current or build164_current or build165_current or build166_current:
    print('CURRENT PRODUCT MEDIA PROVENANCE: Build 73 multi-panel Catalog Media DOM contract superseded by Build 163+ selected-Product/image architecture')
else:
    run_current_contract('scripts/release467_build73_gate.py', 'Release 467 Build 73')
run_current_contract('scripts/release467_build74_gate.py', 'Release 467 Build 74')
run_current_contract('scripts/release467_build75_gate.py', 'Release 467 Build 75')
run_current_contract('scripts/release467_build76_gate.py', 'Release 467 Build 76')
run_current_contract('scripts/release467_build77_gate.py', 'Release 467 Build 77')
run_current_contract('scripts/release467_build78_gate.py', 'Release 467 Build 78')
run_current_contract('scripts/release467_build79_gate.py', 'Release 467 Build 79')
run_current_contract('scripts/release467_build80_gate.py', 'Release 467 Build 80')
run_current_contract('scripts/release467_build81_gate.py', 'Release 467 Build 81')
run_current_contract('scripts/release467_build82_gate.py', 'Release 467 Build 82')
run_current_contract('scripts/release467_build83_gate.py', 'Release 467 Build 83')
run_current_contract('scripts/release467_build84_gate.py', 'Release 467 Build 84')
run_current_contract('scripts/release467_build85_gate.py', 'Release 467 Build 85')
run_current_contract('scripts/release467_build86_gate.py', 'Release 467 Build 86')
run_current_contract('scripts/release467_build87_gate.py', 'Release 467 Build 87')
run_current_contract('scripts/release467_build88_gate.py', 'Release 467 Build 88')
run_current_contract('scripts/release467_build89_gate.py', 'Release 467 Build 89')
run_current_contract('scripts/release467_build90_gate.py', 'Release 467 Build 90')
run_current_contract('scripts/release467_build91_gate.py', 'Release 467 Build 91')
run_current_contract('scripts/release467_build92_gate.py', 'Release 467 Build 92')
run_current_contract('scripts/release467_build93_gate.py', 'Release 467 Build 93')
run_current_contract('scripts/release467_build94_gate.py', 'Release 467 Build 94')

build162_current='dd-product-admin-architecture' in products_source and 'product-browser-v162' in products_source
if build166_current:
    print('CURRENT PRODUCT PROVENANCE: Build 166 Product editing/image stabilization succeeds Build 165 compact browser and Build 164 media CRUD')
    run_current_contract('scripts/release467_build164_gate.py','Release 467 Build 164 compatibility')
    run_current_contract('scripts/release467_build166_gate.py','Release 467 Build 166')
elif build165_current:
    print('CURRENT PRODUCT PROVENANCE: Build 165 compact Product browser + image recovery succeeds Build 164 media CRUD')
    run_current_contract('scripts/release467_build164_gate.py','Release 467 Build 164 compatibility')
    run_current_contract('scripts/release467_build165_gate.py','Release 467 Build 165')
elif build164_current:
    print('CURRENT PRODUCT PROVENANCE: Build 154/155 and Build 162 superseded; Build 164 extends Build 163 low-read Product architecture')
    run_current_contract('scripts/release467_build163_gate.py','Release 467 Build 163 compatibility')
    run_current_contract('scripts/release467_build164_gate.py','Release 467 Build 164')
elif build163_current:
    print('CURRENT PRODUCT PROVENANCE: Build 154/155 and Build 162 editor/media contracts superseded by Build 163 low-read Product architecture')
    run_current_contract('scripts/release467_build163_gate.py','Release 467 Build 163')
elif build162_current:
    print('CURRENT PRODUCT PROVENANCE: Build 154/155 historical DOM contract superseded by Build 162 architecture reset')
    run_current_contract('scripts/release467_build162_gate.py','Release 467 Build 162')
else:
    run_current_contract('scripts/release467_build154_gate.py','Release 467 Build 154')
    run_current_contract('scripts/release467_build155_gate.py','Release 467 Build 155')
run_current_contract('scripts/release467_build206_gate.py','Release 467 Build 206')
run_current_contract('scripts/release467_build207_gate.py','Release 467 Build 207')
run_current_contract('scripts/release467_build208_gate.py','Release 467 Build 208')
run_current_contract('scripts/release467_build209_gate.py','Release 467 Build 209')
run_current_contract('scripts/release467_build210_gate.py','Release 467 Build 210')
run_current_contract('scripts/release467_build211_gate.py','Release 467 Build 211')
run_current_contract('scripts/release467_build212_gate.py','Release 467 Build 212')
run_current_contract('scripts/release467_build213_gate.py','Release 467 Build 213')
run_current_contract('scripts/release467_build214_gate.py','Release 467 Build 214')
run_current_contract('scripts/release467_build215_gate.py','Release 467 Build 215')
run_current_contract('scripts/release467_build216_gate.py','Release 467 Build 216')
run_current_contract('scripts/release467_build217_gate.py','Release 467 Build 217')
run_current_contract('scripts/release467_build218_gate.py','Release 467 Build 218')
run_current_contract('scripts/release467_build219_gate.py','Release 467 Build 219')
run_current_contract('scripts/release467_build220_gate.py','Release 467 Build 220')
run_current_contract('scripts/release467_build221_gate.py','Release 467 Build 221')
run_current_contract('scripts/release467_build222_gate.py','Release 467 Build 222')
run_current_contract('scripts/release467_build223_gate.py','Release 467 Build 223')
run_current_contract('scripts/release467_build224_gate.py','Release 467 Build 224')
run_current_contract('scripts/release467_build225_gate.py','Release 467 Build 225')
run_current_contract('scripts/release467_build226_gate.py','Release 467 Build 226')
run_current_contract('scripts/release467_build227_gate.py','Release 467 Build 227')
run_current_contract('scripts/release467_build228_gate.py','Release 467 Build 228')
run_current_contract('scripts/release467_build229_gate.py','Release 467 Build 229')
run_current_contract('scripts/release467_build230_gate.py','Release 467 Build 230')
run_current_contract('scripts/release467_build231_gate.py','Release 467 Build 231')
run_current_contract('scripts/release467_build232_gate.py','Release 467 Build 232')
run_current_contract('scripts/release467_build233_gate.py','Release 467 Build 233')
run_current_contract('scripts/release467_build234_gate.py','Release 467 Build 234')
run_current_contract('scripts/release467_build235_gate.py','Release 467 Build 235')
run_current_contract('scripts/release467_build236_gate.py','Release 467 Build 236')
run_current_contract('scripts/release467_build237_gate.py','Release 467 Build 237')
run_current_contract('scripts/release467_build238_gate.py','Release 467 Build 238')
run_current_contract('scripts/release467_build239_gate.py','Release 467 Build 239')
run_current_contract('scripts/release467_build240_gate.py','Release 467 Build 240')
run_current_contract('scripts/release467_build241_gate.py','Release 467 Build 241')
run_current_contract('scripts/release467_build242_gate.py','Release 467 Build 242')
run_current_contract('scripts/release467_build243_gate.py','Release 467 Build 243')
run_current_contract('scripts/release467_build244_gate.py','Release 467 Build 244')
run_current_contract('scripts/release467_build245_gate.py','Release 467 Build 245')
run_current_contract('scripts/release467_build246_gate.py','Release 467 Build 246')
run_current_contract('scripts/release467_build247_gate.py','Release 467 Build 247')
run_current_contract('scripts/release467_build248_gate.py','Release 467 Build 248')
run_current_contract('scripts/release467_build249_gate.py','Release 467 Build 249')
run_current_contract('scripts/release467_build250_gate.py','Release 467 Build 250')
run_current_contract('scripts/release467_build251_gate.py','Release 467 Build 251')
run_current_contract('scripts/release467_build252_gate.py','Release 467 Build 252')
run_current_contract('scripts/release467_build253_gate.py','Release 467 Build 253')
run_current_contract('scripts/release467_build254_gate.py','Release 467 Build 254')\nrun_current_contract('scripts/release467_build255_gate.py','Release 467 Build 255')

if FAIL:
    print('CURRENT SYSTEM GATE PROVENANCE: FAIL');[print('-',x) for x in FAIL];sys.exit(1)
print('CURRENT SYSTEM GATE PROVENANCE: PASS')