#!/usr/bin/env python3
"""Release 467 Build 123 — Admin Home Dashboard Refresh gate."""
from pathlib import Path
import json,subprocess,sys
ROOT=Path(__file__).resolve().parents[1];FAIL=[]
B122_SHA='8ff2df0616a4a9f23c4e1a92bcf5e501a306e0da';B122_TREE='e87670bb397cee58ed839813ea33851d799b5823'
B122_PROOFS={'system_gate_run':34710867035,'current_application_quality_run':34710867094,'it_admin_runtime_proof_run':34710867066,'branch_hygiene_run':34710867072};B122_PAGES=34710956842;B122_LIVE=34710999276
EXPECTED=['0001_release464_migration_authority.sql','0002_release464_operational_acceptance.sql','0003_release464_business_growth.sql','0004_release465_storefront_quality.sql']
def req(ok,msg):
    if not ok: FAIL.append(msg)
def read(path): return (ROOT/path).read_text(encoding='utf-8',errors='replace')
def load(path): return json.loads(read(path))
def command(args,label):
    r=subprocess.run(args,cwd=ROOT,text=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=False)
    if r.stdout.strip(): print(r.stdout.strip())
    if r.returncode!=0: FAIL.append(f"{label} failed: {(r.stderr or r.stdout).strip()[-3000:]}")
pointer=load('current-development-authority.json');prior=load('release467-build122-admin-workspace-navigation-command-palette.json');current=load('release467-build123-admin-home-dashboard-refresh.json');manifest=load('migrations/canonical/manifest.json');nav=load('data/admin-navigation-modules.json');dashboard=read('public/js/admin-home-dashboard-v123.js');page=read('admin/index.html');provenance=read('scripts/current_system_gate_provenance_gate.py')
req(pointer.get('release')==467 and pointer.get('build')==123,'current pointer must identify Release 467 Build 123');req(pointer.get('title')=='Admin Home Dashboard Refresh','Build 123 title drifted');req(pointer.get('state')=='DEVELOPMENT_GREEN','candidate pointer must retain inherited Development GREEN state');req(pointer.get('accepted_dev_sha')==B122_SHA and pointer.get('accepted_dev_tree_sha')==B122_TREE,'Build 123 accepted baseline must be exact Build 122');req((pointer.get('acceptance')or{})==B122_PROOFS,'Build 123 inherited four-proof baseline mismatch')
last=(pointer.get('restart_integrity')or{}).get('last_fully_verified')or{};req(last.get('build')==122 and last.get('dev_sha')==B122_SHA and last.get('tree_sha')==B122_TREE,'restart integrity must identify exact Build 122');req((last.get('proofs')or{})==B122_PROOFS,'restart Build 122 proof set drifted');prod=pointer.get('production_checkpoint')or{};req(prod.get('build')==122 and prod.get('main_sha')==B122_SHA and prod.get('tree_sha')==B122_TREE,'Production baseline must be exact Build 122');req(prod.get('production_pages_deploy_run')==B122_PAGES and prod.get('production_live_resource_integrity_run')==B122_LIVE,'Build 122 Production proof IDs drifted')
req(prior.get('state')=='PRODUCTION_GREEN','Build 122 must be ingested as Production GREEN');closure=prior.get('final_closure')or{};req(closure.get('dev_sha')==B122_SHA and closure.get('tree_sha')==B122_TREE,'Build 122 final closure SHA/tree mismatch');req((closure.get('proofs')or{})==B122_PROOFS,'Build 122 final proof mismatch');req(closure.get('ingested_by_build')==123,'Build 122 closure must be ingested by Build 123');req('not self-recorded by Build 122' in str(closure.get('recorded_by')or''),'Build 122 non-self-recording provenance missing');pp=prior.get('production_checkpoint')or{};req(pp.get('main_sha')==B122_SHA and pp.get('tree_sha')==B122_TREE and pp.get('production_pages_deploy_run')==B122_PAGES and pp.get('production_live_resource_integrity_run')==B122_LIVE,'Build 122 Production closure mismatch')
req(current.get('state')=='DEVELOPMENT_CLOSURE_CANDIDATE','Build 123 must remain closure candidate');req(current.get('final_closure') is None and current.get('production_checkpoint') is None,'Build 123 must not self-claim later workflow proof')
for token in ('const BUILD = 123','/data/admin-navigation-modules.json','/api/admin/contracts/operations-today-tasks-read?min_count=1','/api/admin/it-operations-control-tower','Promise.allSettled','adminHomeDashboardSummary','adminHomeDashboardToday','adminHomeDashboardWorkspaces','adminHomeDashboardQuickLinks','adminHomeDashboardHealth'):req(token in dashboard,f'Build 123 dashboard missing token: {token}')
for forbidden in ('localStorage','sessionStorage',"method: 'POST'",'setInterval('):req(forbidden not in dashboard,f'Build 123 dashboard contains forbidden behavior: {forbidden}')
req(len(__import__('re').findall(r'<h1(?:\s|>)',page,__import__('re').I))==1,'Admin home must contain exactly one H1');req('Release 467 Build 123' in page and '/public/js/admin-home-dashboard-v123.js?v=467b123' in page,'Admin home Build 123 identity/asset missing');req('/public/js/admin-today-tasks.js' not in page,'Admin home must not duplicate the writable Today Tasks UI');req('/admin/today-tasks/' in page,'Admin home must retain link to full Today Tasks')
modules=nav.get('modules') or [];req([m.get('key') for m in modules]==['storefront','creator','finance','it'],'active admin workspace keys drifted');req(sum(len(s.get('links')or[]) for m in modules for s in(m.get('sections')or[]))>=50,'current navigation manifest unexpectedly lost tools')
files=[str(row.get('file')or'') for row in(manifest.get('migrations')or[]) if isinstance(row,dict)];req(files==EXPECTED,'canonical D1 migration stream must remain exactly 0001-0004');req('0005_' not in json.dumps(manifest),'Build 123 must not introduce migration 0005');req("run_current_contract('scripts/release467_build123_gate.py','Release 467 Build 123')" in provenance,'active System Gate provenance must call Build 123')
for path in ('AI_HANDOFF.md','PROJECT_STATUS_AND_ROADMAP.md','SANITY_HEALTH_CHECK.md','MARKDOWN_INDEX.md','docs/operations/IT_PREFLIGHT_STARTUP_RELEASE_GUIDE.md'):
    body=read(path)
    for token in (B122_SHA,B122_TREE,*[str(x) for x in B122_PROOFS.values()],str(B122_PAGES),str(B122_LIVE)):req(token in body,f'{path} missing Build 122 closure token {token}')
    req('Build 123' in body and 'Admin Home Dashboard Refresh' in body,f'{path} missing Build 123 identity')
for path in ('public/js/admin-home-dashboard-v123.js','functions/api/admin/it-operations-control-tower.js','functions/api/_lib/currentReliability.js','functions/api/admin/current-deployment-preflight.js','public/js/admin-it-control-tower.js'):command(['node','--check',str(ROOT/path)],f'JavaScript syntax {path}')
command(['node','scripts/release467_build123_admin_home_dashboard_test.mjs'],'Build 123 runtime/source proof')
for path,label in (('scripts/current_authority_restart_integrity_gate.py','restart integrity'),('scripts/current_it_release_truth_gate.py','I.T. truth'),('scripts/current_reliability_truth_gate.py','Reliability truth'),('scripts/current_deployment_preflight_truth_gate.py','Deployment Preflight truth')):command([sys.executable,path],label)
if FAIL:
    print('RELEASE 467 BUILD 123 GATE: FAIL');[print('-',x) for x in FAIL];sys.exit(1)
print('RELEASE 467 BUILD 123 GATE: PASS');print('Build 122 six-proof closure: INGESTED BY BUILD 123');print('Admin home: READ-ONLY / FAIL-SOFT / EXISTING AUTHORITIES ONLY');print('Canonical D1 migrations: 0001-0004 / UNCHANGED')
