#!/usr/bin/env python3
from pathlib import Path
import json,sys
R=Path(__file__).resolve().parents[1];F=[]
def t(p): return (R/p).read_text(encoding='utf-8',errors='replace')
def j(p): return json.loads(t(p))
def q(ok,msg):
    if not ok:F.append(msg)
a=j('release467-build277-private-bucket-binding-non-public-exposure-evidence.json')
prev=j('release467-build276-caip-acceptance-evidence-freshness-baseline.json')
p=j('current-development-authority.json')
doc=t('docs/operations/RELEASE_467_BUILD_277_PRIVATE_BUCKET_BINDING_NON_PUBLIC_EXPOSURE_EVIDENCE.md')
road=t('docs/operations/RELEASE_467_CAIP_PRODUCTION_ACCEPTANCE_AUTONOMOUS_BUILDS_276_284.md')
wf=t('.github/workflows/release467-build277-private-bucket-binding-non-public-exposure-evidence.yml')
proxy=t('functions/api/admin/creative-asset-review.js')
sysgate=t('scripts/current_system_gate_provenance_gate.py')
q(a.get('build')==277 and a.get('title')=='Private Bucket Binding & Non-Public Exposure Evidence','Build 277 identity mismatch')
q(a.get('state') in ('DEVELOPMENT_CANDIDATE','DEVELOPMENT_GREEN','PRODUCTION_GREEN'),'Build 277 state mismatch')
pred=a.get('predecessor') or {}
q(pred.get('development_sha')=='073ee3cacb7e7b7cac70e0e23db9ebebf386099f' and pred.get('development_tree_sha')=='baed3242d5757a83832ab8526f940c971983bd73','Build 276 Development predecessor mismatch')
q(pred.get('production_main_sha')=='1bfcb248a8baf8cea42467a75c0dac53884ec5c3' and pred.get('production_tree_sha')=='baed3242d5757a83832ab8526f940c971983bd73' and pred.get('same_tree') is True,'Build 276 Production predecessor mismatch')
q((pred.get('development_proofs') or {}).get('dedicated_gate_run')==36214675710,'Build 276 Development dedicated proof mismatch')
q((pred.get('production_proofs') or {}).get('build_specific_proof_run')==36214858270,'Build 276 Production dedicated proof mismatch')
q(prev.get('state')=='PRODUCTION_GREEN','Build 276 successor-ingested authority must be Production GREEN')
q((prev.get('final_closure') or {}).get('dev_sha')=='073ee3cacb7e7b7cac70e0e23db9ebebf386099f' and (prev.get('final_closure') or {}).get('tree_sha')=='baed3242d5757a83832ab8526f940c971983bd73','Build 276 final Development closure missing')
q((prev.get('production_checkpoint') or {}).get('main_sha')=='1bfcb248a8baf8cea42467a75c0dac53884ec5c3' and (prev.get('production_checkpoint') or {}).get('tree_sha')=='baed3242d5757a83832ab8526f940c971983bd73','Build 276 Production checkpoint missing')
e=a.get('evidence_contract') or {}
q(e.get('lane')=='caip_private_media' and e.get('current_lane_state')=='EVIDENCE_DEPENDENT','Build 277 CAIP lane state mismatch')
q(e.get('dimension')=='deployed_private_bucket_binding_non_public_exposure','Build 277 evidence dimension mismatch')
q(e.get('pages_binding_key')=='CAIP_PRIVATE_MEDIA_BUCKET','Build 277 private binding mismatch')
q(e.get('unauthenticated_direct_r2_head_expected_status')=='DENIAL_4XX_400_401_403' and e.get('direct_r2_object_listing_forbidden') is True,'Build 277 direct R2 denial expectation drift')
q(e.get('unauthenticated_review_proxy_expected_status')==401 and e.get('permissive_cors_forbidden') is True,'Build 277 live proxy boundary drift')
q(e.get('object_listing_permitted') is False and e.get('object_download_permitted') is False and e.get('r2_mutation_permitted') is False,'Build 277 object safety drift')
q(e.get('fresh_dimensions_after_runtime_green')==1 and e.get('required_dimensions_total')==3 and e.get('overall_lane_after_runtime_green')=='EVIDENCE_DEPENDENT','Build 277 acceptance interpretation drift')
for token in ('Build 277 — Private Bucket Binding & Non-Public Exposure Evidence','Build 278 — Authenticated Private Review & Range-Streaming Acceptance Refresh'): q(token in road,f'Roadmap missing {token}')
for token in ('1/3','direct R2 S3','HTTP `401`','Bucket presence alone remains insufficient','Build 278'): q(token in doc,f'Build 277 document missing {token}')
for token in ('r2.cloudflarestorage.com','build277-r2-head-status.txt','creative-asset-review?token=build277-no-session','build277-private-bucket-non-public-evidence','PAGES_CONTROL_PLANE_PLUS_UNAUTHENTICATED_R2_HEAD_AND_LIVE_PROXY'): q(token in wf,f'Build 277 workflow evidence transport missing: {token}')
q(proxy.find('getAdminUserFromRequest')>=0 and proxy.find('getAdminUserFromRequest')<proxy.find('authorizeSecureReviewGrant'),'Secure review must authenticate administrator before grant authorization')
for token in ("Cache-Control', 'private, no-store","Cross-Origin-Resource-Policy', 'same-origin","Referrer-Policy', 'no-referrer","X-Frame-Options', 'DENY"): q(token in proxy,f'Secure review privacy header missing: {token}')
q('Access-Control-Allow-Origin' not in proxy,'Secure review must not enable permissive CORS')
q('development_sha: 073ee3cacb7e7b7cac70e0e23db9ebebf386099f' in wf and 'production_sha: 1bfcb248a8baf8cea42467a75c0dac53884ec5c3' in wf,'Build 277 workflow predecessor drift')
q("run_current_contract('scripts/release467_build277_gate.py','Release 467 Build 277')" in sysgate,'System Gate missing Build 277')
cur=int(p.get('build') or 0);q(p.get('release')==467 and cur>=277,'Current authority must retain Build 277 or successor')
if cur==277:
    q(p.get('title')=='Private Bucket Binding & Non-Public Exposure Evidence' and p.get('state')=='DEVELOPMENT_GREEN','Current Build 277 pointer mismatch')
    q(p.get('accepted_dev_sha')=='073ee3cacb7e7b7cac70e0e23db9ebebf386099f' and p.get('accepted_dev_tree_sha')=='baed3242d5757a83832ab8526f940c971983bd73','Current Build 277 accepted predecessor mismatch')
    q((p.get('production_checkpoint') or {}).get('main_sha')=='1bfcb248a8baf8cea42467a75c0dac53884ec5c3','Current Build 277 Production predecessor mismatch')
    q(int(p.get('next_build') or 0)==278,'Current Build 277 successor pointer mismatch')
else:
    q(a.get('state')=='PRODUCTION_GREEN','Build 277 successor-ingested authority must be Production GREEN')
    q((a.get('final_closure') or {}).get('dev_sha')=='8ebe7a3a0c3460d35fbf2e1509bdb728b82db927' and (a.get('final_closure') or {}).get('tree_sha')=='3451ae4990328425ef6929643f1c04efe03d9f37','Build 277 final Development closure mismatch')
    q((a.get('production_checkpoint') or {}).get('main_sha')=='552fe0fb1b192c7fd123c9a7369eea9f352f639e' and (a.get('production_checkpoint') or {}).get('tree_sha')=='3451ae4990328425ef6929643f1c04efe03d9f37','Build 277 final Production closure mismatch')
    q((p.get('production_checkpoint') or {}).get('main_sha')=='552fe0fb1b192c7fd123c9a7369eea9f352f639e','Build 278+ current Production baseline must be exact Build 277')
    q(int(p.get('next_build') or 0)>=279,'Build 278+ must advance beyond Build 278 successor')
for k,v in (a.get('safety') or {}).items(): q(v is False,f'Build 277 safety drift: {k}')
print('RELEASE 467 BUILD 277 PRIVATE BUCKET BINDING NON-PUBLIC EXPOSURE EVIDENCE')
if F:
    print('FAIL');[print('-',x) for x in F];sys.exit(1)
print('PASS')
print('Runtime proof is sanitized and read-only; no private object list/download is authorized.')
print('A GREEN dedicated workflow satisfies private-bucket/non-public exposure as 1/3 fresh dimensions; overall CAIP remains EVIDENCE_DEPENDENT.')
print('Next: Build 278 — Authenticated Private Review & Range-Streaming Acceptance Refresh')
