import fs from 'node:fs';
const [input,sha,output]=process.argv.slice(2);const raw=JSON.parse(fs.readFileSync(input,'utf8'));const sets=Array.isArray(raw)?raw:(raw.results||[]);
if(sets.length!==6)throw new Error('Unexpected Build 367 statement count '+sets.length);
const reads=sets.map(x=>Number(x?.meta?.rows_read||0)),aggregate=reads.reduce((a,b)=>a+b,0);if(aggregate>20000)throw new Error('Rows-read ceiling exceeded '+aggregate);
const rows=i=>Array.isArray(sets[i]?.results)?sets[i].results:[];const row=i=>rows(i)[0]||{};
const promo=row(0),grey=row(1),search=row(2),unprofiled=rows(3),summary=row(4),integrity=row(5);
if(Number(promo.creative_work_project_id||0)!==5)throw new Error('35th promo identity missing');
if(Number(grey.creative_work_project_id||0)!==6)throw new Error('Grey Hair identity missing');
if(Number(summary.active_projects||0)!==5)throw new Error('Expected five active Creative Projects');
for(const k of ['duplicate_caip_source_identities','duplicate_content_source_identities','duplicate_maker_story_profiles','foreign_key_violations'])if(Number(integrity[k]||0)!==0)throw new Error('Integrity drift '+k+'='+integrity[k]);
const queue=[];const push=x=>queue.push({...x,workbench_write_capability:'none',completion_persistence:false,owner_assignment_persistence:false,acknowledgement_persistence:false,resolution_persistence:false});
const promoBlocked=String(promo.outcome_status||'unknown')==='unknown'||String(promo.story_review_status||'')!=='reviewed'||Number(promo.public_story_candidate||0)!==1;
if(promoBlocked)push({gap_key:'35th_promo_real_outcome_evidence',gap_family:'35TH_PROMO_REAL_OUTCOME_EVIDENCE',priority:1,target_id:5,target_title:String(promo.project_title||'35th promo'),current_state:'FACTUAL_OUTCOME_EVIDENCE_REQUIRED',
 required_inputs:['real execution/process evidence','real result evidence','real lesson evidence','substantive Maker Story actual result + lesson facts'],
 observed_completion:{execution_events:Number(promo.execution_events||0),result_events:Number(promo.result_events||0),lesson_events:Number(promo.lesson_events||0),story_review_status:String(promo.story_review_status||''),public_story_candidate:Number(promo.public_story_candidate||0),outcome_status:String(promo.outcome_status||'unknown')},
 completion_signal:'Execution/result/lesson evidence exists, substantive factual profile is complete, then explicit human story review/public-candidate decisions can occur.',
 next_safe_human_action:'Record only what actually happened in the existing Creative Process evidence intake, then remeasure.',workspace_href:'/admin/creative-process/?project_id=5',source_authority:'Creative Process project 5 + Maker Story profile'});
if(Number(grey.source_evidence_needs_review||0)>0||Number(grey.reviewed_story_plans||0)===0||Number(grey.maker_story_profiles||0)===0)push({gap_key:'grey_hair_source_evidence_review',gap_family:'GREY_HAIR_SOURCE_EVIDENCE_REVIEW',priority:1,target_id:6,target_title:String(grey.project_title||'Grey Hair'),current_state:Number(grey.source_evidence_needs_review||0)>0?'SOURCE_EVIDENCE_REVIEW_REQUIRED':'STORY_PLAN_OR_PROFILE_READINESS_REQUIRED',
 required_inputs:['explicit review of each remaining source-evidence range','required synchronization/capture prerequisites','human-reviewed story plan before Maker Story profile'],
 observed_completion:{active_source_evidence:Number(grey.active_source_evidence||0),approved_source_evidence:Number(grey.approved_source_evidence||0),source_evidence_needs_review:Number(grey.source_evidence_needs_review||0),reviewed_story_plans:Number(grey.reviewed_story_plans||0),maker_story_profiles:Number(grey.maker_story_profiles||0)},
 completion_signal:'No active source range remains needs-review and the downstream human-reviewed story-plan prerequisites are satisfied.',
 next_safe_human_action:'Review the existing Grey Hair source ranges explicitly; do not infer public-use rights or auto-create a story.',workspace_href:'/admin/grey-hair-story-readiness/',source_authority:'CAIP source-evidence review + Grey Hair story planning'});
if(Number(search.import_batches||0)===0||Number(search.live_rows||0)===0||Number(search.fresh_rows||0)===0)push({gap_key:'real_search_console_export',gap_family:'REAL_SEARCH_CONSOLE_EXPORT',priority:1,target_id:null,target_title:'Google Search Console evidence',current_state:Number(search.live_rows||0)>0?'REAL_EVIDENCE_STALE_NON_ACTIONABLE':'EVIDENCE_PENDING_NO_REAL_EXPORT',
 required_inputs:['genuine Google Search Console Performance CSV','explicit real-export confirmation','report end date when the CSV has no Date column'],
 observed_completion:{import_batches:Number(search.import_batches||0),live_rows:Number(search.live_rows||0),fresh_rows:Number(search.fresh_rows||0),clicks:Number(search.clicks||0),impressions:Number(search.impressions||0),latest_report_date:String(search.latest_report_date||'')},
 completion_signal:'A real confirmed import exists and has query evidence inside the current 30-day actionability window.',
 next_safe_human_action:'Import a genuine Search Console Performance CSV through the existing operator-controlled intake.',workspace_href:'/admin/release-control/runtime-storefront-intelligence/',source_authority:'Search Console import + audit/revert authority'});
for(const p of unprofiled){if(Number(p.creative_work_project_id||0)===6)continue;push({gap_key:'unprofiled_project_'+Number(p.creative_work_project_id||0),gap_family:'UNPROFILED_MAKER_STORY_EVIDENCE',priority:2,target_id:Number(p.creative_work_project_id||0),target_title:String(p.project_title||'Unprofiled project'),current_state:'MAKER_STORY_EVIDENCE_REQUIRED',
 required_inputs:['real project events/evidence','factual result/lesson prerequisites appropriate to the project','explicit human decision before Maker Story profile creation'],
 observed_completion:{active_events:Number(p.active_events||0),selected_evidence_rows:Number(p.selected_evidence_rows||0),maker_story_profile:0},
 completion_signal:'The existing factual Maker Story readiness contract is met; profile creation/review remains an explicit human action.',
 next_safe_human_action:'Capture and review real project events/evidence in Creative Process; do not create a profile from metadata alone.',workspace_href:'/admin/creative-process/?project_id='+Number(p.creative_work_project_id||0),source_authority:'Creative Process project evidence'});}
queue.sort((a,b)=>a.priority-b.priority||a.target_title.localeCompare(b.target_title));const families=[...new Set(queue.map(x=>x.gap_family))];
const evidence={release:467,build:367,exact_development_sha:sha,statement_count:6,rows_read_by_statement:reads,aggregate_rows_read:aggregate,rows_read_ceiling:20000,queue,queue_summary:{active_workbench_rows:queue.length,active_gap_families:families.length,gap_families:families,unprofiled_projects:unprofiled.length},source_state:{promo,grey_hair:grey,search_console:search,unprofiled_projects:unprofiled,summary,integrity},decision:queue.length?'EXECUTION_WORKBENCH_OPEN_REAL_INPUTS_REQUIRED':'NO_CURRENT_EVIDENCE_GAPS',boundaries:{read_only:true,shadow_task_table:false,owner_assignment_persistence:false,acknowledgement_persistence:false,resolution_persistence:false,completion_persistence:false,no_completion_by_workbench_state:true,business_data_mutation:false,evidence_mutation:false,story_mutation:false,search_console_mutation:false,seo_mutation:false,provider_execution:false,production_d1_contact:false}};
fs.writeFileSync(output,JSON.stringify(evidence,null,2)+'\n');console.log('BUILD367_WORKBENCH=',JSON.stringify(queue));console.log('BUILD367_SUMMARY=',JSON.stringify(evidence.queue_summary));console.log('BUILD367_DECISION=',evidence.decision);console.log('BUILD367_ROWS_READ=',JSON.stringify(reads));console.log('BUILD367_AGGREGATE_ROWS_READ=',aggregate);console.log('BUILD367_EVIDENCE_GAP_EXECUTION_WORKBENCH=GREEN');
