import assert from 'node:assert/strict';
import { buildBusinessHealthReviewSession } from '../functions/api/_lib/businessHealthReviewSession.js';
const empty=buildBusinessHealthReviewSession({period_month:'2026-09',state:'ready',owner_priority_matrix:[]},{actions:[]},{periods:{current:'2026-09'}});
assert.equal(empty.state,'ready');assert.equal(empty.summary.review_step_count,0);assert.equal(empty.boundaries.review_session_persistence,false);assert.equal(empty.boundaries.url_context_only,true);
const financeRow={owner_module:'finance',owner_label:'Finance & Accounting',href:'/admin/month-end/',decision_state:'priority_review',human_decision_required:true,summary:{action_count:2,blocking_count:1,persistent_worsening_count:1,newly_worsening_count:1},action_keys:['month-end:no_outstanding_balance'],trend_signal_keys:['outstanding_balance_cents'],top_action:{key:'month-end:no_outstanding_balance',label:'Outstanding balance must be cleared'}};
const finance=buildBusinessHealthReviewSession({period_month:'2026-09',state:'priority_review',owner_priority_matrix:[financeRow]},{actions:[]},{periods:{current:'2026-09'}});
assert.equal(finance.review_steps.length,1);assert.equal(finance.review_steps[0].review_order,1);assert.match(finance.review_steps[0].context_href,/^\/admin\/month-end\//);assert.match(finance.review_steps[0].context_href,/business_health_source=build120/);assert.match(finance.review_steps[0].context_href,/business_health_period=2026-09/);assert.match(finance.review_steps[0].context_href,/business_health_owner=finance/);assert.equal(finance.review_steps[0].top_action_key,'month-end:no_outstanding_balance');assert.equal(finance.boundaries.mutation_capability,'none');
const unsafe={...financeRow,href:'https://example.com/steal',owner_module:'it',owner_label:'I.T.'};const guarded=buildBusinessHealthReviewSession({period_month:'2026-09',state:'review',owner_priority_matrix:[unsafe]},{actions:[]},{});assert.match(guarded.review_steps[0].context_href,/^\/admin\/\?/);assert.equal(guarded.boundaries.context_persistence,false);assert.equal(guarded.boundaries.accounting_posting,false);assert.equal(guarded.boundaries.provider_execution,false);
console.log('Release 467 Build 120 Business Health review session runtime proof: PASS');
