#!/usr/bin/env python3
"""Release 467 Build 117 — Business Health Period Comparison & Trend Review gate."""
from pathlib import Path
import json,re,subprocess,sys
ROOT=Path(__file__).resolve().parents[1];FAIL=[]
B116_SHA='4661b541df3ad92c70e19c85673560f969cda85b';B116_TREE='475d13cd5fda9e9ac694861c8df44c5ede8a5db0'
B116_PROOFS={'system_gate_run':34699742783,'current_application_quality_run':34699742812,'it_admin_runtime_proof_run':34699742791,'branch_hygiene_run':34699742779};B116_PAGES=34699821018;B116_LIVE=34699867959
EXPECTED=['0001_release464_migration_authority.sql','0002_release464_operational_acceptance.sql','0003_release464_business_growth.sql','0004_release465_storefront_quality.sql']
def req(ok,msg):
    if not ok: FAIL.append(msg)
def read(path): return (ROOT/path).read_text(encoding='utf-8',errors='replace')
def load(path): return json.loads(read(path))
def command(args,label):
    r=subprocess.run(args,cwd=ROOT,text=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=False)
    if r.stdout.strip(): print(r.stdout.strip())
    if r.returncode!=0: FAIL.append(f"{label} failed: {(r.stderr or r.stdout).strip()[-3000:]}")
pointer=load('current-development-authority.json');prior=load('release467-build116-business-health-operator-briefs.json');current=load('release467-build117-business-health-period-comparison.json');manifest=load('migrations/canonical/manifest.json')
helper=read('functions/api/_lib/businessHealthPeriodComparison.js');endpoint=read('functions/api/admin/business-health-period-comparison.js');client=read('public/js/admin-business-health-period-comparison-v117.js');page=read('admin/business-health/index.html');provenance=read('scripts/current_system_gate_provenance_gate.py')
req(pointer.get('release')==467 and pointer.get('build')==117,'current pointer must identify Release 467 Build 117');req(pointer.get('title')=='Business Health Period Comparison & Trend Review','Build 117 title drifted');req(pointer.get('state')=='DEVELOPMENT_GREEN','candidate pointer must retain inherited Development GREEN state');req(pointer.get('accepted_dev_sha')==B116_SHA and pointer.get('accepted_dev_tree_sha')==B116_TREE,'Build 117 accepted baseline must be exact Build 116');req((pointer.get('acceptance')or{})==B116_PROOFS,'Build 117 inherited four-proof baseline mismatch')
last=(pointer.get('restart_integrity')or{}).get('last_fully_verified')or{};req(last.get('build')==116 and last.get('dev_sha')==B116_SHA and last.get('tree_sha')==B116_TREE,'restart integrity must identify exact Build 116');req((last.get('proofs')or{})==B116_PROOFS,'restart Build 116 proof set drifted');prod=pointer.get('production_checkpoint')or{};req(prod.get('build')==116 and prod.get('main_sha')==B116_SHA and prod.get('tree_sha')==B116_TREE,'Production baseline must be exact Build 116');req(prod.get('production_pages_deploy_run')==B116_PAGES and prod.get('production_live_resource_integrity_run')==B116_LIVE,'Build 116 Production proof IDs drifted')
req(prior.get('state')=='PRODUCTION_GREEN','Build 116 must be ingested as Production GREEN');closure=prior.get('final_closure')or{};req(closure.get('dev_sha')==B116_SHA and closure.get('tree_sha')==B116_TREE,'Build 116 final closure SHA/tree mismatch');req((closure.get('proofs')or{})==B116_PROOFS,'Build 116 final proof mismatch');req(closure.get('ingested_by_build')==117,'Build 116 closure must be ingested by Build 117');req('not self-recorded by Build 116' in str(closure.get('recorded_by')or''),'Build 116 non-self-recording provenance missing');pp=prior.get('production_checkpoint')or{};req(pp.get('main_sha')==B116_SHA and pp.get('tree_sha')==B116_TREE and pp.get('production_pages_deploy_run')==B116_PAGES and pp.get('production_live_resource_integrity_run')==B116_LIVE,'Build 116 Production closure mismatch')
req(current.get('state')=='DEVELOPMENT_CLOSURE_CANDIDATE','Build 117 must remain closure candidate');req(current.get('final_closure') is None and current.get('production_checkpoint') is None,'Build 117 must not self-claim later workflow proof');start=(current.get('starting_point')or{}).get('development')or{};req(start.get('sha')==B116_SHA and start.get('tree')==B116_TREE,'Build 117 starting Development identity mismatch')
for token in ('BUSINESS_HEALTH_PERIOD_COMPARISON_BUILD=117','previousPeriod','period_specific_grading_only','profitability_historical_claim:false','it_historical_claim:false',"mutation_capability:'none'",'acknowledgement_persistence:false','resolution_persistence:false','accounting_posting:false','inventory_mutation:false','provider_execution:false'):req(token in helper,f'Build 117 helper missing token: {token}')
for forbidden in (r'\bfetch\s*\(',r'\bdb\.',r'\blocalStorage\.',r'\bsessionStorage\.',r'\bsetInterval\s*\('):req(not re.search(forbidden,helper),f'Build 117 pure helper gained forbidden behavior: {forbidden}')
for token in ('loadRelease465BusinessHealth','buildBusinessHealthPeriodComparison',"role:'read_only_business_health_period_comparison'","format==='markdown'","server_persistence:false","acknowledgement_persistence:false","resolution_persistence:false"):req(token in endpoint,f'Build 117 endpoint missing token: {token}')
req('onRequestPost' not in endpoint,'Build 117 endpoint must expose no POST handler')
for forbidden in ('UPDATE ','INSERT ','DELETE ','CREATE TABLE','ALTER TABLE','DROP TABLE'):req(forbidden not in endpoint.upper(),f'Build 117 endpoint contains forbidden DML/DDL: {forbidden}')
for token in ('b117PeriodComparison','b117Export','data-business-health-period-comparison-build="117"','admin-business-health-period-comparison-v117.js?v=467b117','Build 117 safety boundary'):req(token in page,f'Business Health page missing Build 117 token: {token}')
req(len(re.findall(r'<h1(?:\s|>)',page,re.I))==1,'Business Health page must retain exactly one H1');req('/api/admin/business-health-period-comparison' in client and "method:'GET'" in client and "method:'POST'" not in client,'Build 117 client must remain GET-only');req('format=markdown' in client and 'new Blob' in client and 'No acknowledgement or resolution state was stored' in client,'Build 117 client must expose read-only export boundary')
files=[str(row.get('file')or'') for row in(manifest.get('migrations')or[]) if isinstance(row,dict)];req(files==EXPECTED,'canonical D1 migration stream must remain exactly 0001-0004');req('0005_' not in json.dumps(manifest),'Build 117 must not introduce migration 0005');req("run_current_contract('scripts/release467_build117_gate.py','Release 467 Build 117')" in provenance,'active System Gate provenance must call Build 117');req("run_current_contract('scripts/release467_build116_gate.py','Release 467 Build 116')" not in provenance,'Build 116 must no longer be current provenance gate')
for path in ('AI_HANDOFF.md','PROJECT_STATUS_AND_ROADMAP.md','SANITY_HEALTH_CHECK.md','MARKDOWN_INDEX.md','docs/operations/IT_PREFLIGHT_STARTUP_RELEASE_GUIDE.md'):
    body=read(path)
    for token in (B116_SHA,B116_TREE,*[str(x) for x in B116_PROOFS.values()],str(B116_PAGES),str(B116_LIVE)):req(token in body,f'{path} missing Build 116 closure token {token}')
    req('Build 117' in body and 'Business Health Period Comparison' in body,f'{path} missing Build 117 identity')
for path in ('functions/api/_lib/businessHealthPeriodComparison.js','functions/api/admin/business-health-period-comparison.js','public/js/admin-business-health-period-comparison-v117.js','functions/api/admin/it-operations-control-tower.js','functions/api/_lib/currentReliability.js','functions/api/admin/current-deployment-preflight.js','public/js/admin-it-control-tower.js'):command(['node','--check',str(ROOT/path)],f'JavaScript syntax {path}')
command(['node','scripts/release467_build117_business_health_period_comparison_test.mjs'],'Build 117 runtime proof')
for path,label in (('scripts/current_authority_restart_integrity_gate.py','restart integrity'),('scripts/current_it_release_truth_gate.py','I.T. truth'),('scripts/current_reliability_truth_gate.py','Reliability truth'),('scripts/current_deployment_preflight_truth_gate.py','Deployment Preflight truth')):command([sys.executable,path],label)
if FAIL:
    print('RELEASE 467 BUILD 117 GATE: FAIL');[print('-',x) for x in FAIL];sys.exit(1)
print('RELEASE 467 BUILD 117 GATE: PASS');print('Build 116 six-proof closure: INGESTED BY BUILD 117');print('Business Health period comparison: READ-ONLY / PERIOD-SPECIFIC REVIEW ONLY');print('Persistence / Accounting / Inventory / Creative / provider mutation: ZERO');print('Canonical D1 migrations: 0001-0004 / UNCHANGED')
