import fs from 'node:fs';
const [input,sha,out]=process.argv.slice(2);
const raw=JSON.parse(fs.readFileSync(input,'utf8'));const sets=Array.isArray(raw)?raw:(raw.results||[]);
if(sets.length!==3)throw new Error('Unexpected readiness statement count '+sets.length);
const reads=sets.map(x=>Number(x?.meta?.rows_read||0)),aggregate=reads.reduce((a,b)=>a+b,0);
if(aggregate>20000)throw new Error('Rows-read ceiling exceeded '+aggregate);
const ready=(sets[0]?.results||[])[0]||{},deliverables=sets[1]?.results||[],continuity=(sets[2]?.results||[])[0]||{};
if(Number(ready.creative_work_project_id||0)!==5||String(ready.project_key)!=='CP-MSC1SUG2'||String(ready.project_title)!=='35th promo')throw new Error('Target identity drift');
if(String(ready.story_review_status)!=='needs_review'||Number(ready.public_story_candidate||0)!==0||String(ready.outcome_status)!=='unknown')throw new Error('Maker Story review state drift');
if(Number(ready.review_decision_build||0)!==313||String(ready.review_decision)!=='REMAIN_NEEDS_REVIEW_PENDING_EXECUTION_RESULT_LESSON_EVIDENCE')throw new Error('Build 313 review-decision traceability missing');
if(String(ready.media_rights_scope)!=='separate_never_inferred'||Number(ready.approved_copy_authorizes_publication||0)!==0)throw new Error('Media/publication authority boundary drift');
for(const [k,v] of Object.entries({active_events:1,planning_events:1,non_planning_events:0,selected_evidence:1,selected_execution_evidence:0,approved_locked_deliverables:2,changes_requested_deliverables:17,publications:0,social_rows:0}))if(Number(ready[k]||0)!==v)throw new Error('Readiness drift '+k+'='+ready[k]);
if(deliverables.length!==19)throw new Error('Expected 19 Content Studio deliverables, got '+deliverables.length);
const approved=deliverables.filter(x=>String(x.approval_status)==='approved'&&Number(x.copy_locked||0)===1).map(x=>String(x.deliverable_key)).sort();
if(JSON.stringify(approved)!==JSON.stringify(['blog-article','seo-assets']))throw new Error('Approved/locked source set drift '+JSON.stringify(approved));
if(deliverables.filter(x=>String(x.approval_status)==='changes_requested').length!==17)throw new Error('Changes-requested queue drift');
if(Number(continuity.first_story_published_journal_rows||0)!==1||Number(continuity.first_story_review_first_social_rows||0)!==1||Number(continuity.first_story_posted_social_rows||0)!==0)throw new Error('Accepted first-story continuity drift');
if(Number(continuity.duplicate_content_source_identities||0)!==0||Number(continuity.foreign_key_violations||0)!==0)throw new Error('Identity/integrity drift');
const evidence={release:467,build:314,exact_development_sha:sha,phase:'publication_readiness',statement_count:3,rows_read_by_statement:reads,aggregate_rows_read:aggregate,rows_read_ceiling:20000,readiness:ready,deliverables,continuity,publication_readiness:'BLOCKED',blocked_reason:'MISSING_EXECUTION_RESULT_LESSON_EVIDENCE',publication_mutation:false,social_mutation:false,provider_execution:false,media_rights_inference:false,production_d1_contact:false};
fs.writeFileSync(out,JSON.stringify(evidence,null,2)+'\n');
console.log('BUILD314_PUBLICATION_READINESS=',JSON.stringify(ready));
console.log('BUILD314_ROWS_READ=',JSON.stringify(reads));
console.log('BUILD314_AGGREGATE_ROWS_READ=',aggregate);
console.log('BUILD314_SECOND_STORY_PUBLICATION_READINESS=BLOCKED_GREEN');
