import fs from 'node:fs';
const [input,sha,out]=process.argv.slice(2);const raw=JSON.parse(fs.readFileSync(input,'utf8'));const sets=Array.isArray(raw)?raw:(raw.results||[]);
if(sets.length!==8)throw new Error('Unexpected statement count '+sets.length);
const reads=sets.map(x=>Number(x?.meta?.rows_read||0)),aggregate=reads.reduce((a,b)=>a+b,0);if(aggregate>20000)throw new Error('Rows-read ceiling exceeded '+aggregate);
const row=i=>(sets[i]?.results||[])[0]||{};const pre=row(0),adopted=row(5),safety=row(6),integrity=row(7);
if(Number(pre.creative_work_project_id||0)!==5||String(pre.project_key)!=='CP-MSC1SUG2'||String(pre.project_title)!=='35th promo')throw new Error('Exact second-project preflight mismatch');
if(Number(pre.caip_workspaces||0)!==1||Number(pre.content_packages||0)!==1||Number(pre.caip_assets||0)!==0||Number(pre.private_upload_files||0)!==0)throw new Error('Project 5 identity/media preflight drift');
if(String(adopted.story_kind)!=='maker_story'||String(adopted.story_review_status)!=='needs_review'||Number(adopted.public_story_candidate||0)!==0||String(adopted.outcome_status)!=='unknown')throw new Error('Second Maker Story review-first state mismatch');
if(String(adopted.event_type)!=='planning'||String(adopted.event_title)!=='35th promo - existing project brief'||String(adopted.media_url||'')!==''||Number(adopted.event_public_candidate||0)!==0||Number(adopted.selected||0)!==1)throw new Error('Normalized factual evidence selection mismatch');
for(const k of ['public_event_candidates','public_story_candidates','selected_media_evidence','caip_assets','private_upload_files','publications','social_rows'])if(Number(safety[k]||0)!==0)throw new Error('Build 308 safety boundary drift '+k);
if(Number(integrity.active_projects||0)!==5||Number(integrity.maker_story_profiles||0)!==2||Number(integrity.selected_evidence_rows||0)!==4||Number(integrity.caip_workspaces||0)!==5||Number(integrity.content_packages||0)!==5||Number(integrity.duplicate_caip_source_identities||0)!==0||Number(integrity.duplicate_content_source_identities||0)!==0||Number(integrity.foreign_key_violations||0)!==0)throw new Error('Build 308 global coverage/identity mismatch');
const evidence={release:467,build:308,exact_development_sha:sha,statement_count:8,rows_read_by_statement:reads,aggregate_rows_read:aggregate,rows_read_ceiling:20000,target:{creative_work_project_id:5,project_key:'CP-MSC1SUG2',project_title:'35th promo'},preflight:pre,adopted_profile_and_evidence:adopted,safety,integrity,evidence_origin:'existing Creative Project summary/objective/story_angle normalized into one internal text-only planning event',automatic_publication:false,provider_execution:false,media_rights_inference:false,production_d1_contact:false,schema_change:false};
fs.writeFileSync(out,JSON.stringify(evidence,null,2)+'\n');
console.log('BUILD308_ADOPTED=',JSON.stringify(adopted));
console.log('BUILD308_SAFETY=',JSON.stringify(safety));
console.log('BUILD308_INTEGRITY=',JSON.stringify(integrity));
console.log('BUILD308_ROWS_READ=',JSON.stringify(reads));
console.log('BUILD308_AGGREGATE_ROWS_READ=',aggregate);
console.log('BUILD308_SECOND_REAL_MAKER_STORY_ADOPTION=GREEN');
