#!/usr/bin/env python3
from pathlib import Path
import json,re,sys
R=Path(__file__).resolve().parents[1];F=[]
def t(p):return (R/p).read_text(encoding='utf-8',errors='replace')
def j(p):return json.loads(t(p))
def q(ok,msg):
    if not ok:F.append(msg)
a=j('release467-build323-maker-story-coverage-publication-readiness-continuity.json')
prev=j('release467-build322-buyer-discovery-attribution-seo-review-evidence-continuity.json')
p=j('current-development-authority.json')
sql=t('scripts/release467_build323_continuity.sql')
verify=t('scripts/release467_build323_verify_continuity.mjs')
wf=t('.github/workflows/release467-build323-maker-story-coverage-publication-readiness-continuity.yml')
api=t('functions/api/admin/maker-story-coverage.js')
page=t('admin/maker-story-coverage/index.html')
ui=t('public/js/admin-maker-story-coverage-v323.js')
road=t('docs/operations/RELEASE_467_EVIDENCE_COMPLETION_DISCOVERY_ADOPTION_BUILDS_319_324.md')
q(a.get('build')==323 and a.get('title')=='Maker Story Coverage & Publication Readiness Continuity','Build 323 identity mismatch')
q(prev.get('state')=='PRODUCTION_GREEN','Build 322 Production closure not successor-ingested')
q((prev.get('final_closure') or {}).get('dev_sha')=='ad8f82fa23c943303a04f6273b735c1091913cf3' and (prev.get('final_closure') or {}).get('tree_sha')=='3ba6acc882e399e0d3e6eb2b749ce8f43a215e9e','Build 322 exact Development closure missing')
q((prev.get('production_checkpoint') or {}).get('main_sha')=='1d7ef26655905c057c6c064ef7e2d7bf4c94f6a0' and (prev.get('production_checkpoint') or {}).get('tree_sha')=='3ba6acc882e399e0d3e6eb2b749ce8f43a215e9e','Build 322 Production checkpoint missing')
c=a.get('contract') or {};s=a.get('safety') or {}
q(c.get('expected_active_projects')==5 and c.get('coverage_population')=='ALL_ACTIVE_CREATIVE_PROJECTS','Build 323 five-project coverage contract mismatch')
q(c.get('explicit_story_review_required') is True and c.get('public_story_candidate_required') is True and c.get('approved_content_copy_required') is True and c.get('locked_content_copy_required') is True,'Build 323 human-review/copy readiness contract mismatch')
q(c.get('public_media_rights_separate_from_story_text_readiness') is True and c.get('private_media_never_public_by_inference') is True and c.get('provider_posting_independent') is True,'Build 323 rights/provider boundary mismatch')
q(all(v is False for v in s.values()),'Build 323 safety authority drift')
upper=' '+re.sub(r'--.*','',sql).upper()+' '
for forbidden in (' INSERT ',' UPDATE ',' DELETE ',' CREATE ',' ALTER ',' DROP ',' REPLACE ',' VACUUM ',' REINDEX '):q(forbidden not in upper,'Build 323 measurement must remain read-only: '+forbidden.strip())
for token in ('all active Creative Projects','core_story_complete','human_published_journal_rows','public_allowed_caip_assets','public_allowed_private_uploads','evidence-completion lanes','provider_posted_rows','foreign_key_violations'):q(token.lower() in sql.lower(),'Build 323 SQL missing '+token)
for token in ('MAKER_STORY_EVIDENCE_REQUIRED','FACTUAL_OUTCOME_EVIDENCE_REQUIRED','MAKER_STORY_HUMAN_REVIEW_REQUIRED','PUBLIC_CANDIDATE_REVIEW_REQUIRED','CONTENT_STUDIO_REVIEW_REQUIRED','PUBLICATION_REVIEW_READY','PUBLISHED_REVIEWED_STORY','public_media_rights_separate_from_story_text_readiness:true','publication_mutation:false','production_d1_contact:false'):q(token in verify,'Build 323 verifier missing '+token)
for token in ('D1_ONE_SHOT_EVIDENCE_CAPTURE','FIVE ACTIVE PROJECTS: READ-ONLY COVERAGE','HUMAN STORY REVIEW: REQUIRED','MEDIA RIGHTS: SEPARATE NEVER INFERRED','AUTOMATIC PUBLICATION: ZERO','PROVIDER EXECUTION: ZERO','PRODUCTION D1 CONTACT: ZERO'):q(token in wf,'Build 323 workflow boundary missing '+token)
for token in ('build:BUILD','publication_readiness_is_read_only_classification:true','public_media_rights_separate:true','automatic_publication:false','provider_execution:false'):q(token in api,'Build 323 API missing '+token)
q('onRequestPost' not in api,'Build 323 coverage API must remain GET-only')
for token in ('Release 467 • Build 323','Maker Story Coverage &amp; Publication Readiness Continuity','makerStoryCoverageBuild323Mount','admin-maker-story-coverage-v323.js'):q(token in page,'Build 323 page missing '+token)
for token in ('Build 323 • read-only continuity','Media rights — separate','never auto-creates a Maker Story','provider posting remains independent'):q(token in ui,'Build 323 UI missing '+token)
q('Build 324 — Content Adoption & Discovery Outcomes Renewal IV' in road,'Build 324 successor roadmap missing')
q(int(p.get('build') or 0)>=323,'Current pointer must retain Build 323 or successor')
if int(p.get('build') or 0)==323:q(p.get('state')=='DEVELOPMENT_GREEN' and int(p.get('next_build') or 0)==324,'Build 323 current authority/successor mismatch')
print('RELEASE 467 BUILD 323 MAKER STORY COVERAGE & PUBLICATION READINESS CONTINUITY')
if F:
 print('FAIL');[print('-',x) for x in F];sys.exit(1)
print('PASS')
print('Five-project readiness remains read-only; factual human review and publication traceability are required; media rights remain separate')
print('Next: Build 324 — Content Adoption & Discovery Outcomes Renewal IV')
