#!/usr/bin/env python3
"""Static acceptance for Release 466 Build 1 — Governance, Recovery & Production Reliability."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];FAIL=[]
CANONICAL=['0001_release464_migration_authority.sql','0002_release464_operational_acceptance.sql','0003_release464_business_growth.sql','0004_release465_storefront_quality.sql']
def read(path):
 p=ROOT/path
 if not p.is_file():FAIL.append(f'missing required file: {path}');return''
 return p.read_text(encoding='utf-8',errors='replace')
def req(ok,msg):
 if not ok:FAIL.append(msg)
def has(body,*tokens,label='file'):
 for token in tokens:req(token in body,f'{label} missing required contract: {token}')
a=json.loads(read('release466-build1-governance-recovery-reliability.json') or '{}');req(int(a.get('release') or 0)==466 and int(a.get('build') or 0)==1,'Release 466 Build 1 identity drifted');req(a.get('state')=='development_green_external_ruleset_pending','Build 1 closure state must be Development green with external ruleset pending');req([x.get('id') for x in a.get('items',[])]==[1,2,3,4,5],'Build 1 authority must contain items 1-5');req(a.get('schema_change_required') is False and a.get('migration') is None,'Build 1 must remain schema-neutral');item={int(x.get('id') or 0):x for x in a.get('items',[])};req(item.get(1,{}).get('status')=='development_green_external_ruleset_pending','native ruleset state must remain explicit/pending');req(all(item.get(i,{}).get('status')=='complete_development_green' for i in (2,3,4,5)),'Build 1 items 2-5 must be complete Development green')
for key in ('production_business_mutation','production_schema_mutation','provider_execution','provider_publication','inventory_mutation','accounting_posting','automatic_rollback_execution','raw_r2_delete','request_time_schema_ddl'):req((a.get('safety') or {}).get(key) is False,f'Build 1 safety boundary drifted: {key}')
req((a.get('safety') or {}).get('preview_access_must_remain_enforced') is True,'Preview Access must remain enforced')
te=a.get('technical_evidence') or {};req(a.get('technical_green_source_sha')=='96c51f4f2f7ebeb8035b2d4db4c8c3aadf2ffe2c','Build 1 technical-green SHA drifted');req(int(te.get('system_gate_run') or 0)==33463654502 and int(te.get('system_gate_source_job') or 0)==99718937820 and int(te.get('system_gate_deploy_job') or 0)==99718991277,'Build 1 canonical System Gate evidence drifted');req(te.get('exact_preview')=='https://60d84da5.devilndove-site.pages.dev','Build 1 technical Preview drifted');req(int(te.get('build1_proof_run') or 0)==33463654504 and int(te.get('build1_source_proof_job') or 0)==99718937752 and int(te.get('build1_runtime_proof_job') or 0)==99718977134,'Build 1 supplemental proof run evidence drifted');req(int(te.get('proof_artifact_id') or 0)==9784113538 and te.get('proof_artifact_sha256')=='16de3662d3d0c86097603f1538b59b6d0bde1dcd7906d65280c0657b3d19d378','Build 1 proof artifact drifted');req(int(te.get('development_d1_tables_including_cloudflare_reserved') or 0)==583 and int(te.get('development_application_tables_excluding_cf_reserved') or 0)==582 and int(te.get('restored_application_tables') or 0)==582,'Recovery table-count proof drifted');req(te.get('recovery_integrity_check')=='ok' and int(te.get('recovery_foreign_key_violations') or 0)==0 and te.get('recovery_raw_export_retained') is False and te.get('recovery_restored_database_retained') is False,'Recovery safety/integrity evidence drifted');req(int(te.get('structural_identity_count_development') or 0)==603 and int(te.get('structural_identity_count_production') or 0)==603 and te.get('structural_missing_in_production')==[] and te.get('structural_extra_in_production')==[] and te.get('canonical_migration_identity_match') is True and te.get('canonical_proof_identity_match') is True,'Structural drift evidence drifted');req(int(te.get('production_reliability_score') or 0)==100 and te.get('production_reliability_status')=='green' and int(te.get('production_open_critical_incidents') or 0)==0 and int(te.get('production_open_error_incidents') or 0)==0 and int(te.get('production_foreign_key_violations') or 0)==0 and te.get('production_bindings_proven') is True and te.get('production_business_rows_read') is False and te.get('production_mutation') is False,'Production reliability evidence drifted')
manifest=json.loads(read('migrations/canonical/manifest.json') or '{}');req([x.get('file') for x in manifest.get('migrations',[])]==CANONICAL,'Release 466 Build 1 must preserve exact canonical migration sequence 0001-0004');req(not (ROOT/'migrations/canonical/0005_release466_governance_recovery_reliability.sql').exists(),'Build 1 must not invent migration 0005')
policy=read('.github/RELEASE466_BRANCH_PROTECTION_POLICY.md');has(policy,'Target branch: `dev`','Target branch: `main`','Block branch deletion','Block force pushes','Require linear history','status check context `source-gate`','external repository-governance action',label='branch protection policy')
rollback=read('scripts/release466_rollback_plan.py');has(rollback,'--is-ancestor','schema_rollback_allowed','business_data_restore_automatic','target_must_have_prior_successful_production_deployment',label='rollback planner');rollback_workflow=read('.github/workflows/production-rollback-readiness.yml');has(rollback_workflow,'workflow_dispatch','RELEASE466_ROLLBACK_READINESS','Rollback action executed: NO','Production mutation: ZERO',label='rollback readiness workflow');req('pages deploy' not in rollback_workflow and '--target production --apply' not in rollback_workflow and 'git push' not in rollback_workflow,'rollback readiness must never execute rollback/deploy/migration')
recovery=read('scripts/release466_recovery_rehearsal.py');drift=read('scripts/release466_drift_detector.py');health=read('scripts/release466_production_health_proof.py');has(recovery,'ephemeral_local_sqlite','PRAGMA integrity_check','expected_application_tables','raw_export_artifact_retained',label='recovery rehearsal');has(drift,'schema_identity_and_canonical_migration_authority_only','business_rows_read','--fail-on-drift',label='drift detector');has(health,'production-reliability-slo-snapshot','current_snapshot_not_historical_uptime','business_rows_read','production_mutation',label='Production reliability proof')
helper=read('functions/api/_lib/release466Reliability.js');endpoint=read('functions/api/admin/release466-reliability.js');page=read('admin/reliability/index.html');client=read('public/js/admin-release466-reliability.js');has(helper,'loadRelease466Reliability','current_snapshot_not_historical_uptime','native_github_ruleset',"mutation_capability:'none'",'production_mutation:false',label='Release 466 reliability helper');req('onRequestPost' not in endpoint and 'onRequestPut' not in endpoint and 'onRequestDelete' not in endpoint,'Reliability API must remain GET-only');req(page.lower().count('<h1')==1,'Reliability cockpit must have exactly one H1');has(client,'/api/admin/release466-reliability','Reliability score','Structural drift check',label='Reliability client')
release=json.loads(read('development-release.json') or '{}');req(int(release.get('release') or 0)==466 and release.get('convergence_state')=='release466_build1_development_green_external_ruleset_pending','development-release Release 466 Build 1 state drifted');req((release.get('current_release_database_state') or {}).get('release466_build1_schema_change_required') is False,'development-release must state no Build 1 schema change');runtime=read('functions/api/_lib/releaseAuthority.js');has(runtime,'CURRENT_RELEASE = 466','Operational Resilience and Commercial Readiness',label='Release 466 runtime authority')
roadmap=read('docs/operations/RELEASE_466_FOUR_BUILD_ROADMAP.md');has(roadmap,'Build 1 — Governance, Recovery & Production Reliability','Build 2 — Runtime & Storefront Intelligence','Build 3 — Revenue & Business Intelligence','Build 4 — External Acceptance & Commercial Readiness',label='Release 466 roadmap');workflow=read('.github/workflows/release466-build1-proof.yml');has(workflow,'Wait for exact-SHA canonical System Gate','release466_recovery_rehearsal.py','release466_drift_detector.py','release466_production_health_proof.py','release466-build1-recovery-drift-proof',label='Release 466 supplemental proof workflow')
print('RELEASE 466 BUILD 1 — GOVERNANCE, RECOVERY & PRODUCTION RELIABILITY');print('Items 2-5: DEVELOPMENT GREEN');print('Item 1 native GitHub ruleset: EXTERNAL SETTING PENDING');print('D1 schema migration: NONE / canonical 0001-0004 preserved');print('Recovery: 582/582 application tables / integrity OK / 0 FK');print('Structural drift: 603/603 identities / NONE');print('Production reliability: GREEN 100 / READ ONLY')
if FAIL:
 print('RELEASE 466 BUILD 1 GATE: FAIL');[print(f'{i:03d}. {m}') for i,m in enumerate(FAIL,1)];raise SystemExit(1)
print('RELEASE 466 BUILD 1 GATE: PASS')
