#!/usr/bin/env python3
from pathlib import Path
import json,sys
R=Path(__file__).resolve().parents[1];F=[]
def t(p):return (R/p).read_text(encoding='utf-8',errors='replace')
def j(p):return json.loads(t(p))
def q(ok,msg):
    if not ok:F.append(msg)
a=j('release467-build283-planned-vs-actual-inventory-operator-acceptance.json');prev=j('release467-build282-content-studio-bridge-operator-acceptance.json');b274=j('release467-build274-creative-process-planned-vs-actual-inventory-lifecycle.json');p=j('current-development-authority.json')
doc=t('docs/operations/RELEASE_467_BUILD_283_PLANNED_VS_ACTUAL_INVENTORY_OPERATOR_ACCEPTANCE.md');road=t('docs/operations/RELEASE_467_CAIP_PRODUCTION_ACCEPTANCE_AUTONOMOUS_BUILDS_276_284.md');wf=t('.github/workflows/release467-build283-planned-vs-actual-inventory-operator-acceptance.yml');runtime=t('scripts/release467_build283_operator_acceptance.py');api=t('functions/api/admin/creative-process.js');compat=t('functions/api/admin/creative-process-compat.js');ui=t('public/js/admin-creative-process.js');post=t('functions/api/_lib/creativeInventoryPostConsumer.js');reverse=t('functions/api/_lib/creativeInventoryReversalConsumer.js');sysgate=t('scripts/current_system_gate_provenance_gate.py')
q(a.get('build')==283 and a.get('title')=='Planned-vs-Actual Inventory Operator Acceptance','Build 283 identity mismatch');q(a.get('state') in ('DEVELOPMENT_CANDIDATE','DEVELOPMENT_GREEN','PRODUCTION_GREEN'),'Build 283 state mismatch')
pred=a.get('predecessor') or {};q(pred.get('development_sha')=='9cd1892c878839982ab18c7a7745101fbe2015ed' and pred.get('development_tree_sha')=='0f5448333945f050cd7c5a32b5fd9a363f1e2bad','Build 282 Development predecessor mismatch');q(pred.get('production_main_sha')=='034ab92e57b17765a7b946182256fb32ae25cf87' and pred.get('production_tree_sha')=='0f5448333945f050cd7c5a32b5fd9a363f1e2bad' and pred.get('same_tree') is True,'Build 282 Production predecessor mismatch')
dp=pred.get('development_proofs') or {};pp=pred.get('production_proofs') or {};q(dp.get('system_gate_run')==36360504891 and dp.get('current_application_quality_run')==36360504892 and dp.get('it_admin_runtime_proof_run')==36360505049 and dp.get('branch_hygiene_run')==36360505047 and dp.get('dedicated_gate_run')==36360505062,'Build 282 Development proof mismatch');q(pp.get('production_pages_deploy_run')==36360676716 and pp.get('production_live_resource_integrity_run')==36360712757 and pp.get('products_browser_proof_run')==36360712745 and pp.get('products_route_proof_run')==36360712799 and pp.get('build_specific_proof_run')==36360676884,'Build 282 Production proof mismatch')
q(prev.get('state')=='PRODUCTION_GREEN','Build 282 successor-ingested authority must be Production GREEN');q((prev.get('final_closure') or {}).get('dev_sha')=='9cd1892c878839982ab18c7a7745101fbe2015ed' and (prev.get('final_closure') or {}).get('tree_sha')=='0f5448333945f050cd7c5a32b5fd9a363f1e2bad','Build 282 final Development closure missing');q((prev.get('production_checkpoint') or {}).get('main_sha')=='034ab92e57b17765a7b946182256fb32ae25cf87' and (prev.get('production_checkpoint') or {}).get('tree_sha')=='0f5448333945f050cd7c5a32b5fd9a363f1e2bad','Build 282 Production checkpoint missing')
life=b274.get('lifecycle') or {};q(b274.get('state')=='PRODUCTION_GREEN' and life.get('classification')=='PLANNED_ESTIMATES_SEPARATE_FROM_REVIEWED_AND_POSTED_ACTUALS','Build 274 lifecycle source authority drift');q(life.get('planned_material_estimates_move_inventory') is False and life.get('posted_actual_direct_edit_allowed') is False and life.get('history_preserved') is True,'Build 274 lifecycle safety drift')
e=a.get('evidence_contract') or {};q(e.get('environment')=='DEVELOPMENT_EXACT_SHA_LIVE_OPERATOR_ACCEPTANCE' and e.get('live_runtime_required') is True and e.get('static_source_is_live_acceptance') is False,'Build 283 runtime evidence contract drift');q(e.get('existing_non_archived_project_required') is True and e.get('existing_material_event_required') is True and e.get('matching_real_inventory_item_required') is True and e.get('synthetic_event_forbidden') is True,'Build 283 real source requirement drift');q(e.get('review_action')=='review_material' and e.get('explicit_post_action')=='post_material_inventory' and e.get('explicit_reversal_action')=='reverse_material_inventory','Build 283 operator action contract drift');q(e.get('automatic_inventory_movement') is False and e.get('finance_posting') is False and e.get('inventory_returns_to_starting_quantity') is True,'Build 283 net-neutral safety contract drift')
for token in ("'post_material_inventory'","'record_inventory_use'","'correct_inventory_use'","'void_event'","planned_actual_inventory_lifecycle","PLANNED_ESTIMATES_SEPARATE_FROM_REVIEWED_AND_POSTED_ACTUALS","posted_voids_use_compensating_reversal:true"):q(token in api,f'Build 274/283 API contract missing: {token}')
for token in ("action==='review_material'","action==='reverse_material_inventory'","Inventory has not been consumed.","reverseCreativeInventoryThroughContract"):q(token in compat,f'Build 283 compatibility operator contract missing: {token}')
q("postCreativeInventoryThroughContract" in post and "CONTRACT_ID = 'inventory-post'" in post,'Inventory-owned posting contract missing');q("reverseCreativeInventoryThroughContract" in reverse and "CONTRACT_ID = 'inventory-reverse'" in reverse,'Inventory-owned reversal contract missing')
for token in ('Planned estimate — inventory unchanged','Reviewed actual — not posted','Actual inventory posted','Inventory-owned compensating ledger'):q(token in ui,f'Build 283 operator lifecycle label missing: {token}')
for token in ('Wait for exact Development System Gate','current-development-deploy-proof','BUILD283_EXACT_DEV_BASE_URL','release467_build283_operator_acceptance.py','build283-planned-vs-actual-inventory-operator-acceptance-evidence','Production branch remains runtime-read-only for Build 283'):q(token in wf,f'Build 283 workflow missing {token}')
for token in ('existing Development material event','reviewed_actual_unposted_verified','explicit_inventory_post_verified','compensating_reversal_verified','inventory_returned_to_starting_quantity','finance_journal_unchanged','PLANNED_ACTUAL_INVENTORY_OPERATOR_ACCEPTED_REAL_EVIDENCE'):q(token in runtime,f'Build 283 runtime proof missing {token}')
for token in ('Build 283 — Planned-vs-Actual Inventory Operator Acceptance','Build 284 — CAIP Production Acceptance Closure & Outcomes Renewal'):q(token in road,f'Roadmap missing {token}')
for token in ('existing','review_material','post_material_inventory','reverse_material_inventory','net inventory unchanged','finance journal','build 284'):q(token in doc.lower(),f'Build 283 document missing {token}')
q("run_current_contract('scripts/release467_build283_gate.py','Release 467 Build 283')" in sysgate,'System Gate missing Build 283')
cur=int(p.get('build') or 0);q(p.get('release')==467 and cur>=283,'Current authority must retain Build 283 or successor')
if cur==283:
    q(p.get('title')=='Planned-vs-Actual Inventory Operator Acceptance' and p.get('state')=='DEVELOPMENT_GREEN','Current Build 283 pointer mismatch');q(p.get('accepted_dev_sha')=='9cd1892c878839982ab18c7a7745101fbe2015ed' and p.get('accepted_dev_tree_sha')=='0f5448333945f050cd7c5a32b5fd9a363f1e2bad','Current Build 283 accepted predecessor mismatch');q((p.get('production_checkpoint') or {}).get('main_sha')=='034ab92e57b17765a7b946182256fb32ae25cf87' and (p.get('production_checkpoint') or {}).get('tree_sha')=='0f5448333945f050cd7c5a32b5fd9a363f1e2bad','Current Build 283 Production predecessor mismatch');q(int(p.get('next_build') or 0)==284 and p.get('next_build_title')=='CAIP Production Acceptance Closure & Outcomes Renewal','Current Build 283 successor pointer mismatch')
proj=p.get('creative_process_planned_vs_actual_inventory_operator_acceptance') or {};q(proj.get('review_action')=='review_material' and proj.get('post_action')=='post_material_inventory' and proj.get('reversal_action')=='reverse_material_inventory' and proj.get('automatic_inventory_movement') is False and proj.get('finance_posting') is False,'Current Build 283 projection mismatch')
s=a.get('safety') or {}
for k in ('schema_change','request_time_schema_mutation','production_d1_business_data_mutation','production_r2_mutation','creative_process_project_creation','creative_work_event_creation','product_creation','fake_product_creation','automatic_inventory_movement','inventory_direct_stock_rewrite','destructive_usage_history_delete','finance_posting','provider_execution','provider_publication','public_promotion','product_publication','payment_or_refund','production_business_data_copy','secret_capture','raw_operator_identity_capture','synthetic_acceptance','exact_sha_requirement_relaxed','named_proof_requirement_relaxed'):q(s.get(k) is False,f'Build 283 safety drift: {k}')
q(s.get('development_material_review') is True and s.get('development_explicit_inventory_post_and_reversal') is True,'Build 283 bounded Development mutation must be explicit')
print('RELEASE 467 BUILD 283 PLANNED-VS-ACTUAL INVENTORY OPERATOR ACCEPTANCE')
if F:
    print('FAIL');[print('-',x) for x in F];sys.exit(1)
print('PASS');print('Runtime GREEN target: real planned material -> reviewed unposted actual -> explicit Inventory post -> compensating reversal; net stock and Finance unchanged.');print('Next: Build 284 — CAIP Production Acceptance Closure & Outcomes Renewal')
