#!/usr/bin/env python3
"""Release 467 Build 124 — Canada-First Market Controls & U.S. Shipping Pause gate."""
from pathlib import Path
import json,re,subprocess,sys
ROOT=Path(__file__).resolve().parents[1];FAIL=[]
B123_SHA='d0485a9892331e8da2cec42ed54850893b4a7ab1';B123_TREE='e5c15b8c2d1c1a9f091a688b9f525e8b7ce73e20'
B123_PROOFS={'system_gate_run':34719387920,'current_application_quality_run':34719387904,'it_admin_runtime_proof_run':34719387901,'branch_hygiene_run':34719387931};B123_PAGES=34719482161;B123_LIVE=34719519418
EXPECTED=['0001_release464_migration_authority.sql','0002_release464_operational_acceptance.sql','0003_release464_business_growth.sql','0004_release465_storefront_quality.sql']
def req(ok,msg):
    if not ok: FAIL.append(msg)
def read(path): return (ROOT/path).read_text(encoding='utf-8',errors='replace')
def load(path): return json.loads(read(path))
def command(args,label):
    r=subprocess.run(args,cwd=ROOT,text=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=False)
    if r.stdout.strip(): print(r.stdout.strip())
    if r.returncode!=0: FAIL.append(f"{label} failed: {(r.stderr or r.stdout).strip()[-3000:]}")
pointer=load('current-development-authority.json');prior=load('release467-build123-admin-home-dashboard-refresh.json');current=load('release467-build124-canada-first-market-controls-us-shipping-pause.json');manifest=load('migrations/canonical/manifest.json')
core=read('public/js/commerce-policy-core.js');runtime=read('public/js/commerce-policy-runtime.js');bootstrap=read('public/js/core/dd-public-module-visibility.mjs');home=read('index.html');provenance=read('scripts/current_system_gate_provenance_gate.py');doc=read('docs/operations/RELEASE_467_BUILD_124_CANADA_FIRST_MARKET_CONTROLS_US_SHIPPING_PAUSE.md')
it=read('functions/api/admin/it-operations-control-tower.js');reliability=read('functions/api/_lib/currentReliability.js');preflight=read('functions/api/admin/current-deployment-preflight.js')
req(pointer.get('release')==467 and pointer.get('build')==124,'current pointer must identify Release 467 Build 124');req(pointer.get('title')=='Canada-First Market Controls & U.S. Shipping Pause','Build 124 title drifted');req(pointer.get('state')=='DEVELOPMENT_GREEN','candidate pointer must retain inherited Development GREEN state');req(pointer.get('accepted_dev_sha')==B123_SHA and pointer.get('accepted_dev_tree_sha')==B123_TREE,'Build 124 accepted baseline must be exact Build 123');req((pointer.get('acceptance')or{})==B123_PROOFS,'Build 124 inherited four-proof baseline mismatch')
last=(pointer.get('restart_integrity')or{}).get('last_fully_verified')or{};req(last.get('build')==123 and last.get('dev_sha')==B123_SHA and last.get('tree_sha')==B123_TREE,'restart integrity must identify exact Build 123');req((last.get('proofs')or{})==B123_PROOFS,'restart Build 123 proof set drifted');prod=pointer.get('production_checkpoint')or{};req(prod.get('build')==123 and prod.get('main_sha')==B123_SHA and prod.get('tree_sha')==B123_TREE,'Production baseline must be exact Build 123');req(prod.get('production_pages_deploy_run')==B123_PAGES and prod.get('production_live_resource_integrity_run')==B123_LIVE,'Build 123 Production proof IDs drifted')
req(prior.get('state')=='PRODUCTION_GREEN','Build 123 must be ingested as Production GREEN');closure=prior.get('final_closure')or{};req(closure.get('dev_sha')==B123_SHA and closure.get('tree_sha')==B123_TREE,'Build 123 final closure SHA/tree mismatch');req((closure.get('proofs')or{})==B123_PROOFS,'Build 123 final proof mismatch');req(closure.get('ingested_by_build')==124,'Build 123 closure must be ingested by Build 124');req('not self-recorded by Build 123' in str(closure.get('recorded_by')or''),'Build 123 non-self-recording provenance missing');pp=prior.get('production_checkpoint')or{};req(pp.get('main_sha')==B123_SHA and pp.get('tree_sha')==B123_TREE and pp.get('production_pages_deploy_run')==B123_PAGES and pp.get('production_live_resource_integrity_run')==B123_LIVE,'Build 123 Production closure mismatch')
req(current.get('state')=='DEVELOPMENT_CLOSURE_CANDIDATE','Build 124 must remain closure candidate');req(current.get('final_closure') is None and current.get('production_checkpoint') is None,'Build 124 must not self-claim later workflow proof')
for token in ("COMMERCE_POLICY_VERSION = 'R467B77_V1'","COMMERCE_COUNTRY_RESTRICTIONS_VERSION = 'R467B124_V1'","allowed_shipping_country_codes: Object.freeze(['CA'])","allowed_billing_country_codes: Object.freeze(['CA'])","blocked_sales_country_codes: Object.freeze(['US'])","blocked_shipping_country_codes: Object.freeze(['US'])","TEMPORARY_TARIFF_RESTRICTION","market_strategy: 'CANADA_FIRST'","future_market_expansion: 'REVIEW_BEFORE_ENABLE'","united_states_sales_enabled: false","united_states_shipping_enabled: false","50% tariffs","American customers","isBlockedSalesCountry","isBlockedShippingCountry","commerceCountryRestriction","billing_country_blocked","shipping_country_blocked"):req(token in core,f'Build 124 commerce core missing token: {token}')
for token in ("const HOME_PATH = path === '/'","POLICY_PRESENTATION_PATH = HOME_PATH || COMMERCE_PATH","Canada First","data.canadaFirstMarketBanner" if False else "banner.dataset.canadaFirstMarketBanner = '1'","insertAdjacentElement('beforebegin', banner)","COUNTRY_RESTRICTIONS_BUILD = 124"):req(token in runtime,f'Build 124 public runtime missing token: {token}')
req("currentPath === '/'" in bootstrap,'Build 124 bootstrap must load commerce presentation on the front page');req("import('/public/js/commerce-policy-runtime.js?v=124')" in bootstrap,'Build 124 bootstrap must cache-bust the commerce runtime');req('/public/js/commerce-policy-runtime.js?v=77' in bootstrap,'historical Build 77 bootstrap contract token must remain available')
req(len(re.findall(r'<h1(?:\s|>)',home,re.I))==1,'Home page must retain exactly one H1');req('Release 467 Build 124' in doc and 'Canada First' in doc and '50% tariffs' in doc and 'REVIEW_BEFORE_ENABLE' in doc,'Build 124 operating document incomplete')
files=[str(row.get('file')or'') for row in(manifest.get('migrations')or[]) if isinstance(row,dict)];req(files==EXPECTED,'canonical D1 migration stream must remain exactly 0001-0004');req('0005_' not in json.dumps(manifest),'Build 124 must not introduce migration 0005')
req("run_current_contract('scripts/release467_build124_gate.py','Release 467 Build 124')" in provenance,'active System Gate provenance must call Build 124');req("run_current_contract('scripts/release467_build94_gate.py', 'Release 467 Build 94')" in provenance,'historical Build 94 provenance formatting drifted')
for token in ('const BUILD=124',"TITLE='Canada-First Market Controls & U.S. Shipping Pause'",B123_SHA,B123_TREE,str(B123_PAGES),str(B123_LIVE)):req(token in it,f'I.T. projection missing Build 124/123 closure token: {token}')
req('CURRENT_RELIABILITY_BUILD=124' in reliability and B123_SHA in reliability and str(B123_PAGES) in reliability,'Reliability projection not synchronized to Build 124');req('const BUILD=124' in preflight and B123_SHA in preflight and str(B123_PAGES) in preflight,'Deployment Preflight projection not synchronized to Build 124')
for path in ('public/js/commerce-policy-core.js','public/js/commerce-policy-runtime.js','public/js/core/dd-public-module-visibility.mjs','functions/api/admin/it-operations-control-tower.js','functions/api/_lib/currentReliability.js','functions/api/admin/current-deployment-preflight.js','public/js/admin-it-control-tower.js'):command(['node','--check',str(ROOT/path)],f'JavaScript syntax {path}')
command(['node','scripts/release467_build77_commerce_policy_runtime_test.mjs'],'carried Build 77 commerce runtime proof');command(['node','scripts/release467_build124_canada_first_market_controls_test.mjs'],'Build 124 runtime/source proof')
for path,label in (('scripts/current_authority_restart_integrity_gate.py','restart integrity'),('scripts/current_it_release_truth_gate.py','I.T. truth'),('scripts/current_reliability_truth_gate.py','Reliability truth'),('scripts/current_deployment_preflight_truth_gate.py','Deployment Preflight truth')):command([sys.executable,path],label)
if FAIL:
    print('RELEASE 467 BUILD 124 GATE: FAIL');[print('-',x) for x in FAIL];sys.exit(1)
print('RELEASE 467 BUILD 124 GATE: PASS');print('Build 123 six-proof closure: INGESTED BY BUILD 124');print('Canada-first banner: ROOT PUBLIC PRESENTATION / ONE H1 PRESERVED');print('U.S. sales + shipping: EXPLICITLY BLOCKED / TEMPORARY_TARIFF_RESTRICTION');print('Other markets: REVIEW BEFORE ENABLE / NOT AUTO-OPENED');print('Canonical D1 migrations: 0001-0004 / UNCHANGED')
