#!/usr/bin/env python3
from pathlib import Path
import json,sys
R=Path(__file__).resolve().parents[1];F=[]
def t(p):return (R/p).read_text(encoding='utf-8',errors='replace')
def j(p):return json.loads(t(p))
def q(ok,msg):
    if not ok:F.append(msg)
a=j('release467-build282-content-studio-bridge-operator-acceptance.json');prev=j('release467-build281-standalone-social-project-operator-acceptance.json');b273=j('release467-build273-content-studio-standalone-project-bridge.json');p=j('current-development-authority.json')
doc=t('docs/operations/RELEASE_467_BUILD_282_CONTENT_STUDIO_BRIDGE_OPERATOR_ACCEPTANCE.md');road=t('docs/operations/RELEASE_467_CAIP_PRODUCTION_ACCEPTANCE_AUTONOMOUS_BUILDS_276_284.md');wf=t('.github/workflows/release467-build282-content-studio-bridge-operator-acceptance.yml');runtime=t('scripts/release467_build282_operator_acceptance.py');api=t('functions/api/admin/content-studio.js');helper=t('functions/api/_lib/contentAutomationStudio.js');sysgate=t('scripts/current_system_gate_provenance_gate.py')
q(a.get('build')==282 and a.get('title')=='Content Studio Bridge Operator Acceptance','Build 282 identity mismatch');q(a.get('state') in ('DEVELOPMENT_CANDIDATE','DEVELOPMENT_GREEN','PRODUCTION_GREEN'),'Build 282 state mismatch')
pred=a.get('predecessor') or {};q(pred.get('development_sha')=='259cce5ced48e1ef0fb3d88937a53105156d1b34' and pred.get('development_tree_sha')=='7987af6909f73573cbc00b2229a73155bdecc67e','Build 281 Development predecessor mismatch');q(pred.get('production_main_sha')=='707ecef36d8e6fbdcee2d15809441fafd8573ac4' and pred.get('production_tree_sha')=='7987af6909f73573cbc00b2229a73155bdecc67e' and pred.get('same_tree') is True,'Build 281 Production predecessor mismatch')
dp=pred.get('development_proofs') or {};pp=pred.get('production_proofs') or {};q(dp.get('system_gate_run')==36358854444 and dp.get('current_application_quality_run')==36358854372 and dp.get('it_admin_runtime_proof_run')==36358854423 and dp.get('branch_hygiene_run')==36358854410 and dp.get('dedicated_gate_run')==36358854448,'Build 281 Development proof mismatch');q(pp.get('production_pages_deploy_run')==36359022941 and pp.get('production_live_resource_integrity_run')==36359060883 and pp.get('products_browser_proof_run')==36359060909 and pp.get('products_route_proof_run')==36359060888 and pp.get('build_specific_proof_run')==36359023015,'Build 281 Production proof mismatch')
q(prev.get('state')=='PRODUCTION_GREEN','Build 281 successor-ingested authority must be Production GREEN');q((prev.get('final_closure') or {}).get('dev_sha')=='259cce5ced48e1ef0fb3d88937a53105156d1b34' and (prev.get('final_closure') or {}).get('tree_sha')=='7987af6909f73573cbc00b2229a73155bdecc67e','Build 281 final Development closure missing');q((prev.get('production_checkpoint') or {}).get('main_sha')=='707ecef36d8e6fbdcee2d15809441fafd8573ac4' and (prev.get('production_checkpoint') or {}).get('tree_sha')=='7987af6909f73573cbc00b2229a73155bdecc67e','Build 281 Production checkpoint missing');q(b273.get('state')=='PRODUCTION_GREEN' and (b273.get('bridge') or {}).get('exact_one_caip_workspace_required') is True,'Build 273 Content Studio bridge source authority drift')
e=a.get('evidence_contract') or {};q(e.get('environment')=='DEVELOPMENT_EXACT_SHA_LIVE_OPERATOR_ACCEPTANCE' and e.get('live_runtime_required') is True and e.get('static_source_is_live_acceptance') is False,'Build 282 runtime evidence contract drift');q(e.get('existing_non_archived_creative_process_project_required') is True and e.get('exactly_one_existing_caip_workspace_required') is True and e.get('synthetic_project_forbidden') is True,'Build 282 real source requirement drift');q(e.get('action')=='create_from_creative_project' and e.get('two_pass_idempotence_required') is True and e.get('exactly_one_content_package_required') is True and e.get('exactly_one_handoff_row_required') is True,'Build 282 idempotence contract drift');q(e.get('missing_caip_fails_closed') is True and e.get('ambiguous_caip_fails_closed') is True and e.get('existing_link_conflict_fails_closed') is True,'Build 282 fail-closed identity contract drift');q(e.get('provider_publication_invoked') is False and e.get('public_promotion_invoked') is False and e.get('production_runtime_mutation') is False,'Build 282 publication/Production separation drift')
for token in ('inspectCreativeProjectContentStudioBridge','BLOCKED_CAIP_WORKSPACE_MISSING','BLOCKED_CAIP_IDENTITY_AMBIGUOUS','BLOCKED_EXISTING_LINK_CONFLICT','READY_CREATE_PACKAGE','READY_REFRESH_PACKAGE','created_package_for_existing_identity','refreshed_existing_package','duplicate_project_created:false'):q(token in helper,f'Build 273/282 helper invariant missing: {token}')
q("action === 'create_from_creative_project'" in api and 'createOrRefreshContentProjectForCreativeProject' in api,'Content Studio operator bridge action missing');q("const bridgeBlocked=action==='create_from_creative_project'" in api and "code: bridgeBlocked?'CONTENT_STUDIO_BRIDGE_BLOCKED'" in api and "bridge_blocked: bridgeBlocked" in api,'Content Studio fail-closed POST error classification missing');get_chunk=api[api.find('export async function onRequestGet'):api.find('export async function onRequestPost')];q("bridgeBlocked=action" not in get_chunk,'GET handler must not reference POST-only action state')
for token in ('Wait for exact Development System Gate','current-development-deploy-proof','BUILD282_EXACT_DEV_BASE_URL','release467_build282_operator_acceptance.py','build282-content-studio-bridge-operator-acceptance-evidence','Production branch remains runtime-read-only for Build 282'):q(token in wf,f'Build 282 workflow missing {token}')
for token in ('exactly one non-conflicting CAIP workspace','create_from_creative_project','idempotent_content_package_count','single_handoff_row','same_content_package_reused','private_media_reference_count_unchanged','duplicate_project_created','CONTENT_STUDIO_BRIDGE_OPERATOR_ACCEPTED_REAL_EVIDENCE'):q(token in runtime,f'Build 282 runtime proof missing {token}')
for token in ('Build 282 — Content Studio Bridge Operator Acceptance','Build 283 — Planned-vs-Actual Inventory Operator Acceptance'):q(token in road,f'Roadmap missing {token}')
for token in ('existing','exactly one','create_from_creative_project','idempotence','no provider/public promotion path','build 283'):q(token in doc.lower(),f'Build 282 document missing {token}')
q("run_current_contract('scripts/release467_build282_gate.py','Release 467 Build 282')" in sysgate,'System Gate missing Build 282')
cur=int(p.get('build') or 0);q(p.get('release')==467 and cur>=282,'Current authority must retain Build 282 or successor')
if cur==282:
    q(p.get('title')=='Content Studio Bridge Operator Acceptance' and p.get('state')=='DEVELOPMENT_GREEN','Current Build 282 pointer mismatch');q(p.get('accepted_dev_sha')=='259cce5ced48e1ef0fb3d88937a53105156d1b34' and p.get('accepted_dev_tree_sha')=='7987af6909f73573cbc00b2229a73155bdecc67e','Current Build 282 accepted predecessor mismatch');q((p.get('production_checkpoint') or {}).get('main_sha')=='707ecef36d8e6fbdcee2d15809441fafd8573ac4' and (p.get('production_checkpoint') or {}).get('tree_sha')=='7987af6909f73573cbc00b2229a73155bdecc67e','Current Build 282 Production predecessor mismatch');q(int(p.get('next_build') or 0)==283 and p.get('next_build_title')=='Planned-vs-Actual Inventory Operator Acceptance','Current Build 282 successor pointer mismatch')
proj=p.get('caip_content_studio_bridge_operator_acceptance') or {};q(proj.get('action')=='create_from_creative_project' and proj.get('exactly_one_existing_caip_workspace_required') is True and proj.get('duplicate_project_created') is False and proj.get('provider_publication') is False and proj.get('public_promotion') is False,'Current Build 282 projection mismatch')
s=a.get('safety') or {}
for k in ('schema_change','request_time_schema_mutation','production_d1_business_data_mutation','production_r2_mutation','creative_process_project_creation','caip_project_creation','product_creation','fake_product_creation','private_media_upload','private_media_delete','uncertain_r2_delete','public_media_copy','provider_execution','provider_publication','public_promotion','product_publication','inventory_movement','finance_posting','payment_or_refund','production_business_data_copy','secret_capture','raw_operator_identity_capture','synthetic_acceptance','exact_sha_requirement_relaxed','named_proof_requirement_relaxed'):q(s.get(k) is False,f'Build 282 safety drift: {k}')
q(s.get('development_content_package_create_or_refresh') is True,'Build 282 bounded Development Content Studio mutation must be explicit')
print('RELEASE 467 BUILD 282 CONTENT STUDIO BRIDGE OPERATOR ACCEPTANCE')
if F:
    print('FAIL');[print('-',x) for x in F];sys.exit(1)
print('PASS');print('Runtime GREEN target: one real Creative Process identity + one existing CAIP workspace -> one idempotent Content Studio package.');print('Next: Build 283 — Planned-vs-Actual Inventory Operator Acceptance')
