import fs from 'node:fs';
const [input,sha,out]=process.argv.slice(2);const raw=JSON.parse(fs.readFileSync(input,'utf8'));const sets=Array.isArray(raw)?raw:(raw.results||[]);
if(sets.length!==4)throw new Error('Unexpected Build 351 statement count '+sets.length);
const reads=sets.map(x=>Number(x?.meta?.rows_read||0)),aggregate=reads.reduce((a,b)=>a+b,0);if(aggregate>20000)throw new Error('Rows-read ceiling exceeded '+aggregate);
const target=(sets[0]?.results||[])[0]||{},evidence=sets[1]?.results||[],plans=sets[2]?.results||[],integrity=(sets[3]?.results||[])[0]||{};
if(Number(target.creative_work_project_id||0)!==6||String(target.project_key)!=='CP-MSUNAL8R'||String(target.project_title)!=='Grey Hair')throw new Error('Grey Hair identity drift');
for(const [k,v] of Object.entries({exact_work_identity:1,caip_workspaces:1,content_packages:1,foreign_key_violations:0}))if(Number(integrity[k]||0)!==v)throw new Error('Build 351 integrity '+k+'='+integrity[k]);
if(Number(target.active_source_evidence||0)!==evidence.length)throw new Error('Active evidence count/list drift');
const needs=Number(target.source_evidence_needs_review||0),approved=Number(target.approved_source_evidence||0),groups=Number(target.confirmed_capture_groups||0),tracks=Number(target.confirmed_capture_tracks||0),reviewed=Number(target.reviewed_story_plans||0),items=Number(target.source_backed_story_items||0),profiles=Number(target.maker_story_profiles||0);
const evidenceComplete=needs===0,sourceThreshold=approved>=2,syncReady=groups>=1&&tracks>=4,storyPlanReady=reviewed>=1&&items>=2,handoffReady=evidenceComplete&&sourceThreshold&&syncReady&&storyPlanReady;
let state='SOURCE_EVIDENCE_REVIEW_REQUIRED';
if(evidenceComplete&&!sourceThreshold)state='APPROVED_SOURCE_EVIDENCE_INSUFFICIENT';else if(evidenceComplete&&sourceThreshold&&!syncReady)state='STORY_PLANNING_PREREQUISITE_SYNC_REQUIRED';else if(evidenceComplete&&sourceThreshold&&syncReady&&reviewed<1)state='HUMAN_REVIEWED_STORY_PLAN_REQUIRED';else if(evidenceComplete&&sourceThreshold&&syncReady&&reviewed>=1&&items<2)state='SOURCE_BACKED_STORY_ITEMS_REQUIRED';else if(handoffReady)state='GREY_HAIR_REVIEWED_EVIDENCE_READY_PENDING_MAKER_STORY_DECISION';
const baseline={active_source_evidence:3,approved_source_evidence:1,source_evidence_needs_review:2,confirmed_capture_groups:0,confirmed_capture_tracks:0,reviewed_story_plans:0,source_backed_story_items:0,maker_story_profiles:0};
const comparison={active_source_evidence_delta:Number(target.active_source_evidence||0)-baseline.active_source_evidence,approved_source_evidence_delta:approved-baseline.approved_source_evidence,source_evidence_needs_review_delta:needs-baseline.source_evidence_needs_review,confirmed_capture_groups_delta:groups,confirmed_capture_tracks_delta:tracks,reviewed_story_plans_delta:reviewed,source_backed_story_items_delta:items,maker_story_profiles_delta:profiles};
const evidenceOut={release:467,build:351,exact_development_sha:sha,statement_count:4,rows_read_by_statement:reads,aggregate_rows_read:aggregate,rows_read_ceiling:20000,target,evidence_rows:evidence,story_plans:plans,handoff_state:state,comparison_to_build349:comparison,
completion:{evidence_review_complete:evidenceComplete,approved_source_threshold_met:sourceThreshold,sync_prerequisite_met:syncReady,story_plan_handoff_ready:storyPlanReady,handoff_ready:handoffReady,source_evidence_needs_review:needs,approved_source_evidence:approved,confirmed_capture_groups:groups,confirmed_capture_tracks:tracks,reviewed_story_plans:reviewed,source_backed_story_items:items,maker_story_profiles:profiles},
boundaries:{read_only:true,evidence_approval_mutation:false,sync_mutation:false,story_plan_generation:false,story_plan_review_mutation:false,maker_story_profile_mutation:false,automatic_publication:false,private_media_promoted:false,media_rights_inference:false,provider_execution:false,production_d1_contact:false},integrity};
fs.writeFileSync(out,JSON.stringify(evidenceOut,null,2)+'\n');
console.log('BUILD351_HANDOFF_STATE=',state);console.log('BUILD351_TARGET=',JSON.stringify(target));console.log('BUILD351_COMPLETION=',JSON.stringify(evidenceOut.completion));console.log('BUILD351_DELTA_VS_BUILD349=',JSON.stringify(comparison));console.log('BUILD351_EVIDENCE_ROWS=',JSON.stringify(evidence));console.log('BUILD351_STORY_PLANS=',JSON.stringify(plans));console.log('BUILD351_ROWS_READ=',JSON.stringify(reads));console.log('BUILD351_AGGREGATE_ROWS_READ=',aggregate);console.log('BUILD351_GREY_HAIR_CONTINUITY_V=GREEN');