#!/usr/bin/env python3
"""Fail-closed source contract for Release 466 Build 3 — Revenue & Business Intelligence."""
from __future__ import annotations
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];FAIL=[]
def req(ok,msg):
 if not ok:FAIL.append(msg)
def read(path):
 p=ROOT/path
 if not p.is_file():FAIL.append(f'missing required file: {path}');return''
 return p.read_text(encoding='utf-8',errors='replace')
def has(body,*tokens,label='file'):
 for token in tokens:req(token in body,f'{label} missing required contract: {token}')
a=json.loads(read('release466-build3-revenue-business-intelligence.json') or '{}');state=a.get('state');req(a.get('release')==466 and a.get('build')==3,'authority must identify Release 466 Build 3');req(state in {'implementation_in_progress','development_green'},'unexpected Build 3 state');req(a.get('schema_change_required') is False and a.get('migration') is None,'Build 3 must remain schema-neutral');items={int(x.get('id') or 0):x for x in a.get('items',[]) if isinstance(x,dict)};req(set(items)=={11,12,13,14,15},'Build 3 must own exactly items 11-15');req(all(items[i].get('status') in {'implementation_in_progress','development_green','complete_development_green'} for i in items),'Build 3 item lifecycle drifted')
for key in ('production_business_mutation','production_schema_mutation','provider_execution','provider_publication','payment_execution','inventory_mutation','accounting_posting','automatic_price_change','automatic_reorder','automatic_project_start','raw_r2_delete','request_time_schema_ddl'):req((a.get('safety') or {}).get(key) is False,f'safety flag must remain false: {key}')
req((a.get('safety') or {}).get('preview_access_must_remain_enforced') is True,'Preview Access must remain enforced');req((a.get('safety') or {}).get('main_must_remain_release465_until_deliberate_promotion') is True,'main must remain Release 465')
api=read('functions/api/admin/release466-revenue-business-intelligence.js');alias=read('functions/api/admin/release-revenue-business-intelligence.js');page=read('admin/release-control/revenue-business-intelligence/index.html');client=read('public/js/admin-release466-revenue-business-intelligence.js')
has(api,'loadFunnel','loadSearchIntelligence','loadProductOpportunity','loadReorderEconomics','loadCreativePriority','loadProfitabilityIntelligence','site_search_events','inventory_supply_replenishment_profiles','inventory_supply_source_options','creative_project_profitability','recommendation only','automatic_reorder:false','automatic_project_start:false',label='Build 3 API');req('export async function onRequestGet' in api,'Build 3 API must expose GET');req(not re.search(r'\b(?:INSERT|UPDATE|DELETE|CREATE|ALTER|DROP|REPLACE)\b',api,re.I),'Build 3 API must remain SQL read-only');req('onRequestPost' not in api and 'onRequestPut' not in api and 'onRequestDelete' not in api,'Build 3 API must remain GET-only');req("export { onRequestGet }" in alias,'release-route alias must export GET only')
req(page.lower().count('<h1')==1,'Build 3 cockpit must have exactly one H1');has(page,'Revenue &amp; Business Intelligence','recommendation-only','/admin/business-health/','/admin/inventory-creator-intelligence/',label='Build 3 cockpit');has(client,'/api/admin/release-revenue-business-intelligence','Storefront conversion funnel','Search demand and abandonment','Explainable Product opportunity','Inventory reorder economics','Creative project priority',label='Build 3 client')
manifest=json.loads(read('migrations/canonical/manifest.json') or '{}');req([x.get('file') for x in manifest.get('migrations',[])]==['0001_release464_migration_authority.sql','0002_release464_operational_acceptance.sql','0003_release464_business_growth.sql','0004_release465_storefront_quality.sql'],'Build 3 must preserve exact canonical migrations 0001-0004');req(not list((ROOT/'migrations/canonical').glob('*466*build3*')),'Build 3 declared schema-neutral but a Build 3 migration exists')
release=json.loads(read('development-release.json') or '{}');db=release.get('current_release_database_state') or {};req(db.get('build3_schema_change_required') is False and db.get('release466_build3_schema_change_required') is False,'development-release must keep Build 3 schema-neutral')
if state=='implementation_in_progress':
 req(release.get('convergence_state')=='release466_build2_development_green_external_ruleset_pending','Build 3 implementation must start from closed Build 2 Development authority')
else:
 req(release.get('convergence_state')=='release466_build3_development_green_external_ruleset_pending','Build 3 closure convergence state drifted')
 req(all(items[i].get('status')=='development_green' for i in items),'closed Build 3 authority must mark items 11-15 Development green')
 ev=a.get('technical_green_evidence') or {};req(a.get('technical_green_source_sha')=='5ca09eab9e2a3441ffbdf76c46e35b3a6fcd52a6','Build 3 technical-green SHA drifted');req(int(ev.get('system_gate_run') or 0)==33466655732 and int(ev.get('system_gate_source_job') or 0)==99727807616 and int(ev.get('system_gate_deploy_job') or 0)==99727877699,'Build 3 System Gate evidence drifted');req(ev.get('exact_preview')=='https://732f6430.devilndove-site.pages.dev','Build 3 exact Preview evidence drifted');req(int(ev.get('build3_proof_run') or 0)==33466655735 and int(ev.get('build3_source_proof_job') or 0)==99727807035 and int(ev.get('build3_runtime_proof_job') or 0)==99727862065,'Build 3 proof job evidence drifted');req(int(ev.get('build3_proof_artifact_id') or 0)==9785121048 and ev.get('build3_proof_artifact_sha256')=='92af7c472900d89cf4d9a01a44d4abc5ba4a10ef698de2cac7df44011b525b56','Build 3 proof artifact evidence drifted');req(int(ev.get('required_development_authority_tables') or 0)==11 and int(ev.get('observed_page_view_rows') or 0)==33 and int(ev.get('observed_product_rows') or 0)==45 and int(ev.get('observed_inventory_rows') or 0)==1041 and int(ev.get('observed_creative_project_rows') or 0)==5,'Build 3 Development authority evidence drifted');req(ev.get('production_business_rows_read') is False and ev.get('production_mutation') is False,'Build 3 Production read/mutation boundary drifted')
 release_items={int(x.get('id') or 0):x for x in release.get('release466_build3',[]) if isinstance(x,dict)};req(set(release_items)=={11,12,13,14,15} and all(release_items[i].get('status')=='complete_development_green' for i in release_items),'development-release must mark Build 3 items complete Development green');planned={int(x.get('build') or 0):x for x in release.get('planned_builds',[])};req(set(planned)=={4} and planned[4].get('items')==[16,17,18,19,20] and planned[4].get('state')=='next','Build 4 must be the next bounded work after Build 3 closure');roadmap=read('docs/operations/RELEASE_466_FOUR_BUILD_ROADMAP.md');handoff=read('AI_HANDOFF.md');project=read('PROJECT_STATUS_AND_ROADMAP.md');sanity=read('SANITY_HEALTH_CHECK.md');has(roadmap,'Build 3 — Revenue & Business Intelligence — DEVELOPMENT GREEN','Build 4 — External Acceptance & Commercial Readiness — NEXT',label='Release 466 roadmap closure');has(handoff,'Build 3 is Development green','Release 466 Build 4 — External Acceptance & Commercial Readiness',label='AI handoff closure');has(project,'Build 3 | 11–15 | Revenue & Business Intelligence | Development green','Build 4 | 16–20 | External Acceptance & Commercial Readiness | Next',label='project roadmap closure');has(sanity,'Release 466 Build 3 is technically **Development GREEN**','Release 466 Build 4 — External Acceptance & Commercial Readiness',label='sanity closure')
print('RELEASE 466 BUILD 3 SOURCE CONTRACT');print('Items: 11 funnel; 12 search abandonment; 13 Product opportunity; 14 reorder economics; 15 Creative priority');print('Schema change: NONE');print('Automatic business action: ZERO');print('Production mutation/provider/payment execution: ZERO')
if FAIL:
 print('RELEASE 466 BUILD 3 SOURCE CONTRACT: FAIL');[print(f'{i:03d}. {m}') for i,m in enumerate(FAIL,1)];raise SystemExit(1)
print('RELEASE 466 BUILD 3 SOURCE CONTRACT: PASS')
