#!/usr/bin/env python3
from pathlib import Path
import json,re,sys
R=Path(__file__).resolve().parents[1];F=[]
def t(p):return (R/p).read_text(encoding='utf-8',errors='replace')
def j(p):return json.loads(t(p))
def q(ok,msg):
    if not ok:F.append(msg)
a=j('release467-build341-maker-story-advancement-publication-readiness-continuity-iv.json')
prev=j('release467-build340-search-console-real-export-fresh-discovery-intake-v.json')
p=j('current-development-authority.json')
sql=t('scripts/release467_build341_continuity.sql')
verify=t('scripts/release467_build341_verify_continuity.mjs')
wf=t('.github/workflows/release467-build341-maker-story-advancement-publication-readiness-continuity-iv.yml')
api=t('functions/api/admin/maker-story-coverage.js')
page=t('admin/maker-story-coverage/index.html')
ui=t('public/js/admin-maker-story-coverage-v329.js')
road=t('docs/operations/RELEASE_467_EVIDENCE_EXECUTION_DISCOVERY_BUILDS_337_342.md')
q(a.get('build')==341 and a.get('title')=='Maker Story Advancement & Publication Readiness Continuity IV','Build 341 identity mismatch')
q(prev.get('state')=='PRODUCTION_GREEN','Build 340 Production closure not successor-ingested')
q((prev.get('final_closure') or {}).get('dev_sha')=='5e2c1d53ce8f96c29c526f78378a73f9c451c956' and (prev.get('final_closure') or {}).get('tree_sha')=='dfa4b627095b7f5c7fb4777bb6c38c1d0309b629','Build 340 exact Development closure missing')
q((prev.get('production_checkpoint') or {}).get('main_sha')=='104034bea4060c1696708cec8e145c7398525889' and (prev.get('production_checkpoint') or {}).get('tree_sha')=='dfa4b627095b7f5c7fb4777bb6c38c1d0309b629','Build 340 Production checkpoint missing')
c=a.get('contract') or {};s=a.get('safety') or {}
q(c.get('reuses_build329_maker_story_authorities') is True and c.get('reuses_build335_measurement_model') is True,'Build 341 retained Maker Story authority mismatch')
q(c.get('expected_active_projects')==5 and c.get('coverage_population')=='ALL_ACTIVE_CREATIVE_PROJECTS','Build 341 five-project coverage contract mismatch')
q(c.get('substantive_non_placeholder_result_and_lesson_required') is True and c.get('promo35_real_execution_result_lesson_events_required') is True,'Build 341 factual evidence guard mismatch')
q(c.get('explicit_story_review_required') is True and c.get('public_story_candidate_required') is True and c.get('approved_content_copy_required') is True and c.get('locked_content_copy_required') is True,'Build 341 review/copy readiness contract mismatch')
q(c.get('public_media_rights_separate_from_story_text_readiness') is True and c.get('private_media_never_public_by_inference') is True and c.get('provider_posting_independent') is True,'Build 341 rights/provider boundary mismatch')
q(c.get('next_build')==342 and c.get('next_build_title')=='Content Adoption & Discovery Outcomes Renewal VII','Build 342 successor mismatch')
q(all(v is False for v in s.values()),'Build 341 safety authority drift')
upper=' '+re.sub(r'--.*','',sql).upper()+' '
for forbidden in (' INSERT ',' UPDATE ',' DELETE ',' CREATE ',' ALTER ',' DROP ',' REPLACE ',' VACUUM ',' REINDEX '):q(forbidden not in upper,'Build 341 measurement must remain read-only: '+forbidden.strip())
for token in ('what_we_are_trying','actual_result','lesson_learned','execution_events','result_events','lesson_events','source_evidence_needs_review','human_published_journal_rows','provider_posted_rows','pragma_foreign_key_check'):q(token in sql,'Build 341 SQL missing '+token)
for token in ('placeholderGuard','substantiveFact','PUBLISHED_REVIEWED_STORY','FACTUAL_OUTCOME_EVIDENCE_REQUIRED','PUBLICATION_REVIEW_READY','promo35_real_execution_result_lesson_events_required:true','publication_mutation:false','production_d1_contact:false'):q(token in verify,'Build 341 verifier missing '+token)
for token in ('placeholderGuard','substantiveFact','build:BUILD','substantive_non_placeholder_result_and_lesson_required:true','publication_readiness_is_read_only_classification:true','public_media_rights_separate:true','automatic_publication:false','provider_execution:false'):q(token in api,'Build 341 reused API missing '+token)
q('onRequestPost' not in api,'Maker Story coverage API must remain GET-only')
for token in ('makerStoryCoverageBuild329Mount','admin-maker-story-coverage-v329.js'):q(token in page,'Existing Maker Story coverage workspace must remain the reused authority')
for token in ('Placeholder absence text never counts','Media rights — separate','never auto-creates a Maker Story','provider posting remains independent'):q(token in ui,'Reused Maker Story UI boundary missing '+token)
for token in ('D1_ONE_SHOT_EVIDENCE_CAPTURE','FIVE ACTIVE PROJECTS: READ-ONLY ADVANCEMENT','SUBSTANTIVE RESULT/LESSON FACTS: REQUIRED','HUMAN STORY REVIEW: REQUIRED','MEDIA RIGHTS: SEPARATE NEVER INFERRED','AUTOMATIC PUBLICATION: ZERO','PROVIDER EXECUTION: ZERO','PRODUCTION D1 CONTACT: ZERO'):q(token in wf,'Build 341 workflow boundary missing '+token)
q('Build 342 — Content Adoption & Discovery Outcomes Renewal VII' in road,'Build 342 successor roadmap missing')
q(int(p.get('build') or 0)>=341,'Current pointer must retain Build 341 or successor')
if int(p.get('build') or 0)==341:q(int(p.get('next_build') or 0)==342,'Build 342 successor pointer missing')
print('RELEASE 467 BUILD 341 MAKER STORY ADVANCEMENT & PUBLICATION READINESS CONTINUITY IV')
if F:
 print('FAIL');[print('-',x) for x in F];sys.exit(1)
print('PASS');print('Readiness remains factual, human-reviewed, rights-separated and mutation-free')
