import fs from 'node:fs';
const [input,sha,out]=process.argv.slice(2);
const raw=JSON.parse(fs.readFileSync(input,'utf8'));
const sets=Array.isArray(raw)?raw:(raw.results||[]);
if(sets.length!==3)throw new Error('Unexpected statement count '+sets.length);
const reads=sets.map(x=>Number(x?.meta?.rows_read||0));
const aggregate=reads.reduce((a,b)=>a+b,0);
if(aggregate>20000)throw new Error('Rows-read ceiling exceeded '+aggregate);
const second=(sets[0]?.results||[])[0]||{};
const first=(sets[1]?.results||[])[0]||{};
const integrity=(sets[2]?.results||[])[0]||{};
if(Number(second.content_project_id||0)!==23||String(second.content_project_key)!=='creative-project-5-35th-promo'||String(second.source_type)!=='creative_project'||String(second.source_id)!=='5')throw new Error('Second-story Content Studio identity drift');
for(const [k,v] of Object.entries({content_packages:1,deliverables:19,approved_deliverables:2,changes_requested_deliverables:17,locked_deliverables:2,selected_evidence:1,publications:0,social_rows:0,caip_assets:0,private_upload_files:0,public_event_candidates:0}))if(Number(second[k]||0)!==v)throw new Error('Second-story continuity '+k+'='+second[k]);
if(String(second.story_review_status)!=='needs_review'||Number(second.public_story_candidate||0)!==0||String(second.outcome_status)!=='unknown')throw new Error('Second-story publication prerequisite unexpectedly satisfied or drifted');
for(const [k,v] of Object.entries({workshop_journal_rows:1,published_journal_rows:1,social_rows:1,approved_review_first_social_rows:1,posted_social_rows:0}))if(Number(first[k]||0)!==v)throw new Error('First-story continuity '+k+'='+first[k]);
if(String(first.social_image_urls_json||'')!=='[]'||String(first.social_video_url||'')!=='')throw new Error('First-story review-first queue crossed media boundary');
for(const [k,v] of Object.entries({second_story_website_gallery_rows:0,duplicate_content_source_identities:0,foreign_key_violations:0}))if(Number(integrity[k]||0)!==v)throw new Error('Build 310 integrity drift '+k+'='+integrity[k]);
const evidence={release:467,build:310,exact_development_sha:sha,statement_count:3,rows_read_by_statement:reads,aggregate_rows_read:aggregate,rows_read_ceiling:20000,second_story:second,first_story_continuity:first,integrity,second_story_publication_action:'BLOCKED_UNTIL_EXPLICIT_MAKER_STORY_REVIEW',development_d1_mutation:false,provider_execution:false,indexnow_execution:false,marketplace_execution:false,production_d1_contact:false};
fs.writeFileSync(out,JSON.stringify(evidence,null,2)+'\n');
console.log('BUILD310_SECOND_STORY=',JSON.stringify(second));
console.log('BUILD310_FIRST_STORY_CONTINUITY=',JSON.stringify(first));
console.log('BUILD310_INTEGRITY=',JSON.stringify(integrity));
console.log('BUILD310_ROWS_READ=',JSON.stringify(reads));
console.log('BUILD310_AGGREGATE_ROWS_READ=',aggregate);
console.log('BUILD310_REVIEW_FIRST_PUBLICATION_CONTINUITY=GREEN');
