import fs from 'node:fs';
const [input,sha,output]=process.argv.slice(2);
const raw=JSON.parse(fs.readFileSync(input,'utf8'));const sets=Array.isArray(raw)?raw:(raw.results||[]);
if(sets.length!==6)throw new Error('Unexpected statement count '+sets.length);
const reads=sets.map(x=>Number(x?.meta?.rows_read||0)),aggregate=reads.reduce((a,b)=>a+b,0);
if(aggregate>20000)throw new Error('Rows-read ceiling exceeded '+aggregate);
const project=(sets[0]?.results||[])[0]||{},evidence=sets[1]?.results||[],packages=sets[2]?.results||[],deliverables=sets[3]?.results||[],counts=(sets[4]?.results||[])[0]||{},boundary=(sets[5]?.results||[])[0]||{};
if(Number(project.creative_work_project_id)!==7||project.project_key!=='CP-MSXCYQB6'||project.project_title!=='Under the Sea')throw new Error('Project identity drift');
if(project.story_kind!=='maker_story'||project.story_review_status!=='needs_review'||Number(project.public_story_candidate)!==0)throw new Error('Maker Story review-first state drift');
if(Number(project.selected_evidence)!==3||evidence.length!==3)throw new Error('Expected exactly three selected factual evidence rows');
if(evidence.some(x=>Number(x.is_public_candidate||0)!==0||String(x.media_url||'')!==''))throw new Error('Selected evidence crossed public/media boundary');
if(Number(project.caip_workspaces)!==1||Number(project.content_packages)!==1||packages.length!==1)throw new Error('One-to-one package identity drift');
if(String(packages[0].source_type)!=='creative_project'||String(packages[0].source_id)!=='7')throw new Error('Content package source identity drift');
if(deliverables.length<1)throw new Error('No Content Studio drafts found');
if(new Set(deliverables.map(x=>String(x.deliverable_key))).size!==deliverables.length)throw new Error('Duplicate deliverable keys found');
if(deliverables.some(x=>String(x.generated_by||'')!=='factual_template'))throw new Error('Build 303 only reviews factual-template drafts');
if(Number(counts.content_packages)!==1||Number(counts.duplicate_content_source_identities)!==0)throw new Error('Content package duplication');
if(Number(counts.deliverables)!==deliverables.length||Number(counts.factual_template_deliverables)!==deliverables.length)throw new Error('Deliverable aggregate mismatch');
if(Number(counts.approved_deliverables||0)!==0||deliverables.some(x=>String(x.approval_status||'')==='approved'))throw new Error('Discovery expected zero pre-approved drafts');
if(Number(boundary.caip_assets||0)!==0||Number(boundary.private_upload_files||0)!==0)throw new Error('Fail closed: CAIP media appeared before draft review');
if(Number(boundary.publications||0)!==0||Number(boundary.social_rows_total||0)!==0||Number(boundary.foreign_key_violations||0)!==0)throw new Error('Build 304/publication or integrity boundary crossed');
console.log('BUILD303_ROWS_READ=',JSON.stringify(reads));console.log('BUILD303_AGGREGATE_ROWS_READ=',aggregate);
console.log('BUILD303_PROJECT=',JSON.stringify(project));console.log('BUILD303_EVIDENCE=',JSON.stringify(evidence));
console.log('BUILD303_PACKAGE=',JSON.stringify(packages));console.log('BUILD303_COUNTS=',JSON.stringify(counts));
console.log('BUILD303_BOUNDARY=',JSON.stringify(boundary));console.log('BUILD303_DELIVERABLES=',JSON.stringify(deliverables));
console.log('BUILD303_DRAFT_REVIEW_DISCOVERY=GREEN');
fs.writeFileSync(output,JSON.stringify({release:467,build:303,exact_development_sha:sha,reads,aggregate_rows_read:aggregate,project,evidence,packages,deliverables,counts,boundary,mutation:false,refresh:false,approval:false,publication:false,production_d1_contact:false},null,2)+'\n');
