import fs from 'node:fs';
const [input,sha,output]=process.argv.slice(2);
const raw=JSON.parse(fs.readFileSync(input,'utf8'));const sets=Array.isArray(raw)?raw:(raw.results||[]);
if(sets.length!==6)throw new Error('Unexpected statement count '+sets.length);
const reads=sets.map(x=>Number(x?.meta?.rows_read||0)),aggregate=reads.reduce((a,b)=>a+b,0);
if(aggregate>20000)throw new Error('Rows-read ceiling exceeded '+aggregate);
const pre=(sets[0]?.results||[])[0]||{},pub=(sets[2]?.results||[])[0]||{},social=(sets[4]?.results||[])[0]||{},post=(sets[5]?.results||[])[0]||{};
if(Number(pre.content_project_id)!==22||pre.content_project_key!=='creative-project-7-under-the-sea'||pre.source_type!=='creative_project'||String(pre.source_id)!=='7')throw new Error('Content package identity drift');
for(const [k,v] of Object.entries({content_packages:1,deliverables:19,approved_deliverables:2,changes_requested_deliverables:17,approved_blog:1,selected_evidence:3,caip_assets:0,private_upload_files:0}))if(Number(pre[k]||0)!==v)throw new Error('Prerequisite '+k+'='+pre[k]);
if(pub.publication_key!=='content-project-22-workshop_journal'||pub.destination!=='workshop_journal'||pub.content_status!=='published')throw new Error('Workshop Journal publication state mismatch');
if(String(pub.hero_media_url||'')!==''||String(pub.media_urls_json||'')!=='[]')throw new Error('Text-only Journal unexpectedly contains media');
if(Number(pub.copy_locked)!==1||Number(pub.approved_by_user_id)<=0||Number(pub.published_by_user_id)<=0||!String(pub.published_at||''))throw new Error('Explicit Journal approval/publication audit missing');
if(!String(pub.review_notes||'').includes('No public media exists or is inferred'))throw new Error('Journal privacy note missing');
if(social.social_post_key!=='workshop-journal-22-under-the-sea'||social.source_type!=='workshop_journal')throw new Error('Social source identity mismatch');
if(social.approval_status!=='approved'||social.post_status!=='ready'||social.api_publish_mode!=='review_first')throw new Error('Social review-first state mismatch');
if(String(social.image_urls_json||'')!=='[]'||String(social.video_url||'')!==''||String(social.published_at||'')!=='')throw new Error('Social queue crossed media/provider boundary');
if(!String(social.link_url||'').includes('/workshop-journal/story/?story=under-the-sea-workshop-story-22'))throw new Error('Social link mismatch');
for(const [k,v] of Object.entries({content_packages:1,workshop_journal_rows:1,published_journal_rows:1,website_gallery_rows:0,social_rows:1,approved_review_first_social_rows:1,posted_social_rows:0,caip_assets:0,private_upload_files:0,foreign_key_violations:0}))if(Number(post[k]||0)!==v)throw new Error('Post-acceptance '+k+'='+post[k]);
console.log('BUILD304_ACCEPTANCE_ROWS_READ=',JSON.stringify(reads));
console.log('BUILD304_ACCEPTANCE_AGGREGATE_ROWS_READ=',aggregate);
console.log('BUILD304_JOURNAL=',JSON.stringify(pub));
console.log('BUILD304_SOCIAL=',JSON.stringify(social));
console.log('BUILD304_REVIEW_FIRST_PUBLICATION_ACCEPTANCE=GREEN');
fs.writeFileSync(output,JSON.stringify({release:467,build:304,exact_development_sha:sha,reads,aggregate_rows_read:aggregate,journal:pub,social,post,production_d1_contact:false,provider_execution:false,provider_publication:false,r2_mutation:false},null,2)+'\n');
