#!/usr/bin/env python3
"""Release 467 Build 119 — Business Health Escalation Decision Brief & Owner Priority Matrix gate."""
from pathlib import Path
import json,re,subprocess,sys
ROOT=Path(__file__).resolve().parents[1];FAIL=[]
B118_SHA='df0953198882e82ca3d7742b614d92528d45dbe3';B118_TREE='9c2d8abd7da4a5f1e41c00bdc001cd844458d9ea'
B118_PROOFS={'system_gate_run':34703983097,'current_application_quality_run':34703983106,'it_admin_runtime_proof_run':34703983092,'branch_hygiene_run':34703983073};B118_PAGES=34704076896;B118_LIVE=34704126081
EXPECTED=['0001_release464_migration_authority.sql','0002_release464_operational_acceptance.sql','0003_release464_business_growth.sql','0004_release465_storefront_quality.sql']
def req(ok,msg):
    if not ok: FAIL.append(msg)
def read(path): return (ROOT/path).read_text(encoding='utf-8',errors='replace')
def load(path): return json.loads(read(path))
def command(args,label):
    r=subprocess.run(args,cwd=ROOT,text=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=False)
    if r.stdout.strip(): print(r.stdout.strip())
    if r.returncode!=0: FAIL.append(f"{label} failed: {(r.stderr or r.stdout).strip()[-3000:]}")
pointer=load('current-development-authority.json');prior=load('release467-build118-business-health-rolling-trend.json');current=load('release467-build119-business-health-decision-brief.json');manifest=load('migrations/canonical/manifest.json')
helper=read('functions/api/_lib/businessHealthDecisionBrief.js');endpoint=read('functions/api/admin/business-health-decision-brief.js');client=read('public/js/admin-business-health-decision-brief-v119.js');page=read('admin/business-health/index.html');provenance=read('scripts/current_system_gate_provenance_gate.py')
req(pointer.get('release')==467 and pointer.get('build')==119,'current pointer must identify Release 467 Build 119');req(pointer.get('title')=='Business Health Escalation Decision Brief & Owner Priority Matrix','Build 119 title drifted');req(pointer.get('state')=='DEVELOPMENT_GREEN','candidate pointer must retain inherited Development GREEN state');req(pointer.get('accepted_dev_sha')==B118_SHA and pointer.get('accepted_dev_tree_sha')==B118_TREE,'Build 119 accepted baseline must be exact Build 118');req((pointer.get('acceptance')or{})==B118_PROOFS,'Build 119 inherited four-proof baseline mismatch')
last=(pointer.get('restart_integrity')or{}).get('last_fully_verified')or{};req(last.get('build')==118 and last.get('dev_sha')==B118_SHA and last.get('tree_sha')==B118_TREE,'restart integrity must identify exact Build 118');req((last.get('proofs')or{})==B118_PROOFS,'restart Build 118 proof set drifted');prod=pointer.get('production_checkpoint')or{};req(prod.get('build')==118 and prod.get('main_sha')==B118_SHA and prod.get('tree_sha')==B118_TREE,'Production baseline must be exact Build 118');req(prod.get('production_pages_deploy_run')==B118_PAGES and prod.get('production_live_resource_integrity_run')==B118_LIVE,'Build 118 Production proof IDs drifted')
req(prior.get('state')=='PRODUCTION_GREEN','Build 118 must be ingested as Production GREEN');closure=prior.get('final_closure')or{};req(closure.get('dev_sha')==B118_SHA and closure.get('tree_sha')==B118_TREE,'Build 118 final closure SHA/tree mismatch');req((closure.get('proofs')or{})==B118_PROOFS,'Build 118 final proof mismatch');req(closure.get('ingested_by_build')==119,'Build 118 closure must be ingested by Build 119');req('not self-recorded by Build 118' in str(closure.get('recorded_by')or''),'Build 118 non-self-recording provenance missing');pp=prior.get('production_checkpoint')or{};req(pp.get('main_sha')==B118_SHA and pp.get('tree_sha')==B118_TREE and pp.get('production_pages_deploy_run')==B118_PAGES and pp.get('production_live_resource_integrity_run')==B118_LIVE,'Build 118 Production closure mismatch')
req(current.get('state')=='DEVELOPMENT_CLOSURE_CANDIDATE','Build 119 must remain closure candidate');req(current.get('final_closure') is None and current.get('production_checkpoint') is None,'Build 119 must not self-claim later workflow proof');start=(current.get('starting_point')or{}).get('development')or{};req(start.get('sha')==B118_SHA and start.get('tree')==B118_TREE,'Build 119 starting Development identity mismatch')
for token in ('BUSINESS_HEALTH_DECISION_BRIEF_BUILD=119','existing_action_queue_authoritative:true','second_action_queue_created:false','human_decision_only:true','decision_persistence:false','approval_persistence:false','trend_scope','priority_review','blocking_review',"mutation_capability:'none'",'accounting_posting:false','inventory_mutation:false','provider_execution:false'):req(token in helper,f'Build 119 helper missing token: {token}')
for forbidden in (r'\bfetch\s*\(',r'\bdb\.',r'\blocalStorage\.',r'\bsessionStorage\.',r'\bsetInterval\s*\('):req(not re.search(forbidden,helper),f'Build 119 pure helper gained forbidden behavior: {forbidden}')
for token in ('loadRelease465BusinessHealth','buildBusinessHealthDecisionBrief',"role:'read_only_business_health_decision_brief'","format==='markdown'",'decision_persistence:false','approval_persistence:false','acknowledgement_persistence:false','resolution_persistence:false'):req(token in endpoint,f'Build 119 endpoint missing token: {token}')
req('onRequestPost' not in endpoint,'Build 119 endpoint must expose no POST handler')
for forbidden in ('UPDATE ','INSERT ','DELETE ','CREATE TABLE','ALTER TABLE','DROP TABLE'):req(forbidden not in endpoint.upper(),f'Build 119 endpoint contains forbidden DML/DDL: {forbidden}')
for token in ('b119DecisionBrief','b119Export','data-business-health-decision-brief-build="119"','admin-business-health-decision-brief-v119.js?v=467b119','Build 119 safety boundary'):req(token in page,f'Business Health page missing Build 119 token: {token}')
req(len(re.findall(r'<h1(?:\s|>)',page,re.I))==1,'Business Health page must retain exactly one H1');req('/api/admin/business-health-decision-brief' in client and "method:'GET'" in client and "method:'POST'" not in client,'Build 119 client must remain GET-only');req('format=markdown' in client and 'new Blob' in client and 'No decision, approval, acknowledgement or resolution state was stored' in client,'Build 119 client must expose read-only export boundary')
files=[str(row.get('file')or'') for row in(manifest.get('migrations')or[]) if isinstance(row,dict)];req(files==EXPECTED,'canonical D1 migration stream must remain exactly 0001-0004');req('0005_' not in json.dumps(manifest),'Build 119 must not introduce migration 0005');req("run_current_contract('scripts/release467_build119_gate.py','Release 467 Build 119')" in provenance,'active System Gate provenance must call Build 119');req("run_current_contract('scripts/release467_build118_gate.py','Release 467 Build 118')" not in provenance,'Build 118 must no longer be current provenance gate')
for path in ('AI_HANDOFF.md','PROJECT_STATUS_AND_ROADMAP.md','SANITY_HEALTH_CHECK.md','MARKDOWN_INDEX.md','docs/operations/IT_PREFLIGHT_STARTUP_RELEASE_GUIDE.md'):
    body=read(path)
    for token in (B118_SHA,B118_TREE,*[str(x) for x in B118_PROOFS.values()],str(B118_PAGES),str(B118_LIVE)):req(token in body,f'{path} missing Build 118 closure token {token}')
    req('Build 119' in body and 'Business Health Escalation Decision Brief' in body,f'{path} missing Build 119 identity')
for path in ('functions/api/_lib/businessHealthDecisionBrief.js','functions/api/admin/business-health-decision-brief.js','public/js/admin-business-health-decision-brief-v119.js','functions/api/admin/it-operations-control-tower.js','functions/api/_lib/currentReliability.js','functions/api/admin/current-deployment-preflight.js','public/js/admin-it-control-tower.js'):command(['node','--check',str(ROOT/path)],f'JavaScript syntax {path}')
command(['node','scripts/release467_build119_business_health_decision_brief_test.mjs'],'Build 119 runtime proof')
for path,label in (('scripts/current_authority_restart_integrity_gate.py','restart integrity'),('scripts/current_it_release_truth_gate.py','I.T. truth'),('scripts/current_reliability_truth_gate.py','Reliability truth'),('scripts/current_deployment_preflight_truth_gate.py','Deployment Preflight truth')):command([sys.executable,path],label)
if FAIL:
    print('RELEASE 467 BUILD 119 GATE: FAIL');[print('-',x) for x in FAIL];sys.exit(1)
print('RELEASE 467 BUILD 119 GATE: PASS');print('Build 118 six-proof closure: INGESTED BY BUILD 119');print('Business Health decision brief: READ-ONLY / EXISTING ACTION QUEUE AUTHORITATIVE');print('Decision/approval/trend-history/Accounting/Inventory/Creative/provider mutation: ZERO');print('Canonical D1 migrations: 0001-0004 / UNCHANGED')
