#!/usr/bin/env python3
"""Release 467 Build 120 — Business Health Owner Context Transfer & Review Session Packet gate."""
from pathlib import Path
import json,re,subprocess,sys
ROOT=Path(__file__).resolve().parents[1];FAIL=[]
B119_SHA='9f5f763c277dc5c250cfe72d85e4235dc3e778dd';B119_TREE='2fa9a857ce4756c38d746acdd5f21e44e8f1e4f1'
B119_PROOFS={'system_gate_run':34705738437,'current_application_quality_run':34705738429,'it_admin_runtime_proof_run':34705738421,'branch_hygiene_run':34705738427};B119_PAGES=34706136674;B119_LIVE=34706179149
EXPECTED=['0001_release464_migration_authority.sql','0002_release464_operational_acceptance.sql','0003_release464_business_growth.sql','0004_release465_storefront_quality.sql']
def req(ok,msg):
    if not ok: FAIL.append(msg)
def read(path): return (ROOT/path).read_text(encoding='utf-8',errors='replace')
def load(path): return json.loads(read(path))
def command(args,label):
    r=subprocess.run(args,cwd=ROOT,text=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=False)
    if r.stdout.strip(): print(r.stdout.strip())
    if r.returncode!=0: FAIL.append(f"{label} failed: {(r.stderr or r.stdout).strip()[-3000:]}")
pointer=load('current-development-authority.json');prior=load('release467-build119-business-health-decision-brief.json');current=load('release467-build120-business-health-review-session.json');manifest=load('migrations/canonical/manifest.json')
helper=read('functions/api/_lib/businessHealthReviewSession.js');endpoint=read('functions/api/admin/business-health-review-session.js');client=read('public/js/admin-business-health-review-session-v120.js');context_client=read('public/js/admin-business-health-review-context-v120.js');page=read('admin/business-health/index.html');provenance=read('scripts/current_system_gate_provenance_gate.py')
req(pointer.get('release')==467 and pointer.get('build')==120,'current pointer must identify Release 467 Build 120');req(pointer.get('title')=='Business Health Owner Context Transfer & Review Session Packet','Build 120 title drifted');req(pointer.get('state')=='DEVELOPMENT_GREEN','candidate pointer must retain inherited Development GREEN state');req(pointer.get('accepted_dev_sha')==B119_SHA and pointer.get('accepted_dev_tree_sha')==B119_TREE,'Build 120 accepted baseline must be exact Build 119');req((pointer.get('acceptance')or{})==B119_PROOFS,'Build 120 inherited four-proof baseline mismatch')
last=(pointer.get('restart_integrity')or{}).get('last_fully_verified')or{};req(last.get('build')==119 and last.get('dev_sha')==B119_SHA and last.get('tree_sha')==B119_TREE,'restart integrity must identify exact Build 119');req((last.get('proofs')or{})==B119_PROOFS,'restart Build 119 proof set drifted');prod=pointer.get('production_checkpoint')or{};req(prod.get('build')==119 and prod.get('main_sha')==B119_SHA and prod.get('tree_sha')==B119_TREE,'Production baseline must be exact Build 119');req(prod.get('production_pages_deploy_run')==B119_PAGES and prod.get('production_live_resource_integrity_run')==B119_LIVE,'Build 119 Production proof IDs drifted')
req(prior.get('state')=='PRODUCTION_GREEN','Build 119 must be ingested as Production GREEN');closure=prior.get('final_closure')or{};req(closure.get('dev_sha')==B119_SHA and closure.get('tree_sha')==B119_TREE,'Build 119 final closure SHA/tree mismatch');req((closure.get('proofs')or{})==B119_PROOFS,'Build 119 final proof mismatch');req(closure.get('ingested_by_build')==120,'Build 119 closure must be ingested by Build 120');req('not self-recorded by Build 119' in str(closure.get('recorded_by')or''),'Build 119 non-self-recording provenance missing');pp=prior.get('production_checkpoint')or{};req(pp.get('main_sha')==B119_SHA and pp.get('tree_sha')==B119_TREE and pp.get('production_pages_deploy_run')==B119_PAGES and pp.get('production_live_resource_integrity_run')==B119_LIVE,'Build 119 Production closure mismatch')
req(current.get('state')=='DEVELOPMENT_CLOSURE_CANDIDATE','Build 120 must remain closure candidate');req(current.get('final_closure') is None and current.get('production_checkpoint') is None,'Build 120 must not self-claim later workflow proof');start=(current.get('starting_point')or{}).get('development')or{};req(start.get('sha')==B119_SHA and start.get('tree')==B119_TREE,'Build 120 starting Development identity mismatch')
for token in ('BUSINESS_HEALTH_REVIEW_SESSION_BUILD=120','existing_action_queue_authoritative:true','build119_decision_matrix_authoritative:true','url_context_only:true','review_session_persistence:false','context_persistence:false','second_action_queue_created:false',"mutation_capability:'none'",'accounting_posting:false','inventory_mutation:false','provider_execution:false'):req(token in helper,f'Build 120 helper missing token: {token}')
for forbidden in (r'\bfetch\s*\(',r'\bdb\.',r'\blocalStorage\.',r'\bsessionStorage\.',r'\bsetInterval\s*\('):req(not re.search(forbidden,helper),f'Build 120 pure helper gained forbidden behavior: {forbidden}')
for token in ('getDecisionBrief','buildBusinessHealthReviewSession',"role:'read_only_business_health_review_session'","format==='markdown'",'review_session_persistence:false','context_persistence:false','decision_persistence:false','approval_persistence:false'):req(token in endpoint,f'Build 120 endpoint missing token: {token}')
req('onRequestPost' not in endpoint,'Build 120 endpoint must expose no POST handler')
for forbidden in ('UPDATE ','INSERT ','DELETE ','CREATE TABLE','ALTER TABLE','DROP TABLE'):req(forbidden not in endpoint.upper(),f'Build 120 endpoint contains forbidden DML/DDL: {forbidden}')
for token in ('b120ReviewSession','b120Export','data-business-health-review-session-build="120"','admin-business-health-review-session-v120.js?v=467b120','Build 120 safety boundary'):req(token in page,f'Business Health page missing Build 120 token: {token}')
req(len(re.findall(r'<h1(?:\s|>)',page,re.I))==1,'Business Health page must retain exactly one H1');req('/api/admin/business-health-review-session' in client and "method:'GET'" in client and "method:'POST'" not in client,'Build 120 client must remain GET-only');req('format=markdown' in client and 'new Blob' in client and 'No review, decision, approval, acknowledgement or resolution state was stored' in client,'Build 120 client must expose read-only export boundary')
for token in ('business_health_source','business_health_period','business_health_owner','business_health_state','data-business-health-context-build','URL context only'):
    req(token in context_client,f'Build 120 destination context client missing token: {token}')
for path in ('admin/finance/index.html','admin/month-end/index.html','admin/project-profitability-reconciliation/index.html','admin/it/index.html'):
    body=read(path);req('admin-business-health-review-context-v120.js?v=467b120' in body,f'{path} missing Build 120 context banner client')
files=[str(row.get('file')or'') for row in(manifest.get('migrations')or[]) if isinstance(row,dict)];req(files==EXPECTED,'canonical D1 migration stream must remain exactly 0001-0004');req('0005_' not in json.dumps(manifest),'Build 120 must not introduce migration 0005');req("run_current_contract('scripts/release467_build120_gate.py','Release 467 Build 120')" in provenance,'active System Gate provenance must call Build 120');req("run_current_contract('scripts/release467_build119_gate.py','Release 467 Build 119')" not in provenance,'Build 119 must no longer be current provenance gate')
for path in ('AI_HANDOFF.md','PROJECT_STATUS_AND_ROADMAP.md','SANITY_HEALTH_CHECK.md','MARKDOWN_INDEX.md','docs/operations/IT_PREFLIGHT_STARTUP_RELEASE_GUIDE.md'):
    body=read(path)
    for token in (B119_SHA,B119_TREE,*[str(x) for x in B119_PROOFS.values()],str(B119_PAGES),str(B119_LIVE)):req(token in body,f'{path} missing Build 119 closure token {token}')
    req('Build 120' in body and 'Business Health Owner Context Transfer' in body,f'{path} missing Build 120 identity')
for path in ('functions/api/_lib/businessHealthReviewSession.js','functions/api/admin/business-health-review-session.js','public/js/admin-business-health-review-session-v120.js','public/js/admin-business-health-review-context-v120.js','public/js/admin-business-health-decision-brief-v119.js','functions/api/admin/it-operations-control-tower.js','functions/api/_lib/currentReliability.js','functions/api/admin/current-deployment-preflight.js','public/js/admin-it-control-tower.js'):command(['node','--check',str(ROOT/path)],f'JavaScript syntax {path}')
command(['node','scripts/release467_build120_business_health_review_session_test.mjs'],'Build 120 runtime proof')
for path,label in (('scripts/current_authority_restart_integrity_gate.py','restart integrity'),('scripts/current_it_release_truth_gate.py','I.T. truth'),('scripts/current_reliability_truth_gate.py','Reliability truth'),('scripts/current_deployment_preflight_truth_gate.py','Deployment Preflight truth')):command([sys.executable,path],label)
if FAIL:
    print('RELEASE 467 BUILD 120 GATE: FAIL');[print('-',x) for x in FAIL];sys.exit(1)
print('RELEASE 467 BUILD 120 GATE: PASS');print('Build 119 six-proof closure: INGESTED BY BUILD 120');print('Business Health owner context: URL-ONLY / REVIEW SESSION PERSISTENCE ZERO');print('Decision/approval/Accounting/Inventory/Creative/provider mutation: ZERO');print('Canonical D1 migrations: 0001-0004 / UNCHANGED')
