#!/usr/bin/env python3
"""Release 467 Build 118 — Business Health Rolling Trend & Escalation Review gate."""
from pathlib import Path
import json,re,subprocess,sys
ROOT=Path(__file__).resolve().parents[1];FAIL=[]
B117_SHA='98ca6ee1a501d7ba8484f1b5ea31be696c907034';B117_TREE='e06d666285f654baded4f0948eff6984b38fc41b'
B117_PROOFS={'system_gate_run':34700359583,'current_application_quality_run':34700359610,'it_admin_runtime_proof_run':34700359586,'branch_hygiene_run':34700359581};B117_PAGES=34700443075;B117_LIVE=34700490013
EXPECTED=['0001_release464_migration_authority.sql','0002_release464_operational_acceptance.sql','0003_release464_business_growth.sql','0004_release465_storefront_quality.sql']
def req(ok,msg):
    if not ok: FAIL.append(msg)
def read(path): return (ROOT/path).read_text(encoding='utf-8',errors='replace')
def load(path): return json.loads(read(path))
def command(args,label):
    r=subprocess.run(args,cwd=ROOT,text=True,stdout=subprocess.PIPE,stderr=subprocess.PIPE,check=False)
    if r.stdout.strip(): print(r.stdout.strip())
    if r.returncode!=0: FAIL.append(f"{label} failed: {(r.stderr or r.stdout).strip()[-3000:]}")
pointer=load('current-development-authority.json');prior=load('release467-build117-business-health-period-comparison.json');current=load('release467-build118-business-health-rolling-trend.json');manifest=load('migrations/canonical/manifest.json')
helper=read('functions/api/_lib/businessHealthRollingTrend.js');endpoint=read('functions/api/admin/business-health-rolling-trend.js');client=read('public/js/admin-business-health-rolling-trend-v118.js');page=read('admin/business-health/index.html');provenance=read('scripts/current_system_gate_provenance_gate.py')
req(pointer.get('release')==467 and pointer.get('build')==118,'current pointer must identify Release 467 Build 118');req(pointer.get('title')=='Business Health Rolling Trend & Escalation Review','Build 118 title drifted');req(pointer.get('state')=='DEVELOPMENT_GREEN','candidate pointer must retain inherited Development GREEN state');req(pointer.get('accepted_dev_sha')==B117_SHA and pointer.get('accepted_dev_tree_sha')==B117_TREE,'Build 118 accepted baseline must be exact Build 117');req((pointer.get('acceptance')or{})==B117_PROOFS,'Build 118 inherited four-proof baseline mismatch')
last=(pointer.get('restart_integrity')or{}).get('last_fully_verified')or{};req(last.get('build')==117 and last.get('dev_sha')==B117_SHA and last.get('tree_sha')==B117_TREE,'restart integrity must identify exact Build 117');req((last.get('proofs')or{})==B117_PROOFS,'restart Build 117 proof set drifted');prod=pointer.get('production_checkpoint')or{};req(prod.get('build')==117 and prod.get('main_sha')==B117_SHA and prod.get('tree_sha')==B117_TREE,'Production baseline must be exact Build 117');req(prod.get('production_pages_deploy_run')==B117_PAGES and prod.get('production_live_resource_integrity_run')==B117_LIVE,'Build 117 Production proof IDs drifted')
req(prior.get('state')=='PRODUCTION_GREEN','Build 117 must be ingested as Production GREEN');closure=prior.get('final_closure')or{};req(closure.get('dev_sha')==B117_SHA and closure.get('tree_sha')==B117_TREE,'Build 117 final closure SHA/tree mismatch');req((closure.get('proofs')or{})==B117_PROOFS,'Build 117 final proof mismatch');req(closure.get('ingested_by_build')==118,'Build 117 closure must be ingested by Build 118');req('not self-recorded by Build 117' in str(closure.get('recorded_by')or''),'Build 117 non-self-recording provenance missing');pp=prior.get('production_checkpoint')or{};req(pp.get('main_sha')==B117_SHA and pp.get('tree_sha')==B117_TREE and pp.get('production_pages_deploy_run')==B117_PAGES and pp.get('production_live_resource_integrity_run')==B117_LIVE,'Build 117 Production closure mismatch')
req(current.get('state')=='DEVELOPMENT_CLOSURE_CANDIDATE','Build 118 must remain closure candidate');req(current.get('final_closure') is None and current.get('production_checkpoint') is None,'Build 118 must not self-claim later workflow proof');start=(current.get('starting_point')or{}).get('development')or{};req(start.get('sha')==B117_SHA and start.get('tree')==B117_TREE,'Build 118 starting Development identity mismatch')
for token in ('BUSINESS_HEALTH_ROLLING_TREND_BUILD=118','persistent_worsening','reversal_worsening','newly_worsening','recovering','sustained_improving','trend_history_persistence:false','human_escalation_review_only:true','profitability_historical_claim:false','it_historical_claim:false',"mutation_capability:'none'",'accounting_posting:false','inventory_mutation:false','provider_execution:false'):req(token in helper,f'Build 118 helper missing token: {token}')
for forbidden in (r'\bfetch\s*\(',r'\bdb\.',r'\blocalStorage\.',r'\bsessionStorage\.',r'\bsetInterval\s*\('):req(not re.search(forbidden,helper),f'Build 118 pure helper gained forbidden behavior: {forbidden}')
for token in ('loadRelease465BusinessHealth','buildBusinessHealthRollingTrend',"role:'read_only_business_health_rolling_trend'","format==='markdown'",'trend_history_persistence:false','server_persistence:false','acknowledgement_persistence:false','resolution_persistence:false'):req(token in endpoint,f'Build 118 endpoint missing token: {token}')
req('onRequestPost' not in endpoint,'Build 118 endpoint must expose no POST handler')
for forbidden in ('UPDATE ','INSERT ','DELETE ','CREATE TABLE','ALTER TABLE','DROP TABLE'):req(forbidden not in endpoint.upper(),f'Build 118 endpoint contains forbidden DML/DDL: {forbidden}')
for token in ('b118RollingTrend','b118Export','data-business-health-rolling-trend-build="118"','admin-business-health-rolling-trend-v118.js?v=467b118','Build 118 safety boundary'):req(token in page,f'Business Health page missing Build 118 token: {token}')
req(len(re.findall(r'<h1(?:\s|>)',page,re.I))==1,'Business Health page must retain exactly one H1');req('/api/admin/business-health-rolling-trend' in client and "method:'GET'" in client and "method:'POST'" not in client,'Build 118 client must remain GET-only');req('format=markdown' in client and 'new Blob' in client and 'No acknowledgement or resolution state was stored' in client,'Build 118 client must expose read-only export boundary')
files=[str(row.get('file')or'') for row in(manifest.get('migrations')or[]) if isinstance(row,dict)];req(files==EXPECTED,'canonical D1 migration stream must remain exactly 0001-0004');req('0005_' not in json.dumps(manifest),'Build 118 must not introduce migration 0005');req("run_current_contract('scripts/release467_build118_gate.py','Release 467 Build 118')" in provenance,'active System Gate provenance must call Build 118');req("run_current_contract('scripts/release467_build117_gate.py','Release 467 Build 117')" not in provenance,'Build 117 must no longer be current provenance gate')
for path in ('AI_HANDOFF.md','PROJECT_STATUS_AND_ROADMAP.md','SANITY_HEALTH_CHECK.md','MARKDOWN_INDEX.md','docs/operations/IT_PREFLIGHT_STARTUP_RELEASE_GUIDE.md'):
    body=read(path)
    for token in (B117_SHA,B117_TREE,*[str(x) for x in B117_PROOFS.values()],str(B117_PAGES),str(B117_LIVE)):req(token in body,f'{path} missing Build 117 closure token {token}')
    req('Build 118' in body and 'Business Health Rolling Trend' in body,f'{path} missing Build 118 identity')
for path in ('functions/api/_lib/businessHealthRollingTrend.js','functions/api/admin/business-health-rolling-trend.js','public/js/admin-business-health-rolling-trend-v118.js','functions/api/admin/it-operations-control-tower.js','functions/api/_lib/currentReliability.js','functions/api/admin/current-deployment-preflight.js','public/js/admin-it-control-tower.js'):command(['node','--check',str(ROOT/path)],f'JavaScript syntax {path}')
command(['node','scripts/release467_build118_business_health_rolling_trend_test.mjs'],'Build 118 runtime proof')
for path,label in (('scripts/current_authority_restart_integrity_gate.py','restart integrity'),('scripts/current_it_release_truth_gate.py','I.T. truth'),('scripts/current_reliability_truth_gate.py','Reliability truth'),('scripts/current_deployment_preflight_truth_gate.py','Deployment Preflight truth')):command([sys.executable,path],label)
if FAIL:
    print('RELEASE 467 BUILD 118 GATE: FAIL');[print('-',x) for x in FAIL];sys.exit(1)
print('RELEASE 467 BUILD 118 GATE: PASS');print('Build 117 six-proof closure: INGESTED BY BUILD 118');print('Business Health rolling trend: READ-ONLY / HUMAN ESCALATION REVIEW ONLY');print('Trend history / persistence / Accounting / Inventory / Creative / provider mutation: ZERO');print('Canonical D1 migrations: 0001-0004 / UNCHANGED')
