import fs from 'node:fs';
const [input,sha,out]=process.argv.slice(2);const raw=JSON.parse(fs.readFileSync(input,'utf8'));const sets=Array.isArray(raw)?raw:(raw.results||[]);
if(sets.length!==3)throw new Error('Unexpected Build 317 statement count '+sets.length);
const reads=sets.map(x=>Number(x?.meta?.rows_read||0)),aggregate=reads.reduce((a,b)=>a+b,0);if(aggregate>20000)throw new Error('Rows-read ceiling exceeded '+aggregate);
const candidates=sets[0]?.results||[],events=sets[1]?.results||[],integrity=(sets[2]?.results||[])[0]||{};
if(Number(integrity.active_projects||0)!==5)throw new Error('Expected five active Creative Projects');
if(Number(integrity.maker_story_profiles||0)!==2)throw new Error('Expected two existing Maker Story profiles before Build 317');
if(Number(integrity.caip_workspaces||0)!==5||Number(integrity.content_packages||0)!==5)throw new Error('One-project identity coverage drift');
if(Number(integrity.duplicate_caip_source_identities||0)!==0||Number(integrity.duplicate_content_source_identities||0)!==0||Number(integrity.foreign_key_violations||0)!==0)throw new Error('Identity/FK integrity drift');
const evaluated=candidates.map(c=>{
 const identity=Number(c.caip_workspaces||0)===1&&Number(c.content_packages||0)===1;
 const factualTimeline=Number(c.execution_result_events||0)>=1&&Number(c.safe_text_events||0)>=1;
 const reviewedCaip=Number(c.approved_source_evidence||0)>=2&&Number(c.reviewed_story_plans||0)>=1&&Number(c.source_backed_story_items||0)>=2;
 const ready=identity&&(factualTimeline||reviewedCaip);
 const score=(factualTimeline?1000:0)+(reviewedCaip?900:0)+Number(c.execution_result_events||0)*50+Number(c.approved_source_evidence||0)*20+Number(c.reviewed_story_plans||0)*20+Number(c.source_backed_story_items||0)*10+Number(c.project_fact_fields||0);
 return {...c,identity_ready:identity,factual_timeline_ready:factualTimeline,reviewed_caip_ready:reviewedCaip,third_story_ready:ready,readiness_score:score};
}).sort((a,b)=>b.readiness_score-a.readiness_score||Number(a.creative_work_project_id)-Number(b.creative_work_project_id));
const ready=evaluated.filter(c=>c.third_story_ready);
const selected=ready.length?ready[0]:null;
const state=selected?'ONE_REAL_THIRD_PROJECT_READY':'NO_THIRD_PROJECT_FACTUALLY_READY';
const selectedEvents=selected?events.filter(e=>Number(e.creative_work_project_id)===Number(selected.creative_work_project_id)):[];
const evidence={release:467,build:317,exact_development_sha:sha,statement_count:3,rows_read_by_statement:reads,aggregate_rows_read:aggregate,rows_read_ceiling:20000,candidates:evaluated,selected_candidate:selected,selected_candidate_events:selectedEvents,selection_state:state,selection_count:selected?1:0,selection_rule:'identity must be exactly one CAIP workspace + one Content Studio package, plus either factual non-planning execution evidence or reviewed source-backed CAIP evidence; metadata alone is insufficient',public_media_rights_separate:true,private_media_promoted:false,d1_mutation:false,production_d1_contact:false,integrity};
fs.writeFileSync(out,JSON.stringify(evidence,null,2)+'\n');
console.log('BUILD317_SELECTION_STATE=',state);
console.log('BUILD317_CANDIDATES=',JSON.stringify(evaluated));
console.log('BUILD317_SELECTED=',JSON.stringify(selected));
console.log('BUILD317_SELECTED_EVENTS=',JSON.stringify(selectedEvents));
console.log('BUILD317_ROWS_READ=',JSON.stringify(reads));
console.log('BUILD317_AGGREGATE_ROWS_READ=',aggregate);
console.log('BUILD317_READINESS_DISCOVERY=GREEN');
