import fs from 'node:fs';
const [input,sha,output]=process.argv.slice(2);
const raw=JSON.parse(fs.readFileSync(input,'utf8'));const sets=Array.isArray(raw)?raw:(raw.results||[]);
if(sets.length!==6)throw new Error('Unexpected statement count '+sets.length);
const reads=sets.map(x=>Number(x?.meta?.rows_read||0)),aggregate=reads.reduce((a,b)=>a+b,0);if(aggregate>20000)throw new Error('Rows-read ceiling exceeded '+aggregate);
const row=i=>(sets[i]?.results||[])[0]||{};const pre=row(0),trace=row(3),media=row(4),integrity=row(5);
if(String(trace.story_review_status)!=='reviewed'||Number(trace.public_story_candidate||0)!==1)throw new Error('Maker Story review/public-candidate reconciliation failed');
if(Number(trace.profile_review_actor_user_id||0)<=0||Number(trace.publication_approved_by_user_id||0)<=0||Number(trace.publication_published_by_user_id||0)<=0)throw new Error('Human review/publication actor traceability missing');
if(Number(trace.approved_copy_count||0)!==2||Number(trace.locked_copy_count||0)!==2||Number(trace.published_journal_count||0)!==1)throw new Error('Copy/publication authority drift');
for(const k of ['public_event_candidates','selected_media_evidence','public_allowed_caip_assets','public_allowed_private_uploads','website_gallery_rows'])if(Number(media[k]||0)!==0)throw new Error('Media/public-rights boundary drift '+k);
if(Number(integrity.maker_story_profiles||0)!==1||Number(integrity.caip_workspaces||0)!==1||Number(integrity.content_packages||0)!==1||Number(integrity.review_first_social_ready||0)!==1||Number(integrity.posted_social_rows||0)!==0||Number(integrity.foreign_key_violations||0)!==0)throw new Error('Identity/social/provider boundary drift');
const evidence={release:467,build:307,exact_development_sha:sha,statement_count:6,rows_read_by_statement:reads,aggregate_rows_read:aggregate,rows_read_ceiling:20000,preflight:pre,traceability:trace,media_public_rights_boundary:media,integrity,story_public_candidate_scope:'reviewed_factual_story_text_only',media_rights_scope:'separate_never_inferred',provider_execution:false,provider_publication:false,production_d1_contact:false,r2_mutation:false,schema_change:false};
fs.writeFileSync(output,JSON.stringify(evidence,null,2)+'\n');
console.log('BUILD307_TRACEABILITY=',JSON.stringify(trace));
console.log('BUILD307_MEDIA_BOUNDARY=',JSON.stringify(media));
console.log('BUILD307_INTEGRITY=',JSON.stringify(integrity));
console.log('BUILD307_ROWS_READ=',JSON.stringify(reads));
console.log('BUILD307_AGGREGATE_ROWS_READ=',aggregate);
console.log('BUILD307_REVIEW_PUBLICATION_TRACEABILITY=GREEN');
