#!/usr/bin/env python3
"""Canonical repository and current-release forward-sanity authority."""
from __future__ import annotations
import json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];failures=[]
def require(condition,message):
 if not condition:failures.append(message)
release=json.loads((ROOT/'development-release.json').read_text(encoding='utf-8'))
require(release.get('environment')=='development','current release must target Development');require(release.get('release')==448,'current Development release must be Release 448');require(release.get('label')=='Platform Expansion','current release label must be Platform Expansion');require(release.get('release_track')=='single-current-release','single current release track is required');require(release.get('pages_project')=='devilndove-site-dev','Development Pages project authority drifted')
previous=release.get('previous_release',{});require(previous.get('release')==447,'Release 447 completion authority missing');require(previous.get('state')=='complete','Release 447 must remain complete')
module_keys=[r.get('key') for r in release.get('canonical_modules',[])];require(module_keys==['storefront','creators','socials','financials','it-platform'],f'canonical module authority drifted: {module_keys}');require(all(r.get('status')=='active' for r in release.get('canonical_modules',[])),'all five canonical modules must remain active');mp=release.get('module_policy',{});require(mp.get('minimum_canonical_modules')==5,'minimum canonical module authority drifted');require(mp.get('future_modules_allowed') is True,'future top-level modules must remain possible')
clients=release.get('clients',[]);client_keys=[r.get('key') for r in clients];require(client_keys==['web','phone','desktop'],f'canonical client authority drifted: {client_keys}');require(all(r.get('status')=='active' for r in clients),'Web/Phone/Desktop must remain active first-class clients');[require(r.get('notifications')==['new_release','new_item'],f"{r.get('key')} notification contract drifted") for r in clients]
policy=release.get('release_policy',{});require(policy.get('one_current_release') is True,'one-current-release policy must remain enabled');require(policy.get('legacy_build_numbers_are_provenance_only') is True,'legacy build numbers must be provenance only');require(policy.get('historical_build_gates_allowed') is False,'historical build-number gates must remain retired');require(policy.get('production_promotion')=='closed','Production promotion must remain closed during Development work');require(policy.get('deferred_it_tasks_block_release') is False,'deferred I.T. tasks must not gate forward releases');require(policy.get('external_credentials_for_feature_development')=='assume_available_or_mocked','feature development must not be blocked by deferred provider credentials');require(policy.get('current_release_d1_changes_allowed') is True,'Release 448 must allow protected Development D1 evolution')
infra=release.get('development_infrastructure',{});require(infra.get('cloudflare_account_id')=='c0d5bc25df16ae5b7d47c985c4b7b787','Development Cloudflare account authority drifted');require(infra.get('local_access_preflight')=='python scripts/cloudflare_development_access.py --auth-only','Development Cloudflare access preflight authority drifted')
baseline=release.get('database_baseline',{});require(baseline.get('release')==447,'verified D1 baseline release drifted');require(baseline.get('apply_status')=='applied_and_verified_development','verified D1 baseline state drifted');require('Read-only D1/R2 verification first' in baseline.get('startup_rule',''),'read-only startup rule missing')
it=release.get('deferred_it_test_environment',{});require(it.get('state')=='backlog_non_blocking','deferred I.T. test environment state drifted');require(it.get('release_gating') is False,'deferred I.T. test environment may not gate releases');it_keys=[r.get('key') for r in it.get('tasks',[])];require(it_keys==['authenticated-development-runtime','stripe-test','paypal-sandbox','caip-private-media'],f'deferred I.T. backlog drifted: {it_keys}');require(all(r.get('status')=='deferred' for r in it.get('tasks',[])),'deferred I.T. tasks must remain explicitly deferred until tested')
workstreams={r.get('key'):r for r in release.get('workstreams',[])}
for key in ('client-platform-continuity','storefront-merchandising','product-material-lineage','product-tool-lineage','manufacturer-provenance-reviews','product-image-quality','it-integration-registry','carousel-movie-reuse','movie-data-convergence','unverified-process-states'):require(key in workstreams,f'Release 448 workstream missing: {key}')
storefront=workstreams.get('storefront-merchandising',{});require('source_converged' in str(storefront.get('status','')),'Storefront Shop/Collections/Collages convergence must remain recorded');require(storefront.get('workspace')=='/admin/storefront-merchandising/','Storefront merchandising workspace authority drifted');require(storefront.get('public_surfaces')==['/shop/','/collections/','/collages/'],'Storefront public surfaces drifted')
migrations={r.get('key'):r for r in release.get('current_release_migrations',[])}
for key,file in (('product-lineage','database_release448_product_lineage.sql'),('media-movie-it','database_release448_media_it.sql'),('storefront-merchandising','database_release448_storefront_merchandising.sql')):
 row=migrations.get(key,{});require(row.get('file')==file,f'Release 448 migration authority missing/drifted: {key}');require(row.get('production_allowed') is False,f'{key} migration must never allow Production');require(row.get('development_d1_status') in {'blocked_missing_github_cloudflare_token','applied_and_verified_development'},f'{key} D1 state is not truthful/current')
forward=release.get('forward_queue',[])
for marker in ('CAIP','Inventory','Supplies','Tools'):require(marker in forward,f'forward queue missing: {marker}')
require(not list(ROOT.glob('BUILD*.md')),'historical BUILD*.md files must not exist in repository root');require(not (ROOT/'docs/archive').exists(),'docs/archive must not ship; Git history is the archive');require(not (ROOT/'docs/releases').exists(),'docs/releases must not ship; current release belongs in development-release.json');require(not (ROOT/'tmp').exists(),'tmp must not ship in repository');[require(not (ROOT/j).exists(),f'junk placeholder remains: {j}') for j in ('testfile','java.md','updated.md')]
for required in ('database_full_schema.sql','scripts/cloudflare_development_access.py','scripts/apply_development_platform_convergence.py','scripts/development_runtime_acceptance.py','LIVE_TESTING_GUIDE.md'):require((ROOT/required).exists(),f'required current authority missing: {required}')
workflow_dir=ROOT/'.github/workflows';require((workflow_dir/'system-gate.yml').exists(),'canonical .github/workflows/system-gate.yml is missing');require(not list(workflow_dir.glob('build*-system-gate.yml')),'historical build-numbered system gates must not be active')
if (workflow_dir/'system-gate.yml').exists():
 workflow=(workflow_dir/'system-gate.yml').read_text(encoding='utf-8');require(not re.search(r'build\d+',workflow,flags=re.I),'canonical system gate must not depend on historical build-numbered scripts');require('python scripts/development_runtime_acceptance.py --self-check' in workflow,'System Gate must validate runtime acceptance safety/manifest');require('python scripts/release448_storefront_merchandising_gate.py' in workflow,'System Gate must validate Storefront merchandising convergence')
runbook=(ROOT/'LIVE_TESTING_GUIDE.md').read_text(encoding='utf-8');require(not re.search(r'Build\s+\d+',runbook,flags=re.I),'active I.T. testing runbook must not carry numbered Build instructions')
for marker in ('https://devilndove-site-dev.pages.dev','DND_DEV_SESSION_COOKIE','Production mutation is forbidden','Provider readiness never implies provider acceptance','non-blocking'):require(marker in runbook,f'active I.T. testing runbook missing safeguard: {marker}')
runtime=(ROOT/'scripts/development_runtime_acceptance.py').read_text(encoding='utf-8')
for marker in ('ALLOWED_HOSTS = {"devilndove-site-dev.pages.dev"}','SESSION_ENV = "DND_DEV_SESSION_COOKIE"','method="GET"','Production, custom-domain and arbitrary targets are forbidden','provider_transaction_acceptance','caip_private_media_acceptance'):require(marker in runtime,f'Development runtime acceptance missing safeguard: {marker}')
require('--password' not in runtime and '--token' not in runtime and '--cookie' not in runtime,'runtime acceptance must not accept credentials through CLI flags')
wrangler=(ROOT/'wrangler.toml').read_text(encoding='utf-8')
for marker in ('name = "devilndove-site-dev"','binding = "DB"','database_name = "devilndove-dev"','binding = "PRODUCT_MEDIA_BUCKET"','bucket_name = "devilndove-toolshed-images-dev"','binding = "CAIP_PRIVATE_MEDIA_BUCKET"','bucket_name = "devilndove-caip-media-dev"'):require(marker in wrangler,f'Development infrastructure authority missing: {marker}')
require('account_id =' not in wrangler,'Pages wrangler.toml must not carry account_id; local tooling pins CLOUDFLARE_ACCOUNT_ID instead')
access=(ROOT/'scripts/cloudflare_development_access.py').read_text(encoding='utf-8')
for marker in ("EXPECTED_ACCOUNT_ID = 'c0d5bc25df16ae5b7d47c985c4b7b787'","EXPECTED_DATABASE_NAME = 'devilndove-dev'","EXPECTED_DATABASE_ID = 'dbc1615b-dcbe-4951-973b-b47c99c73bfa'","'devilndove-toolshed-images-dev'","'devilndove-caip-media-dev'","env['CLOUDFLARE_ACCOUNT_ID'] = EXPECTED_ACCOUNT_ID","--auth-mode","CLOUDFLARE_API_TOKEN","Credentials printed: NEVER"):require(marker in access,f'Development Cloudflare access preflight missing safeguard: {marker}')
infra_api=(ROOT/'functions/api/admin/infrastructure-readiness.js').read_text(encoding='utf-8')
for marker in ('SELECT 1 AS ok','sqlite_master','bucket.list({ limit: 1 })','d1_write: false','r2_write: false','provider_write: false'):require(marker in infra_api,f'read-only infrastructure contract missing: {marker}')
require('captureRuntimeIncident' not in infra_api,'read-only infrastructure readiness must not write incident rows')
for rel in ('functions/api/admin/contracts/catalog-read.js','functions/api/admin/contracts/content-media.js','functions/api/admin/contracts/accounting-read.js'):
 t=(ROOT/rel).read_text(encoding='utf-8');require(not re.search(r'Build\s+\d+',t,flags=re.I),f'active contract carries stale numbered Build identity: {rel}');require('const RELEASE = 448;' in t,f'active contract must declare Release 448 without cross-contract helper import: {rel}');require('release: RELEASE' in t,f'active contract must expose current release metadata: {rel}');require('currentReleaseMetadata' not in t,f'active contract must remain Pages-compatible and not import release helper: {rel}');require(not re.search(r'\bbuild\s*:',t,flags=re.I),f'active contract exposes stale build field: {rel}')
pwa=(ROOT/'public/js/pwa-platform.js').read_text(encoding='utf-8');require('const RELEASE = 448;' in pwa,'shared Web/Phone/Desktop client is not current Release 448');require('checkReleaseUpdate' in pwa and 'checkNewItems' in pwa,'shared clients must support release and item notifications')
version_pattern=re.compile(r'([?&]v=)(\d+)(?:[.-][\w-]+)?(?=["\'&#\s)]|$)');runtime_files=list(ROOT.glob('*.html'))+list((ROOT/'admin').rglob('*.html'))+list((ROOT/'js').rglob('*.js'))+list((ROOT/'public/js').rglob('*.js'))+list((ROOT/'css').rglob('*.css'));future=[]
for path in sorted(set(runtime_files)):
 t=path.read_text(encoding='utf-8')
 for m in version_pattern.finditer(t):
  if int(m.group(2))>int(release['release']):future.append(f'{path.relative_to(ROOT)}:{m.group(2)}')
require(not future,f'future cache majors found: {future[:12]}')
print('PLATFORM FORWARD SANITY');print(f"Current release: {release['release']} — {release['label']}");print(f"Canonical modules: {', '.join(module_keys)}");print(f"Canonical clients: {', '.join(client_keys)} — ACTIVE");print('Storefront Shop / Collections / Collages: SOURCE CONVERGED');print('Development runtime/provider/media test work: DEFERRED I.T. / NON-BLOCKING');print('Release 447: COMPLETE');print('Release 448: ACTIVE');print('Development Cloudflare account: PINNED BY LOCAL TOOLING');print('Pages wrangler account_id: FORBIDDEN');print('Historical build numbers: PROVENANCE ONLY');print('Production mutation capability: NONE')
if failures:
 for i,f in enumerate(failures,1):print(f'{i:03d}. FAIL — {f}')
 raise SystemExit(1)
print('PLATFORM FORWARD SANITY: PASS')
