// Release 465 Build 2 — read-only Inventory & Creator intelligence.
// Existing Product, Inventory, lot provenance, CAIP, Content Studio and pipeline tables remain authoritative.
import { loadMaterialLotPlan, productLotSchemaReadiness, EPSILON } from './productLotProvenance.js';

const rows=r=>Array.isArray(r?.results)?r.results:[];
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const id=v=>{const n=Number(v||0);return Number.isInteger(n)&&n>0?n:0};
const txt=v=>String(v??'').trim();
const low=v=>txt(v).toLowerCase();
const r6=v=>Number(num(v).toFixed(6));
const clamp=(v,f=1,min=1,max=100)=>Number.isInteger(Number(v))?Math.max(min,Math.min(max,Number(v))):f;
async function one(db,sql,b=[]){try{const s=db.prepare(sql);return b.length?await s.bind(...b).first():await s.first()}catch{return null}}
async function many(db,sql,b=[]){try{const s=db.prepare(sql);return rows(b.length?await s.bind(...b).all():await s.all())}catch{return[]}}

export async function loadProductBase(db,productId){
  return id(productId)?one(db,`SELECT product_id,name,slug,sku,product_category,product_type,merchandise_origin,sale_channel,status,review_status,price_cents,currency,inventory_tracking,inventory_quantity,featured_image_url,updated_at FROM products WHERE product_id=? LIMIT 1`,[id(productId)]):null;
}
async function materialRows(db,productId){
  return many(db,`SELECT prl.product_resource_link_id,prl.product_id,prl.resource_kind,prl.source_key,COALESCE(prl.quantity_used,0) quantity_used,COALESCE(prl.consumption_mode,'per_unit') consumption_mode,COALESCE(prl.lot_size_units,1) lot_size_units,sii.site_item_inventory_id,sii.item_name,COALESCE(sii.on_hand_quantity,0) on_hand_quantity,COALESCE(sii.stock_unit_label,'unit') stock_unit_label,COALESCE(sii.usage_unit_label,'unit') usage_unit_label,COALESCE(sii.usage_units_per_stock_unit,1) usage_units_per_stock_unit,COALESCE(sii.unit_cost_cents,0) unit_cost_cents,COALESCE(siup.usage_tracking_mode,CASE WHEN prl.resource_kind='tool' THEN 'reusable' ELSE 'exact' END) tracking_mode FROM product_resource_links prl LEFT JOIN site_item_inventory sii ON LOWER(TRIM(COALESCE(sii.source_type,'')))=LOWER(TRIM(COALESCE(prl.resource_kind,''))) AND sii.external_key=prl.source_key AND COALESCE(sii.is_active,1)=1 LEFT JOIN site_inventory_usage_profiles siup ON siup.site_item_inventory_id=sii.site_item_inventory_id WHERE prl.product_id=? ORDER BY COALESCE(prl.sort_order,0),prl.product_resource_link_id`,[id(productId)]);
}
function usage(row,units){
  const kind=low(row.resource_kind),mode=low(row.consumption_mode)||'per_unit',tracking=low(row.tracking_mode)||(kind==='tool'?'reusable':'exact');
  const q=Math.max(0,num(row.quantity_used)),lot=Math.max(1,num(row.lot_size_units,1)),usageUnits=mode==='end_of_lot'?q*(units/lot):q*units,per=Math.max(EPSILON,num(row.usage_units_per_stock_unit,1));
  const consumes=kind==='supply'&&mode!=='story_only'&&['exact','estimated'].includes(tracking);
  return{kind,mode,tracking,consumes,stockRequired:consumes?usageUnits/per:0};
}

export async function loadProductAvailabilityIntelligence(db,productId,opt={}){
  const product=await loadProductBase(db,productId);if(!product)return null;
  const forecastUnits=clamp(opt.forecastUnits,1,1,100),schema=await productLotSchemaReadiness(db),source=await materialRows(db,product.product_id);
  const materials=[];let canMake=Infinity,has=false,blocked=false,cost=0;
  for(const row of source){
    const per=usage(row,1),plan=usage(row,forecastUnits),inventoryId=id(row.site_item_inventory_id),available=Math.max(0,num(row.on_hand_quantity));
    let lot={ready:per.consumes?0:1,method:'none',covered_stock_quantity:0,estimated_cost_cents:0,blockers:[],candidates:[],allocations:[]};
    if(per.consumes){has=true;if(!inventoryId)lot.blockers.push('No active Inventory record is linked to this Product resource.');else if(!schema.ok)lot.blockers.push(`Lot-provenance authority is not ready: ${schema.missing_tables.join(', ')}`);else lot=await loadMaterialLotPlan(db,inventoryId,plan.stockRequired);}
    const make=per.consumes&&per.stockRequired>EPSILON?Math.max(0,Math.floor((available+EPSILON)/per.stockRequired)):null;if(make!=null)canMake=Math.min(canMake,make);
    const short=per.consumes?Math.max(0,plan.stockRequired-available):0,lotShort=per.consumes&&schema.ok?Math.max(0,plan.stockRequired-num(lot.covered_stock_quantity)):short;
    const blockers=[...(lot.blockers||[])];if(short>EPSILON)blockers.push(`On-hand stock is short by ${r6(short)} ${row.stock_unit_label||'unit'} for this ${forecastUnits}-unit scenario.`);if(per.consumes&&blockers.length)blocked=true;
    const est=per.consumes?Math.max(0,num(lot.estimated_cost_cents)||Math.round(num(row.unit_cost_cents)*plan.stockRequired)):0;cost+=est;
    materials.push({product_resource_link_id:row.product_resource_link_id,resource_kind:per.kind,source_key:row.source_key||'',item_name:row.item_name||row.source_key||'Unlinked resource',consumption_mode:per.mode,tracking_mode:per.tracking,consumes_inventory:per.consumes,site_item_inventory_id:inventoryId||null,stock_unit_label:row.stock_unit_label||'unit',on_hand_quantity:r6(available),per_product_stock_requirement:r6(per.stockRequired),forecast_units:forecastUnits,forecast_stock_requirement:r6(plan.stockRequired),forecast_shortfall_on_hand:r6(short),forecast_shortfall_lot_covered:r6(lotShort),can_make_units_from_on_hand:make,lot_policy:lot.method||'none',lot_ready:Boolean(lot.ready),lot_reconcile_status:lot.reconcile_status||'',lot_candidate_count:(lot.candidates||[]).length,lot_allocation_count:(lot.allocations||[]).length,estimated_forecast_material_cost_cents:Math.round(est),blockers});
  }
  if(!has)canMake=null;else if(!Number.isFinite(canMake))canMake=0;
  const finished=Number(product.inventory_tracking||0)===1?Math.max(0,Math.floor(num(product.inventory_quantity))):null,total=finished==null?canMake:finished+(canMake||0);
  let state='not_inventory_tracked';if(finished!=null){if(finished>=forecastUnits)state='available_now';else if(finished>0)state='limited_finished_stock';else if((canMake||0)>=forecastUnits&&!blocked)state='can_make';else if((canMake||0)>0)state='limited_can_make';else state='unavailable';}else if(has){state=(canMake||0)>=forecastUnits&&!blocked?'can_make':(canMake||0)>0?'limited_can_make':'unavailable';}
  const shortages=materials.filter(x=>x.consumes_inventory&&(x.forecast_shortfall_on_hand>EPSILON||x.forecast_shortfall_lot_covered>EPSILON||x.blockers.length));
  return{product,forecast:{scenario_units:forecastUnits,scenario_is_operator_input:true,actual_planned_quantity_claimed:false,estimated_material_cost_cents:Math.round(cost)},availability:{state,finished_units_on_hand:finished,can_make_units_from_current_on_hand:canMake,total_potential_units_without_purchasing:total,hard_blocked:blocked},materials,shortages,lot_provenance:{schema_ready:schema.ok,missing_tables:schema.missing_tables,deterministic_allocation_required:true},mutation_capability:'none',production_execution_active:false,inventory_consumption_active:false};
}

function similarity(a,b,resources,collections){
  let score=0;const reasons=[];if(txt(a.product_category)&&low(a.product_category)===low(b.product_category)){score+=30;reasons.push(`Same category: ${a.product_category}`)}if(txt(a.product_type)&&low(a.product_type)===low(b.product_type)){score+=10;reasons.push(`Same product type: ${a.product_type}`)}if(txt(a.merchandise_origin)&&low(a.merchandise_origin)===low(b.merchandise_origin)){score+=8;reasons.push(`Same merchandise origin: ${a.merchandise_origin}`)}if(resources){score+=Math.min(30,resources*10);reasons.push(`${resources} shared material/tool resource${resources===1?'':'s'}`)}if(collections){score+=Math.min(20,collections*10);reasons.push(`${collections} shared Storefront collection${collections===1?'':'s'}`)}const ap=Math.max(0,num(a.price_cents)),bp=Math.max(0,num(b.price_cents));if(ap&&bp){const ratio=Math.min(ap,bp)/Math.max(ap,bp);if(ratio>=.7){score+=8;reasons.push('Similar price band')}else if(ratio>=.45){score+=4;reasons.push('Adjacent price band')}}return{score,reasons};
}
export async function loadRelatedProductIntelligence(db,productId,opt={}){
  const base=await loadProductBase(db,productId);if(!base)return null;const limit=clamp(opt.limit,8,1,20);
  const candidates=await many(db,`SELECT product_id,name,slug,sku,product_category,product_type,merchandise_origin,sale_channel,status,review_status,price_cents,currency,inventory_tracking,inventory_quantity,featured_image_url,updated_at FROM products WHERE product_id<>? AND LOWER(COALESCE(status,''))='active' AND LOWER(COALESCE(review_status,'')) IN ('approved','published') ORDER BY updated_at DESC,product_id DESC LIMIT 240`,[base.product_id]);
  const baseResources=new Set((await many(db,`SELECT DISTINCT LOWER(TRIM(COALESCE(source_key,''))) source_key FROM product_resource_links WHERE product_id=? AND TRIM(COALESCE(source_key,''))<>''`,[base.product_id])).map(x=>low(x.source_key)).filter(Boolean));
  const ids=candidates.map(x=>id(x.product_id)).filter(Boolean),rc=new Map(),cc=new Map();
  if(ids.length&&baseResources.size){const ph=ids.map(()=>'?').join(','),r=await many(db,`SELECT product_id,LOWER(TRIM(COALESCE(source_key,''))) source_key FROM product_resource_links WHERE product_id IN (${ph})`,ids);for(const x of r)if(baseResources.has(low(x.source_key)))rc.set(id(x.product_id),(rc.get(id(x.product_id))||0)+1);}
  const baseCollections=new Set((await many(db,`SELECT storefront_collection_id FROM storefront_collection_products WHERE product_id=? AND membership_status='included'`,[base.product_id])).map(x=>id(x.storefront_collection_id)).filter(Boolean));
  if(ids.length&&baseCollections.size){const ph=ids.map(()=>'?').join(','),m=await many(db,`SELECT product_id,storefront_collection_id FROM storefront_collection_products WHERE product_id IN (${ph}) AND membership_status='included'`,ids);for(const x of m)if(baseCollections.has(id(x.storefront_collection_id)))cc.set(id(x.product_id),(cc.get(id(x.product_id))||0)+1);}
  const related=candidates.map(product=>{const pid=id(product.product_id),s=similarity(base,product,rc.get(pid)||0,cc.get(pid)||0);return{product,score:s.score,reasons:s.reasons,shared_resource_count:rc.get(pid)||0,shared_collection_count:cc.get(pid)||0}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||txt(a.product.name).localeCompare(txt(b.product.name))).slice(0,limit);
  return{product:base,related,scoring_authority:'category + type + merchandise origin + shared Product resources + shared Storefront collections + price proximity',automatic_relationship_write:false,mutation_capability:'none'};
}

export async function loadGenealogyExceptions(db,opt={}){
  const limit=clamp(opt.limit,80,1,200);
  const [noLots,noRun,legacy,unreconciled]=await Promise.all([
    many(db,`SELECT r.product_production_run_id,r.run_key,r.product_id,p.name product_name,r.run_status,r.posted_at,COUNT(ml.product_production_run_material_lot_id) lot_allocation_count FROM product_production_runs r LEFT JOIN products p ON p.product_id=r.product_id LEFT JOIN product_production_run_material_lots ml ON ml.product_production_run_id=r.product_production_run_id WHERE LOWER(COALESCE(r.run_status,''))='posted' GROUP BY r.product_production_run_id HAVING COUNT(ml.product_production_run_material_lot_id)=0 ORDER BY COALESCE(r.posted_at,r.created_at) DESC LIMIT ?`,[limit]),
    many(db,`SELECT fil.product_finished_inventory_lot_id,fil.lot_key,fil.product_id,p.name product_name,fil.product_production_run_id,fil.source_kind,fil.quantity_created,fil.lot_status,fil.created_at FROM product_finished_inventory_lots fil LEFT JOIN products p ON p.product_id=fil.product_id LEFT JOIN product_production_runs r ON r.product_production_run_id=fil.product_production_run_id WHERE LOWER(COALESCE(fil.source_kind,''))<>'legacy_opening_balance' AND (fil.product_production_run_id IS NULL OR r.product_production_run_id IS NULL) ORDER BY fil.created_at DESC LIMIT ?`,[limit]),
    many(db,`SELECT p.product_id,p.name,p.inventory_quantity,(SELECT COUNT(*) FROM order_items oi WHERE oi.product_id=p.product_id) order_line_count FROM products p WHERE LOWER(COALESCE(p.merchandise_origin,'')) IN ('made_in_house','handmade') AND COALESCE(p.inventory_quantity,0)>0 AND NOT EXISTS (SELECT 1 FROM product_finished_inventory_lots fil WHERE fil.product_id=p.product_id) ORDER BY p.inventory_quantity DESC,p.product_id LIMIT ?`,[limit]),
    many(db,`SELECT DISTINCT p.product_id,p.name,sii.site_item_inventory_id,sii.item_name,COALESCE(lp.reconcile_status,'needs_review') reconcile_status,COALESCE(lp.depletion_method,'manual') depletion_method FROM products p JOIN product_resource_links prl ON prl.product_id=p.product_id JOIN site_item_inventory sii ON LOWER(TRIM(COALESCE(sii.source_type,'')))=LOWER(TRIM(COALESCE(prl.resource_kind,''))) AND sii.external_key=prl.source_key LEFT JOIN inventory_lot_policies lp ON lp.site_item_inventory_id=sii.site_item_inventory_id WHERE LOWER(COALESCE(prl.resource_kind,''))='supply' AND LOWER(COALESCE(prl.consumption_mode,'per_unit'))<>'story_only' AND LOWER(COALESCE(lp.reconcile_status,'needs_review'))<>'reconciled' ORDER BY p.name,sii.item_name LIMIT ?`,[limit])
  ]);
  const exceptions=[
    ...noLots.map(x=>({severity:'high',type:'posted_run_without_material_lot_allocations',product_id:id(x.product_id)||null,product_name:x.product_name||'',reference_id:id(x.product_production_run_id),reference_key:x.run_key||'',explanation:'A posted production run has no purchase-lot material allocation rows.',next_action:'Review the run and lot provenance before relying on it as forward genealogy evidence.'})),
    ...noRun.map(x=>({severity:'high',type:'finished_lot_without_production_run',product_id:id(x.product_id)||null,product_name:x.product_name||'',reference_id:id(x.product_finished_inventory_lot_id),reference_key:x.lot_key||'',explanation:'A non-legacy finished inventory lot is not backed by an existing production run.',next_action:'Investigate the finished-lot provenance; do not fabricate a historical run.'})),
    ...unreconciled.map(x=>({severity:low(x.reconcile_status)==='blocked'?'high':'medium',type:'material_lot_reconciliation_not_ready',product_id:id(x.product_id)||null,product_name:x.name||'',reference_id:id(x.site_item_inventory_id),reference_key:x.item_name||'',explanation:`Material lot reconciliation is ${x.reconcile_status||'needs_review'} with ${x.depletion_method||'manual'} depletion.`,next_action:'Reconcile purchase lots before a reviewed production release consumes this material.'}))
  ];
  const historical_boundaries=legacy.map(x=>({severity:'info',type:'legacy_opening_balance_boundary',product_id:id(x.product_id),product_name:x.name||'',inventory_quantity:num(x.inventory_quantity),order_line_count:num(x.order_line_count),explanation:'Current finished quantity exists without forward finished-lot provenance. This can be legitimate pre-cutover opening stock.',next_action:'Do not reconstruct history. Forward production must use the lot-aware production authority.'}));
  return{exceptions,historical_boundaries,counts:{high:exceptions.filter(x=>x.severity==='high').length,medium:exceptions.filter(x=>x.severity==='medium').length,info_boundaries:historical_boundaries.length,total_exceptions:exceptions.length},historical_reconstruction_claimed:false,mutation_capability:'none'};
}

async function contentReadiness(db,contentId){
  if(!id(contentId))return{linked:false,score:0,approved_deliverable_count:0,blockers:['No Content Studio project is linked.']};const project=await one(db,`SELECT content_project_id,project_title,review_status,public_release_status,updated_at FROM content_projects WHERE content_project_id=? LIMIT 1`,[id(contentId)]);if(!project)return{linked:false,score:0,approved_deliverable_count:0,blockers:['The linked Content Studio project could not be found.']};
  const c=await one(db,`SELECT (SELECT COUNT(*) FROM content_project_media WHERE content_project_id=? AND is_selected=1 AND safety_status<>'blocked') selected_media_count,(SELECT COUNT(*) FROM content_project_deliverables WHERE content_project_id=? AND approval_status='approved') approved_deliverable_count,(SELECT COUNT(*) FROM content_project_deliverables WHERE content_project_id=? AND deliverable_status='published') published_deliverable_count`,[id(contentId),id(contentId),id(contentId)])||{};
  let score=5;const blockers=[];if(num(c.selected_media_count)>0)score+=7;else blockers.push('Select at least one safe Content Studio media item.');if(num(c.approved_deliverable_count)>0)score+=8;else blockers.push('No approved Content Studio deliverable is available yet.');return{linked:true,content_project:project,selected_media_count:num(c.selected_media_count),approved_deliverable_count:num(c.approved_deliverable_count),published_deliverable_count:num(c.published_deliverable_count),score:Math.min(20,score),blockers};
}
async function evidenceReadiness(db,projectId){
  const c=await one(db,`SELECT (SELECT COUNT(*) FROM creative_media_evidence_ranges WHERE creative_project_id=? AND marker_status='active' AND review_status='approved') approved_marker_count,(SELECT COUNT(*) FROM creative_media_evidence_ranges WHERE creative_project_id=? AND marker_status='active' AND review_status='approved' AND verification_status IN ('source_observed','confirmed')) verified_marker_count,(SELECT COUNT(*) FROM creative_story_evidence WHERE creative_project_id=? AND review_status='approved') approved_story_evidence_count`,[id(projectId),id(projectId),id(projectId)])||{};
  const approved=num(c.approved_marker_count)+num(c.approved_story_evidence_count),verified=num(c.verified_marker_count),blockers=[];let score=0;if(approved>0)score+=12;else blockers.push('No approved CAIP evidence is available.');if(verified>0)score+=8;else blockers.push('No approved temporal evidence has source-observed/confirmed verification.');return{score,approved_evidence_count:approved,verified_evidence_count:verified,blockers};
}
export async function loadCreativeReadinessIntelligence(db,creativeProjectId,opt={}){
  const project=await one(db,`SELECT creative_project_id,creative_project_key,project_title,project_status,governance_status,lifecycle_stage,content_project_id,product_id,updated_at FROM creative_projects WHERE creative_project_id=? LIMIT 1`,[id(creativeProjectId)]);if(!project)return null;const productId=id(project.product_id);
  const [product,evidence,content,pipeline]=await Promise.all([productId?loadProductAvailabilityIntelligence(db,productId,{forecastUnits:opt.forecastUnits||1}):null,evidenceReadiness(db,project.creative_project_id),contentReadiness(db,project.content_project_id),one(db,`SELECT creative_business_pipeline_id,pipeline_status,social_handoff_status,storefront_collection_id,accounting_period_month,finished_inventory_reference,updated_at FROM creative_business_pipelines WHERE creative_project_id=? OR (? > 0 AND product_id=?) ORDER BY updated_at DESC,creative_business_pipeline_id DESC LIMIT 1`,[project.creative_project_id,productId,productId])]);
  const dimensions=[],blockers=[];let score=0;const add=(key,label,value,max)=>{dimensions.push({key,label,score:value,max_score:max});score+=value};
  add('product_linkage','Product linkage',productId?15:0,15);if(!productId)blockers.push('Link the Creative Project to a Product.');
  let material=0;if(product){const s=product.availability.state;material=['available_now','can_make','not_inventory_tracked'].includes(s)&&!product.availability.hard_blocked?20:['limited_finished_stock','limited_can_make'].includes(s)?12:4;if(product.shortages.length)blockers.push('Resolve Product material shortages or lot-reconciliation blockers.');}add('materials','Materials / availability',material,20);
  let cost=0;if(product){const c=product.materials.filter(x=>x.consumes_inventory),known=c.filter(x=>x.estimated_forecast_material_cost_cents>0).length,coverage=c.length?known/c.length:1;cost=Math.round(coverage*15);if(coverage<1)blockers.push('Complete or review material cost coverage for the linked Product.');}add('cost','Material cost coverage',cost,15);
  add('evidence','Reviewed CAIP evidence',evidence.score,20);blockers.push(...evidence.blockers);add('content','Content Studio readiness',content.score,20);blockers.push(...content.blockers);
  const gov=low(project.governance_status),ps=low(project.project_status);let gs=['approved','reviewed','ready'].includes(gov)?6:gov?3:0;gs+=['review_ready','ready','complete','approved'].includes(ps)?4:ps?2:0;add('governance','Project governance',Math.min(10,gs),10);
  const unique=[...new Set(blockers.filter(Boolean))];const band=score>=85&&!unique.length?'ready_for_review':score>=70?'nearly_ready':score>=45?'in_progress':'blocked';
  return{creative_project:project,product_availability:product,evidence,content,pipeline,readiness:{score:Math.max(0,Math.min(100,score)),band,dimensions,blockers:unique},automatic_publication:false,provider_execution_active:false,inventory_mutation_active:false,accounting_posting_active:false,mutation_capability:'none'};
}

export function chooseNextSafeAction(bundle){
  const r=bundle?.creative_readiness,p=bundle?.product_intelligence||r?.product_availability,pipe=r?.pipeline;
  if(!r)return{key:'select_creative_project',priority:1,title:'Select a Creative Project',explanation:'Choose a CAIP Creative Project so readiness and blockers can be evaluated.',execution_capability:'none'};
  if(!id(r.creative_project?.product_id))return{key:'link_product',priority:2,title:'Link the Product',explanation:'Product linkage is required before Inventory, Storefront and profitability readiness can be evaluated.',execution_capability:'none'};
  if(p?.availability?.hard_blocked||(p?.shortages||[]).length)return{key:'resolve_material_readiness',priority:3,title:'Resolve Material Readiness',explanation:'Inventory quantity or deterministic purchase-lot reconciliation is blocking a safe production scenario.',execution_capability:'none'};
  const cost=r.readiness?.dimensions?.find(x=>x.key==='cost');if(cost&&cost.score<cost.max_score)return{key:'complete_cost_coverage',priority:4,title:'Complete Material Cost Coverage',explanation:'Some consuming Product resources do not yet have enough cost evidence for dependable profitability review.',execution_capability:'none'};
  if(num(r.evidence?.approved_evidence_count)<=0)return{key:'review_caip_evidence',priority:5,title:'Review CAIP Evidence',explanation:'Approve source-observed evidence before advancing the story/content workflow.',execution_capability:'none'};
  if(!r.content?.linked||num(r.content?.approved_deliverable_count)<=0)return{key:'prepare_content_studio',priority:6,title:'Prepare Content Studio',explanation:'Link or review the Content Studio package and approve at least one deliverable.',execution_capability:'none'};
  if(!pipe)return{key:'sync_business_pipeline',priority:7,title:'Sync the Business Pipeline',explanation:'Create or synchronize the existing cross-module reference spine; this does not post accounting or publish content.',execution_capability:'none'};
  if(low(pipe.social_handoff_status)==='not_ready')return{key:'review_social_handoff',priority:8,title:'Review Social Handoff',explanation:'An operator can review whether social handoff should move to review-ready.',execution_capability:'none'};
  return{key:'review_for_completion',priority:9,title:'Review for Completion',explanation:'Core readiness signals are satisfied. Review existing domain authorities before marking workflow complete.',execution_capability:'none'};
}
export async function listIntelligenceSelectors(db){
  const [products,creative_projects,open_pipeline_candidates]=await Promise.all([many(db,`SELECT product_id,name,slug,status,review_status,product_category,inventory_tracking,inventory_quantity,updated_at FROM products WHERE LOWER(COALESCE(status,''))<>'archived' ORDER BY updated_at DESC,product_id DESC LIMIT 240`),many(db,`SELECT creative_project_id,creative_project_key,project_title,project_status,governance_status,content_project_id,product_id,updated_at FROM creative_projects WHERE LOWER(COALESCE(project_status,''))<>'archived' ORDER BY updated_at DESC,creative_project_id DESC LIMIT 180`),many(db,`SELECT creative_business_pipeline_id,creative_project_id,content_project_id,product_id,pipeline_status,social_handoff_status,updated_at FROM creative_business_pipelines WHERE pipeline_status NOT IN ('complete','archived') ORDER BY updated_at DESC,creative_business_pipeline_id DESC LIMIT 160`)]);
  return{products,creative_projects,open_pipeline_candidates};
}
