-- Release 461 Development-only custom-request commerce runtime authority.
-- Public traffic never creates/alters schema. custom_request_quote_drafts is a prerequisite owned elsewhere.
PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS custom_request_order_status_links (custom_request_order_status_link_id INTEGER PRIMARY KEY AUTOINCREMENT,custom_request_id INTEGER NOT NULL,order_id INTEGER NOT NULL,order_status_token TEXT NOT NULL UNIQUE,link_status TEXT NOT NULL DEFAULT 'active',customer_email TEXT,customer_name TEXT,created_by_user_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,order_stage TEXT NOT NULL DEFAULT 'planning',stage_notes TEXT,stage_updated_at TEXT,expired_at TEXT,voided_at TEXT);
CREATE INDEX IF NOT EXISTS idx_custom_order_status_links_token ON custom_request_order_status_links(order_status_token,link_status);
CREATE TABLE IF NOT EXISTS custom_request_quote_share_links (custom_request_quote_share_link_id INTEGER PRIMARY KEY AUTOINCREMENT,custom_request_id INTEGER NOT NULL,quote_draft_id INTEGER,share_token TEXT NOT NULL UNIQUE,share_status TEXT NOT NULL DEFAULT 'active',customer_name TEXT,customer_email TEXT,title TEXT,quote_total_cents INTEGER NOT NULL DEFAULT 0,scope_summary TEXT,payment_summary_json TEXT DEFAULT '{}',expires_at TEXT,accepted_at TEXT,declined_at TEXT,customer_response_note TEXT,created_by_user_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,voided_at TEXT,expired_at TEXT,lifecycle_note TEXT);
CREATE INDEX IF NOT EXISTS idx_custom_quote_share_links_token ON custom_request_quote_share_links(share_token,share_status);
CREATE TABLE IF NOT EXISTS custom_request_quote_line_items (custom_request_quote_line_item_id INTEGER PRIMARY KEY AUTOINCREMENT,custom_request_id INTEGER NOT NULL,quote_draft_id INTEGER NOT NULL,line_type TEXT NOT NULL DEFAULT 'custom',line_label TEXT NOT NULL,quantity REAL NOT NULL DEFAULT 1,unit_amount_cents INTEGER NOT NULL DEFAULT 0,line_amount_cents INTEGER NOT NULL DEFAULT 0,is_taxable INTEGER NOT NULL DEFAULT 1,line_status TEXT NOT NULL DEFAULT 'active',sort_order INTEGER NOT NULL DEFAULT 100,created_by_user_id INTEGER,updated_by_user_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS custom_request_quote_revisions (custom_request_quote_revision_id INTEGER PRIMARY KEY AUTOINCREMENT,custom_request_id INTEGER NOT NULL,quote_draft_id INTEGER,revision_type TEXT NOT NULL DEFAULT 'changed',revision_status TEXT NOT NULL DEFAULT 'open',revision_notes TEXT,snapshot_json TEXT DEFAULT '{}',created_by_user_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS custom_request_payment_request_drafts (custom_request_payment_request_draft_id INTEGER PRIMARY KEY AUTOINCREMENT,custom_request_id INTEGER NOT NULL,quote_draft_id INTEGER,share_link_id INTEGER,payment_request_key TEXT NOT NULL UNIQUE,payment_request_status TEXT NOT NULL DEFAULT 'review_needed',request_type TEXT NOT NULL DEFAULT 'deposit',amount_cents INTEGER NOT NULL DEFAULT 0,tax_cents INTEGER NOT NULL DEFAULT 0,currency TEXT NOT NULL DEFAULT 'CAD',customer_name TEXT,customer_email TEXT,due_date TEXT,review_notes TEXT,source_payload_json TEXT DEFAULT '{}',created_by_user_id INTEGER,reviewed_by_user_id INTEGER,reviewed_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS custom_request_order_drafts (custom_request_order_draft_id INTEGER PRIMARY KEY AUTOINCREMENT,custom_request_id INTEGER NOT NULL,quote_draft_id INTEGER,share_link_id INTEGER,order_draft_key TEXT NOT NULL UNIQUE,order_draft_status TEXT NOT NULL DEFAULT 'review_needed',customer_name TEXT,customer_email TEXT,subtotal_cents INTEGER NOT NULL DEFAULT 0,shipping_cents INTEGER NOT NULL DEFAULT 0,tax_cents INTEGER NOT NULL DEFAULT 0,total_cents INTEGER NOT NULL DEFAULT 0,currency TEXT NOT NULL DEFAULT 'CAD',fulfillment_notes TEXT,source_payload_json TEXT DEFAULT '{}',created_by_user_id INTEGER,reviewed_by_user_id INTEGER,reviewed_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_custom_quote_line_items_quote ON custom_request_quote_line_items(quote_draft_id,line_status,sort_order);
CREATE INDEX IF NOT EXISTS idx_custom_quote_revisions_request ON custom_request_quote_revisions(custom_request_id,created_at);
CREATE INDEX IF NOT EXISTS idx_custom_payment_request_drafts_request ON custom_request_payment_request_drafts(custom_request_id,payment_request_status,updated_at);
CREATE INDEX IF NOT EXISTS idx_custom_order_drafts_request ON custom_request_order_drafts(custom_request_id,order_draft_status,updated_at);
CREATE TABLE IF NOT EXISTS custom_request_payment_links (custom_request_payment_link_id INTEGER PRIMARY KEY AUTOINCREMENT,custom_request_id INTEGER NOT NULL,payment_request_draft_id INTEGER,quote_draft_id INTEGER,payment_link_key TEXT NOT NULL UNIQUE,link_token TEXT NOT NULL UNIQUE,link_status TEXT NOT NULL DEFAULT 'active',link_url_path TEXT NOT NULL,request_type TEXT NOT NULL DEFAULT 'deposit',amount_cents INTEGER NOT NULL DEFAULT 0,tax_cents INTEGER NOT NULL DEFAULT 0,currency TEXT NOT NULL DEFAULT 'CAD',customer_name TEXT,customer_email TEXT,provider TEXT NOT NULL DEFAULT 'manual_review',provider_reference TEXT,approval_notes TEXT,customer_viewed_at TEXT,customer_ready_at TEXT,customer_note TEXT,approved_by_user_id INTEGER,approved_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,viewed_at TEXT,ready_to_pay_at TEXT,customer_ready_note TEXT,order_id INTEGER,payment_id INTEGER,external_share_status TEXT NOT NULL DEFAULT 'gate_pending',gate_status TEXT NOT NULL DEFAULT 'pending',preferred_provider TEXT NOT NULL DEFAULT 'manual',checkout_redirect_url TEXT,expired_at TEXT,voided_at TEXT,lifecycle_note TEXT);
CREATE TABLE IF NOT EXISTS custom_request_payment_checkout_records (custom_request_payment_checkout_record_id INTEGER PRIMARY KEY AUTOINCREMENT,custom_request_id INTEGER NOT NULL,payment_link_id INTEGER,order_id INTEGER,payment_id INTEGER,provider TEXT NOT NULL DEFAULT 'manual',checkout_status TEXT NOT NULL DEFAULT 'prepared',provider_order_id TEXT,provider_payment_id TEXT,redirect_url TEXT,mode TEXT,source_payload_json TEXT DEFAULT '{}',created_by_user_id INTEGER,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_custom_checkout_records_request ON custom_request_payment_checkout_records(custom_request_id,provider,checkout_status,updated_at);
PRAGMA foreign_key_check;
