// Build 220 — lot-level purchase history for supplies and tools.
import { auditAdminAction, getAdminUserFromRequest, getDb, jsonResponse, normalizeText } from '../_lib/adminAudit.js';
import { ensureProductOffersSchema, normalizeRows } from '../_lib/productOffers.js';

function json(data, status=200){return jsonResponse(data,status,{'Cache-Control':'no-store'});}
function number(value, fallback=0){const n=Number(value);return Number.isFinite(n)&&n>=0?n:fallback;}
function whole(value){const n=Number(value);return Number.isInteger(n)&&n>0?n:0;}
function text(value,max=500){return normalizeText(value).slice(0,max);}

async function access(context){
 const adminUser=await getAdminUserFromRequest(context.request,context.env);if(!adminUser)return{error:json({ok:false,error:'Admin access required.'},401)};
 const db=getDb(context.env);if(!db)return{error:json({ok:false,error:'Database binding is not configured.'},500)};
 return{adminUser,db};
}
async function load(db,itemId){
 const item=await db.prepare(`SELECT site_item_inventory_id,item_name,source_type,external_key,on_hand_quantity,stock_unit_label,usage_unit_label,usage_units_per_stock_unit,unit_cost_cents,supplier_name,supplier_sku,amazon_url,source_url FROM site_item_inventory WHERE site_item_inventory_id=?`).bind(itemId).first();
 if(!item)return null;
 const result=await db.prepare(`SELECT * FROM inventory_purchase_lots WHERE site_item_inventory_id=? ORDER BY COALESCE(purchase_date,received_date,created_at) DESC, inventory_purchase_lot_id DESC`).bind(itemId).all();
 const lots=normalizeRows(result).map(row=>({...row,inventory_purchase_lot_id:Number(row.inventory_purchase_lot_id||0),quantity_received:number(row.quantity_received),quantity_remaining:number(row.quantity_remaining),unit_cost_cents:number(row.unit_cost_cents),shipping_cost_cents:number(row.shipping_cost_cents),tax_cost_cents:number(row.tax_cost_cents)}));
 return{item,lots,summary:{lot_count:lots.length,available_lot_count:lots.filter(row=>row.lot_status==='available'&&row.quantity_remaining>0).length,quantity_remaining:lots.reduce((sum,row)=>sum+number(row.quantity_remaining),0),total_purchase_value_cents:lots.reduce((sum,row)=>sum+Math.round(number(row.quantity_received)*number(row.unit_cost_cents)),0)}};
}
export async function onRequestGet(context){const a=await access(context);if(a.error)return a.error;try{await ensureProductOffersSchema(a.db);const itemId=whole(new URL(context.request.url).searchParams.get('site_item_inventory_id'));if(!itemId)return json({ok:false,error:'An inventory item is required.'},400);const detail=await load(a.db,itemId);if(!detail)return json({ok:false,error:'Inventory item not found.'},404);return json({ok:true,detail});}catch(error){return json({ok:false,error:error?.message||'Inventory lots could not load.'},500)}}
export async function onRequestPost(context){const a=await access(context);if(a.error)return a.error;let body={};try{body=await context.request.json()}catch{return json({ok:false,error:'Invalid JSON body.'},400)};try{await ensureProductOffersSchema(a.db);const itemId=whole(body.site_item_inventory_id);if(!itemId)throw new Error('An inventory item is required.');const lotId=whole(body.inventory_purchase_lot_id);const lotCode=text(body.lot_code,120);if(!lotCode)throw new Error('A lot or batch code is required.');const qtyReceived=number(body.quantity_received);const qtyRemaining=Math.min(qtyReceived,number(body.quantity_remaining,qtyReceived));const fields=[itemId,lotCode,text(body.purchase_date,20)||null,text(body.received_date,20)||null,text(body.supplier_name,180)||null,text(body.supplier_order_number,180)||null,text(body.supplier_sku,180)||null,text(body.asin,40)||null,text(body.source_url,1000)||null,qtyReceived,qtyRemaining,Math.round(number(body.unit_cost_cents)),Math.round(number(body.shipping_cost_cents)),Math.round(number(body.tax_cost_cents)),text(body.expiry_date,20)||null,text(body.storage_location,180)||null,['available','consumed','expired','quarantined','returned'].includes(text(body.lot_status,30))?text(body.lot_status,30):'available',text(body.notes,1000)||null,a.adminUser.user_id];
 if(lotId){await a.db.prepare(`UPDATE inventory_purchase_lots SET lot_code=?2,purchase_date=?3,received_date=?4,supplier_name=?5,supplier_order_number=?6,supplier_sku=?7,asin=?8,source_url=?9,quantity_received=?10,quantity_remaining=?11,unit_cost_cents=?12,shipping_cost_cents=?13,tax_cost_cents=?14,expiry_date=?15,storage_location=?16,lot_status=?17,notes=?18,updated_at=CURRENT_TIMESTAMP WHERE inventory_purchase_lot_id=?1 AND site_item_inventory_id=?19`).bind(lotId,...fields.slice(1,18),itemId).run();}else{await a.db.prepare(`INSERT INTO inventory_purchase_lots (site_item_inventory_id,lot_code,purchase_date,received_date,supplier_name,supplier_order_number,supplier_sku,asin,source_url,quantity_received,quantity_remaining,unit_cost_cents,shipping_cost_cents,tax_cost_cents,expiry_date,storage_location,lot_status,notes,created_by_user_id,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(...fields).run();}
 const detail=await load(a.db,itemId);await auditAdminAction(context.env,context.request,a.adminUser,{action_type:lotId?'inventory_lot_update':'inventory_lot_create',target_type:'site_item_inventory',target_id:itemId,target_key:detail?.item?.item_name||String(itemId),details:{lot_code:lotCode,quantity_received:qtyReceived,quantity_remaining:qtyRemaining}});return json({ok:true,message:lotId?'Purchase lot updated.':'Purchase lot added.',detail});}catch(error){return json({ok:false,error:error?.message||'Inventory lot could not be saved.'},400)}}
export async function onRequestDelete(context){const a=await access(context);if(a.error)return a.error;try{await ensureProductOffersSchema(a.db);const url=new URL(context.request.url);const lotId=whole(url.searchParams.get('inventory_purchase_lot_id'));if(!lotId)return json({ok:false,error:'A purchase lot is required.'},400);const existing=await a.db.prepare(`SELECT * FROM inventory_purchase_lots WHERE inventory_purchase_lot_id=?`).bind(lotId).first();if(!existing)return json({ok:false,error:'Purchase lot not found.'},404);await a.db.prepare(`DELETE FROM inventory_purchase_lots WHERE inventory_purchase_lot_id=?`).bind(lotId).run();await auditAdminAction(context.env,context.request,a.adminUser,{action_type:'inventory_lot_delete',target_type:'site_item_inventory',target_id:Number(existing.site_item_inventory_id||0),target_key:existing.lot_code||String(lotId),details:{quantity_remaining:number(existing.quantity_remaining)}});return json({ok:true,message:'Purchase lot removed.'});}catch(error){return json({ok:false,error:error?.message||'Purchase lot could not be removed.'},400)}}
